### ISSUE TITLE
Problem while trying to compile

### ISSUE THREAD

**Issue by erwrow** [esp8266/Arduino#3895] opened 2017-11-29 22:22 UTC
Hi, i've just downloaded Arduino and installed the esp8266 complement, and when i try to compile some random program, it throws the following error:

Arduino:1.8.5 (Windows 10), Tarjeta:"Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck, Disabled, None"

exec: "C:\\Users\\Erwrow\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++": file does not exist
Error compilando para la tarjeta Generic ESP8266 Module.

Este reporte podría tener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

the sketch (if needed) is the blink one:

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);     // Initialize the LED_BUILTIN pin as an output
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, LOW);   // Turn the LED on (Note that LOW is the voltage level
                                    // but actually the LED is on; this is because 
                                    // it is acive low on the ESP-01)
  delay(1000);                      // Wait for a second
  digitalWrite(LED_BUILTIN, HIGH);  // Turn the LED off by making the voltage HIGH
  delay(2000);                      // Wait for two seconds (to demonstrate the active low LED)
}

**Comment by devyte** [comment] 2017-12-05 01:50
@erwrow I suggest a clean install, both of the IDE and of the core. Also, restart the IDE after installing the core.
Closing as can't reproduce.

**Closed by devyte** 2017-12-05 01:50 UTC
