### ISSUE TITLE
ESP8266 vs. iPhone Hotspots

### ISSUE THREAD

**Issue by PeterESP8266** [esp8266/Arduino#3893] opened 2017-11-29 18:47 UTC
#### Hardware
Hardware:			ESP-12F
Core Version:      	2.3.0

### Description

My Problem:

ESP8266 wakes up --> takes measurement --> looks for known SSIDs --> uploads data --> goes back to deep sleep

This whole process works with android hotspots and other "normal" wifi routers, but for some reason it does not work with hotspots hosted by iPhones. I tried it with iPhones 5SE, 6 and 7 over some time now so the problem should be constant through many iOS versions.

If another device is already connected to the iPhone's hotspot the upload works--> the interesting thing is, that the iPhone does not list the ESP8266 as connected device even though it is connected because otherwise the upload would not work. I've tried different ESP8266 Version from 1 to 12F and some NodeMCUs.

I did not find anything about this problem yet so I'm asking here if there are any known issues with the ESP8266's hotspot preferences.

I am using ESP8266WiFi.h and ESP8266WiFiMulti.h libraries.

### Settings in IDE

Module:  	        Generic ESP8266 Module
Flash Size: 		4MB/1MB
CPU Frequency:		80Mhz

**Comment by devyte** [comment] 2017-12-05 02:13
@PeterESP8266 no MCVE sketch to reproduce the issue. 
I just tested connecting to an iphone's hotspot, and it works with one and two ESPs.
I suggest trying with latest git, as 2.3.0 is ancient. Also, I seem to remember that the iphone is sometimes a bit sketchy with accepting clients when the hotspot window is not on screen, which means make sure the screen is on, and on the hotspot config screen, when the ESP connects.
Closing as can't reproduce.

**Closed by devyte** 2017-12-05 02:13 UTC
