### ISSUE TITLE
Add LWIP2 support for platformio

### ISSUE THREAD

**Issue by Redferne** [esp8266/Arduino#4168] opened 2018-01-15 10:58 UTC
Please add support for building with lwip2 in PlatformIO. Or please provide instructions on how to build with lwip2 without manually editing platformio-build.py file.

**Comment by d-a-v** [comment] 2018-01-15 11:20
What about adding a new script ```platformio-build-lwip2.py``` patched script for a better audience before further integration ?
Could you make a pull-request for that ?

**Comment by Redferne** [comment] 2018-01-16 06:59
Sure, can you please exlain how this new script will be executed by PlatformIO?
I guess it possible to manually edit `~/.platformio/platforms/espressif8266/builder/frameworks/arduino.py` but that kinds of defeats the purpose?

**Comment by ivankravets** [comment] 2018-01-16 09:33
Which changes do you need in build script?

**Comment by Redferne** [comment] 2018-01-17 11:34
To be able to build with lwip2, I made the following change, replace lwip with lwip2 and replace lwip_gcc with lwip2:
```
        join(FRAMEWORK_DIR, "tools", "sdk", "lwip2", "include"),

        "mesh", "wpa2", "smartconfig", "espnow", "pp", "main", "wpa", "lwip2",
```
But I think it should be possible to configure this for your target in platformio.ini instead, like a possiblity to override parts of the CPPPATH and LIBS.

**Comment by ivankravets** [comment] 2018-01-17 11:37
Have you tried http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html ?

**Comment by Redferne** [comment] 2018-01-18 01:27
Yes. Did not work.

**Comment by ivankravets** [comment] 2018-04-13 00:29
Duplicate of https://github.com/platformio/platform-espressif8266/issues/65

Indeed, you can change LWIP using `build_unflags` and `build_flags` options. However, we will add the better option.

**Closed by ivankravets** 2018-04-13 00:29 UTC

**Comment by ivankravets** [comment] 2018-04-20 18:15
See http://docs.platformio.org/en/latest/platforms/espressif8266.html#lwip-variant
