### ISSUE TITLE
http://arduino.esp8266.com/stable/package_esp8266com_index.json file signature verification failed. File ignored.

### ISSUE THREAD

**Issue by nkenna** [esp8266/Arduino#5106] opened 2018-09-03 14:44 UTC
Everything about ESP8266 and NodeMCU just disappeared from my Arduino IDE. This error turns up when I try to access the Board manager:

http://arduino.esp8266.com/stable/package_esp8266com_index.json file signature verification failed. File ignored.
![espp](https://user-images.githubusercontent.com/22357643/44992784-2f637a00-af90-11e8-878e-b5f410c08d76.PNG)

**Comment by Deimos1994** [comment] 2018-09-03 19:17
@nkenna, My works fine... I think the problem on your side.
![123](https://user-images.githubusercontent.com/31592485/44999567-ee3a8c80-afc6-11e8-84cd-1b1745d089fb.JPG)

**Comment by devyte** [comment] 2018-09-03 19:39
Same here. Closing as can't reproduce.

**Closed by devyte** 2018-09-03 19:39 UTC
