### ISSUE TITLE
ESP8266 after restart or power on/off. does not worked

### ISSUE THREAD

**Issue by karenYerevan** [esp8266/Arduino#4104] opened 2018-01-06 11:32 UTC
hi there
i have ESP8266-12E, it is have other power
I flashing esp8266 from arduino uno
aruduino uno -- esp8266
RX -> RXD
TX -> TXD
GND -> GND,GPIO0

After flashing all worck good.
But when esp8266 is restart or power on/off , esp8266  stopping works

![img_0291](https://user-images.githubusercontent.com/9501068/34639296-b5746eb2-f2f6-11e7-884a-d15d4c0b9dcf.jpg)

**Comment by devyte** [comment] 2018-01-06 15:48
@karenYerevan this is the third time advising you of the same. This is not a general support forum for your particular project. If you have an issue with the code in this repo, then open an issue and provide all the requested details, including a detailed explanation, the steps to reproduce the issue, serial debug messages, and an example minimal sketch.
This issue ignored the entire issue template. Closing due to lack of info.

**Closed by devyte** 2018-01-06 15:48 UTC
