### ISSUE TITLE
Exception 3: LoadStoreError: Processor internal physical address or data error during load or store

### ISSUE THREAD

**Issue by alexander-22** [esp8266/Arduino#7257] opened 2020-05-01 14:57 UTC
There is an old firmware that works without problems when compiled using the "ESP8266 core for Arduino" library version 2.4.2. when compiled with versions higher than 2.4.2 and up to the last one, an error occurs. When the button is clicked in the browser, the ESP8266 is overloaded. A dump of the error:
Exception 3: LoadStoreError: Processor internal physical address or data error during load or store
PC: 0x4000bf64
EXCVADDR: 0x4025dd5f

Decoding stack results
0x4020efd4: ESPWebMQTTRelay::handleSchedulesConfig() at E:\Andruino\ESP8266\Sonoff_Relay3/Sonoff_Relay3.ino line 1723
0x4021afc0: String::equals(String const&) const at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\cores\esp8266\WString.cpp line 502
0x40203cac: esp8266webserver::FunctionRequestHandler ::handle(esp8266webserver::ESP8266WebServerTemplate &, HTTPMethod, String) at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/detail/RequestHandlersImpl.h line 40
0x40224e6b: std::_Function_handler    (ESPWebMQTTRelay*)> >::_M_invoke(std::_Any_data const&) at c:\users\���������\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/functional line 2073
0x401000e1: std::function ::operator()() const at c:\users\���������\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/functional line 2465
0x40203ce2: esp8266webserver::FunctionRequestHandler ::handle(esp8266webserver::ESP8266WebServerTemplate &, HTTPMethod, String) at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/detail/RequestHandlersImpl.h line 47
0x40208eba: esp8266webserver::ESP8266WebServerTemplate ::_handleRequest() at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h line 667
0x40100364: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\cores\esp8266\core_esp8266_main.cpp line 160
0x40208fcb: esp8266webserver::ESP8266WebServerTemplate ::handleClient() at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h line 335
0x402107e4: ESP8266WiFiAPClass::softAPgetStationNum() at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi\src\ESP8266WiFiAP.cpp line 319
0x4021c336: __delay(unsigned long) at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\cores\esp8266\core_esp8266_wiring.cpp line 54
0x40209127: ESPWebBase::loop() at C:\Users\8523~1\AppData\Local\Temp\arduino_build_168983\sketch\ESPWeb.cpp line 167
0x40219848: Print::println() at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\cores\esp8266\Print.cpp line 186
0x4020c341: loop() at E:\Andruino\ESP8266\Sonoff_Relay3/Sonoff_Relay3.ino line 2532
0x4021baf8: loop_wrapper() at C:\Users\���������\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\cores\esp8266\core_esp8266_main.cpp line 180

String to swear at:
1723  page += ESPWebBase::tagInput(typeText, FPSTR(paramScheduleHour), "0", F("size=2 maxlength=2"));

 ets Jan  8 2013,rst cause:1, boot mode:(3,7)
load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
SDK:2.2.2-dev(38a443e)/Core:2.6.3=20603000/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-16-ge23a07e/BearSSL:89454af

I can understand if my code would not work at all, but when compiled on version 2.4.2, everything works without problems.

**Comment by devyte** [comment] 2020-05-01 19:46
@alexander-22 The list of fixed critical stability issues since 2.4.2 is so long that I can't even look it up in a reasonable amount of time. I think some of them even canceled each other out. And then there's the sdk updates since that time, which changed some behavior details that were out of our control. Then there has been a whole lot of code changed around in our core since that time.
Your code above shows use of ESPWebMQTTRelay. We don't accept issues with 3rd party lib involvement.
Please reduce your code to MCVE that only uses our core api, or work with the ESPWebMQTTRelay author or community to do so. If you can still reproduce the problem with that, please open a new issue, and follow the template instructions which you ignored here. We can discuss further at that time.
Closing due to not compliant.

**Closed by devyte** 2020-05-01 19:46 UTC
