### ISSUE TITLE
Search mDNS when resolving DNS names

### ISSUE THREAD

**Issue by madpilot** [esp8266/Arduino#2373] opened 2016-08-08 00:17 UTC
Feature request: When automatically resolving domain names, would it be possible to search using the mDNS broadcast address if the domain name ends with .local?

If the domain name ends with .local, using a DNS server ip of 224.0.0.251 and a port of 5353 is all that needs to happen, so there is minimal code change.

If someone wants to point the right file, I'm happy to change it and put it in a PR.

**Comment by n8henrie** [comment] 2016-09-12 21:57
This would be great. I'm trying to get mdns to work right now just for this purpose but not having any luck.

@madpilot -- do you have a functioning `hostname.local` resolution workaround currently?

**Comment by madpilot** [comment] 2016-09-12 22:10
@n8henrie Not right now - I finally have master running in my IDE, so I'm hoping to have a poke around this week.

**Comment by railnerd** [comment] 2017-03-18 10:07
should be possible to pull latest stable lwip (2_0_2) and

#define LWIP_DNS_SUPPORT_MDNS_QUERIES 1

**Comment by me-no-dev** [comment] 2017-03-18 10:13
we should actually port the mdns from ESP32. It has host and service queries and all. I need to add a couple of features before merging though.

**Comment by railnerd** [comment] 2017-03-19 01:16
well, the root cause for not being able to resolve .local addresses lies in lwip, but certainly parity between ESP32 and ESP8266 would be nice.

**Comment by madpilot** [comment] 2017-03-19 08:37
I ended up writing a small library that does this: https://github.com/madpilot/mDNSResolver

**Comment by devyte** [comment] 2017-10-14 06:14
@me-no-dev will you be porting the esp32 mdns? no hurry. Also, it may make more sense after migrating to lwip2.

**Comment by devyte** [comment] 2017-10-14 06:15
@madpilot I assume from your last comment that your mDNSResolver addresses this issue?

**Comment by me-no-dev** [comment] 2017-10-14 06:26
i hope some not so full version of it can be ported. 3 interfaces and IPv6 on ESP32 make things a bit intensive and i do not know how 8266 will coop even with v4 on 2 interfaces. But there is a way I imagine to port most of it (once done)

**Comment by devyte** [comment] 2019-01-11 19:15
Automatic switchover to MDNS lookup in HostByName() for .local hostnames would forcibly pull in the MDNS code for all users, which is undesirable. I suggest a simple app function along the lines of:
```
myLookup(hostname)
{
  if(hostname ends in .local)
    look up with MDNS lib
  else
    look up with hostByName()
}
```
Closing.

**Closed by devyte** 2019-01-11 19:15 UTC
Labels: waiting for feedback
