### ISSUE TITLE
ESP8266WiFiMulti needs a timeout mechanism

### ISSUE THREAD

**Issue by gavanfantom** [esp8266/Arduino#3014] opened 2017-03-02 18:09 UTC
#### Hardware
Hardware:			?ESP-07?
Core Version:      	?2.3.0?

### Description

When using ESP8266WiFiMulti's run() method to connect to a WiFi network, it is possible for the connection to neither succeed nor fail, leading to the run() method never returning. A good example of this would be connecting to a WiFi network where the DHCP server is inoperative.

A mechanism to specify a timeout should exist.

The relevant code in run() looks like this:

                // wait for connection or fail
                while(status != WL_CONNECTED && status != WL_NO_SSID_AVAIL && status != WL_CONNECT_FAILED) {
                    delay(10);
                    status = WiFi.status();
                }

I think that simply exiting the loop after a timeout hits would be sufficient - taking the latest status should be harmless and should allow the rest of the code to operate with the most recent information available.

An optional argument specifying a timeout would probably be a good way to implement this. Alternatively, a timeout could be set as member variable by the constructor.

**Comment by devyte** [comment] 2018-01-12 03:07
Closing as duplicate of #3993 .

**Closed by devyte** 2018-01-12 03:07 UTC
Labels: component: libraries, level: easy, type: bug
