### ISSUE TITLE
Update to latest SDK

### ISSUE THREAD

**Issue by derpicknicker1** [esp8266/Arduino#20] opened 2015-03-31 04:27 UTC
Used version is 0.9.5

Latest SDK version is esp_iot_sdk_v1.0.0_15_03_20 released

Fix bugs:
* Interrupt during flash erasing will cause wdt reset
* Read/write rtc memory
* If router disconnect to ESP8266, ESP8266 won’t reconnect
* Connect to router which hid its SSID

Full Changelog & Download:
http://bbs.espressif.com/viewtopic.php?f=5&t=286

**Comment by igrr** [comment] 2015-03-31 05:34
Duplicate of #1, we've already upgraded in b64079f.

**Closed by igrr** 2015-03-31 05:34 UTC

**Comment by derpicknicker1** [comment] 2015-03-31 10:09
Ok. I downloaded the win-files.zip here yesterday and the versionnumber in ..\arduino-1.6.1\hardware\tools\esp8266\sdk\version is 0.9.5

**Comment by igrr** [comment] 2015-03-31 10:14
Yep, it's staged for the next release.
