### ISSUE TITLE
IDE Updation issue 

### ISSUE THREAD

**Issue by wounder123** [esp8266/Arduino#6470] opened 2019-08-30 12:41 UTC
Serial window::
fork/exec C:\Documents and Settings\ANJUSHA\Local Settings\Application Data\Arduino15\packages\esp8266\tools\python\3.7.2-post1/python.exe: %1 is not a Valid Win32 application.
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

After updating the core of esp8266 into 2.5.2 ,these issue come
I am also try to  update  Arduino ide but no use. .
How to solve this issue?

**Comment by devyte** [comment] 2019-08-30 14:31
@earlephilhower is this a duplicate of #6467?

**Comment by earlephilhower** [comment] 2019-08-30 14:54
Dup of #6467.  Tracking there.

**Closed by earlephilhower** 2019-08-30 14:54 UTC
