### ISSUE TITLE
ESP8266WIFI

### ISSUE THREAD

**Issue by goagem** [esp8266/Arduino#3703] opened 2017-10-10 14:53 UTC
Can anyone help me? 

C:\Users\Simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src\APScan.cpp: In member function 'bool APScan::start()':

APScan.cpp:18: error: no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

   results = WiFi.scanNetworks(false, settings.apScanHidden); // lets scanNetworks return hidden APs. (async = false & show_hidden = true)

                                                           ^

C:\Users\Simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src\APScan.cpp:18:59: note: candidate is:

In file included from C:\Users\Simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src\APScan.h:6:0,

                 from C:\Users\Simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src\APScan.cpp:1:

C:\Users\Simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note: int8_t ESP8266WiFiClass::scanNetworks(bool)

     int8_t scanNetworks(bool async = false);

            ^

C:\Users\Simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note:   candidate expects 1 argument, 2 provided

exit status 1
no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

Ive tried to change the network thingy to results = WiFi.scanNetworks(); but it dosn´t work.

**Comment by devyte** [comment] 2017-10-10 15:20
@goagem no basic info, no IDE info, no sketch. You pretty much ignored the entire issue template.
I suggest deleting the Arduino IDE and Arduino dir (backup your projects first),  and doing a clean install from scratch. Also, rather than use the release version from the boards manager, I suggest using git,  see readthedocs for installation instructions.
I'm using the scanNetworks method myself, and I don't have build issues.
Closing due to lack of info, can't reproduce, off topic, see #3655 .

**Closed by devyte** 2017-10-10 15:20 UTC
