### ISSUE TITLE
In the environment which having a weak WiFi signal, WiFi.status() took a long long time.

### ISSUE THREAD

**Issue by kalsolio** [esp8266/Arduino#4798] opened 2018-06-08 08:29 UTC
with the **Correct SSID and password**, if the wifi is so week, Visible, but very weak , WiFi.status() will took many Minutes. 
ps. if the wifi is not found, or the password is error, .status() will work ok.

origin code:
```
  Serial1.resetESP();
  delay(3000); //wait while WiFiLink firmware connects to WiFi with Web Panel settings
  WiFi.init(&Serial1);
  Serial.println("wait wifi status...");
  while (WiFi.status() != WL_CONNECTED) {
     delay(100);
  }
```
After I change it like this, reboot my board to try more times,  there is a chance to connect WiFi success 
```
  WiFi.init(&Serial1);
  Serial.println("wait wifi status...");

  wdt_enable(WDTO_8S);
  delay(7000);
  wdt_reset();

  while (WiFi.status() != WL_CONNECTED) {
   delay(100);
  }
```

**Comment by devyte** [comment] 2018-06-08 20:32
Issue template was completely ignored.
In any case, I'm assuming that this is a duplicate of #4792 .
Closing.

**Closed by devyte** 2018-06-08 20:32 UTC
