### ISSUE TITLE
Error Downloading from Board Manager

### ISSUE THREAD

**Issue by fh9g12** [esp8266/Arduino#1787] opened 2016-03-17 09:33 UTC
### Basic Infos

Cant install board using either stable or Staging link
#### Hardware

Windows 7
Arduino 1.6.8
Core Version:       ?2.1.0-rc2?
### Description

Hello there, when I try to install the boards via the board manager in arduino 1.6.8 ( also tried 1.6.5 ) I always get a 'Error Downloading' shown in the bottum of the board manager on the first package (I've tired all version as well ), But if I go to the links I can download them manually... I am aware this is probably a permissions issue or something at my end, but I was wondering if other people had had a similar problem / have a solution / could tell me where to place the manually downloaded files so 'it thinks its downloaded them' ??
##

**Comment by fh9g12** [comment] 2016-03-18 09:37
I 'man'ed up and just learn how do it the git repositry way instead... although the initial issue still stands..

**Comment by drewfish** [comment] 2016-08-01 18:21
I've just run into this too, specifically:
* Arduino IDE 1.6.9
* added `http://arduino.esp8266.com/stable/package_esp8266com_index.json` to the additional board manager URLs in the preferences (along with the json for adafruit and sparkfun boards)
* tried to install 2.3.0 of esp8266 in the board manager
* got `Error downloading https://github.com/igrr/mkspiffs/releases/download/0.1.2/mkspiffs-0.1.2-osx.tar.gz`

**Comment by drewfish** [comment] 2016-08-01 18:24
Hmmm... just tried again and it worked...

**Comment by vishva8kumara** [comment] 2017-05-09 20:27
I tried several times and it failed. So I manually downloaded the json file from http://arduino.esp8266.com/versions/2.3.0/package_esp8266com_index.json and mirrored on http://info.lk/static/package_esp8266com_index.json

Now it work for me. I'm leaving the file on that server for anyone having the same problem to use.

**Comment by ballew** [comment] 2017-05-16 04:49
I can't download it either. Used the link provided by vishva8kumara which worked. Thanks vishva8kumara

**Comment by sunilvb** [comment] 2017-05-17 12:09
Unable to install the package as well... 
get the following error 

*Error downloading https://github.com/esp8266/Arduino/releases/download/2.3.0/esp8266-2.3.0.zip 
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target*

Although, I can manually point the browser to github and download the esp8266-2.3.0zip.

**Comment by faisalzed** [comment] 2017-06-02 22:15
Just disable the firewall . go and solve it all

**Comment by devyte** [comment] 2017-10-18 00:31
Can't reproduce, closing.

**Closed by devyte** 2017-10-18 00:31 UTC
Labels: type: troubleshooting
