### ISSUE TITLE
Arduino max() min() functions doesn't work when I load ESP Libraries

### ISSUE THREAD

**Issue by jamilbn** [esp8266/Arduino#2073] opened 2016-05-31 03:03 UTC
### Hardware
Hardware:			ESP-12
Core Version:      	2.2.0

### Description

Arduino max() min() functions doesn't work when I load ESP Libraries

`#include <ESP8266WiFi.h>`
`#include <WiFiClient.h>`
`#include <ESP8266WebServer.h>`
`#include <ESP8266HTTPUpdateServer.h>`
`#include <ESP8266mDNS.h>`
`#include <FS.h>`

### Error

error: 'min' was not declared in this scope
error: 'max' was not declared in this scope

When I comment those libraries my sketch works just fine with the functions max an min as they should work.

https://www.arduino.cc/en/Reference/Max

**Comment by WereCatf** [comment] 2016-05-31 12:59
It's an issue I stumbled upon myself, too. I just used _min() and _max() in my code instead.

**Comment by igrr** [comment] 2016-06-01 03:16
Closing as duplicate of #398

**Closed by igrr** 2016-06-01 03:16 UTC
