### ISSUE TITLE
Exception number 3 in versions higher than 2.50

### ISSUE THREAD

**Issue by franciscogimeno2000** [esp8266/Arduino#6818] opened 2019-11-20 17:24 UTC
### Basic Infos

- [ *] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [* ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [* ] I have tested that the issue is present in current master branch (aka latest git).
- [* ] I have searched the issue tracker for a similar issue.
- [* ] If there is a stack dump, I have decoded it.
- [* ] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-01]
- Core Version:			[2.6.1]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  	[Generic ESP8266]
- Flash Mode:	[dout compatible]
- Flash Size: 		[1MB fs:none ]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:	[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200)

### Problem Description
Exception number 3 in versions higher than 2.50
What I am going to describe compiles and works without problems in version 2.50 but in the following ones, that exception number jumps in a part of the code that I have isolated.
As I say, this in version 2.50 compiles and works without problems.

### CODE

#include <Ticker.h>
#include <ESP8266WiFi.h>
#include <DNSServer.h>
#include <ESP8266WebServer.h>
#include <EEPROM.h>
#include <Ethernet.h>
#include <ESP8266HTTPClient.h>

#include "config.h"     

void setup()
 {
..
...
....
....
webServer.on("/config.php", []()
			{
			webServer.send(200, "text/html", webconfig());
			});

}

void loop() 
{
dnsServer.processNextRequest();
webServer.handleClient();
}

webconfig()
{
String webcon;
webcon = CONFIG_page;  //<-----------When you try to do this the exception is triggered.
return  webcon;
}

//-------------------------------------------
//file config.h

const char CONFIG_page[] PROGMEM = R"=====(
//<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
//<html>
 // <head>
  //  <meta http-equiv="cache-control" content="max-age=0" />
 //   <meta http-equiv="cache-control" content="no-cache" />
  //  <meta http-equiv="expires" content="0" />
 //   <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
 //   <meta http-equiv="pragma" content="no-cache" />
  // ..
 // .</head>
 // ..

// more code htlm web page---------------
)=====";
//---------------------------------------------------

```

### Debug Messages

```
Exception (3):
epc1=0x4000bf64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40243923 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffca0 end: 3fffffc0 offset: 01a0
3ffffe40:  40243923 3ffffeb0 3fff0a04 40209970  
3ffffe50:  402092d0 3ffffeb0 3fff0a04 40201599  
3ffffe60:  3fff1400 001c001f 80fe8900 40209500  
3ffffe70:  00000001 80000004 3ffeec00 40209604  
3ffffe80:  80000010 00000000 3ffffeb0 80209951  
3ffffe90:  00000001 00000001 3fff0a04 40202fb8  
3ffffea0:  00000001 00000001 3fff0a04 40204682  
3ffffeb0:  36626500 40201100 80fffee0 40209951  
3ffffec0:  00000001 402011f8 3fff0a04 401000e1  
3ffffed0:  3fff0a04 3ffee920 3fff0a04 40202fee  
3ffffee0:  3fff1400 0010001f 80000000 3ffe8718  
3ffffef0:  3fff0a04 3ffee920 3ffee8e0 402049ba  
3fffff00:  3fff10ac 0010001f 00c6a7f0 3fff1400  
3fffff10:  000000af 80006e69 40100278 0000de8b  
3fffff20:  00000001 3ffee920 3ffee8e0 40206bd0  
3fffff30:  00000001 00000000 00001388 401009ef  
3fffff40:  00000000 3fff10e4 3ffee8e0 3ffeed5c  
3fffff50:  00000001 3ffee904 3ffee8e0 40204b8c  
3fffff60:  4020c958 00000000 00001388 40206f2f  
3fffff70:  00000000 3fff10e4 3ffeed1c 4020768c  
3fffff80:  3fffdad0 00000000 3ffeed1c 40204c36  
3fffff90:  3fffdad0 00000000 3ffeed1c 4020ab11  
3fffffa0:  3fffdad0 00000000 3ffeed1c 4020ac20  
3fffffb0:  feefeffe feefeffe 3ffe8718 40100cb1  
<<<stack<<<
```

**Comment by franciscogimeno2000** [comment] 2019-11-20 17:45
Hello, is the description wrong?

**Comment by franciscogimeno2000** [comment] 2019-11-20 17:49
OK thanks.

**Comment by earlephilhower** [comment] 2019-11-20 17:50
Looks like you were editing when I closed.  You will need to decode that stack dump and provide a *full* compilable, working MCVE so that we can look at it (as requested in the template)

As of now, there's nothing usable for debug given here yet.

**Comment by earlephilhower** [comment] 2019-11-20 17:51
And, if I had to guess, you're running out of memory copying a massive const char * stored in RAM into an equally massive String also stored in RAM.

**Comment by franciscogimeno2000** [comment] 2019-11-20 17:54
ok , Two questions
1 How is it decoded?
2 Why does version 2.50 work?

**Comment by earlephilhower** [comment] 2019-11-20 18:41
Sorry, but without a full MCVE and a properly decoded stack trace including the callbacks there is nothing to be done here.

**Comment by devyte** [comment] 2019-11-20 19:50
@franciscogimeno2000 this is better than your other attempt, but it is still not quite there.
The requirement is that you provide an MCVE: Minimal Complete Verifiable Example. In other words, a complete sketch where you have pulled out all unnecessary code, that can be loaded into the IDE and built, then flashed to a board to verify the issue you face. This is so that we can reproduce the issue on our end and investigate the cause.
Please edit your OP and replace the sketch with

**Comment by franciscogimeno2000** [comment] 2019-11-20 22:54
The problem is the size, the number of characters that happened to the string.
I have left a few characters and it works.
The question is, because in version 2.50 it works without problems and in the following ones it does not. That has changed in the updates.

**Comment by franciscogimeno2000** [comment] 2019-11-20 22:57
Can you tell me where I find information about what the configuration parameters of the chip do in the arduino ide?

**Comment by devyte** [comment] 2019-11-21 02:22
Available heap changes a bit from release to release. Also, you could be running into fragmentation, i.e.: you have enough free heap, but no single piece of it is big enough to hold a required allocation.
If it works with a slightly smaller html string, then a memory issue is most likely.
One thing you can do is use the ESPClass, there are methods to get free heap and a fragmentation metric. Look at Esp.h.
It is in general not a good idea to server html from embedded strings. Instead, put static content in files in a (small) FS, and serve dynamic data as a json to be loaded by the browser into the static html. This is what I do.

I don't see a core issue, so closing for now. If further info is provided that shows otherwise, then I'll reopen.

**Closed by devyte** 2019-11-21 02:22 UTC
Labels: waiting for feedback

**Comment by franciscogimeno2000** [comment] 2019-11-21 10:17
Thank you for your help, I have achieved a good decoding.


CODE:

``
Exception 3: LoadStoreError: Processor internal physical address or data error during load or store
PC: 0x4000bf64
EXCVADDR: 0x40242cf3

Decoding stack results
0x40209aa3: String::String(char const*) at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266\WString.cpp line 34
0x40209220: HardwareSerial::write(unsigned char const*, unsigned int) at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/HardwareSerial.h line 159
0x402014ae: Montarwebconfig() at C:\Users\IEUser\Documents\Arduino\AVERESTESIVAOQUEREDUCI/AVERESTESIVAOQUEREDUCI.ino line 696
0x40209500: Print::print(String const&) at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266\Print.cpp line 116
0x402098a1: String::invalidate() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266\WString.cpp line 140
0x402045d2: std::_Function_handler ::_M_invoke(const std::_Any_data &) at C:\Users\IEUser\Documents\Arduino\AVERESTESIVAOQUEREDUCI/AVERESTESIVAOQUEREDUCI.ino line 480
0x402098a1: String::invalidate() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266\WString.cpp line 140
0x402011f8: esp8266webserver::FunctionRequestHandler ::canHandle(HTTPMethod, String) at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\ESP8266WebServer\src/detail/RequestHandlersImpl.h line 23
0x401000e1: std::function ::operator()() const at c:\users\ieuser\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/functional line 2465
0x40202f3e: esp8266webserver::FunctionRequestHandler ::handle(esp8266webserver::ESP8266WebServerTemplate &, HTTPMethod, String) at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\ESP8266WebServer\src/detail/RequestHandlersImpl.h line 47
0x4020490a: esp8266webserver::ESP8266WebServerTemplate ::_handleRequest() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h line 665
0x40100278: millis() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266\core_esp8266_wiring.cpp line 188
0x40206b20: WiFiServer::available(unsigned char*) at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\ESP8266WiFi\src\WiFiServer.cpp line 116
0x401009ef: free(void*) at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266\umm_malloc\umm_malloc.cpp line 362
0x40204adc: esp8266webserver::ESP8266WebServerTemplate ::handleClient() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h line 335
0x40206e7f: WiFiUDP::parsePacket() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\ESP8266WiFi\src\WiFiUdp.cpp line 199
0x402075dc: DNSServer::processNextRequest() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\DNSServer\src\DNSServer.cpp line 166
0x40204b86: loop() at C:\Users\IEUser\Documents\Arduino\AVERESTESIVAOQUEREDUCI/AVERESTESIVAOQUEREDUCI.ino line 624
0x4020aa61: esp_schedule() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266\core_esp8266_main.cpp line 112
0x4020ab70: loop_wrapper() at C:\Users\IEUser\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266\core_esp8266_main.cpp line 179
``
