### ISSUE TITLE
problems with WiFi.setPhyMode

### ISSUE THREAD

**Issue by onkelfunny** [esp8266/Arduino#1354] opened 2016-01-02 21:32 UTC
```
Sketch 1:
void setup() {
    WiFi.disconnect(true);
    delay(2000);
    WiFi.begin("ABCD12345678", "12345678");
}
```

```
Sketch 2:
void setup() {
    WiFi.disconnect(true);
    delay(2000);
    WiFi.setPhyMode(WIFI_PHY_MODE_11B);
    WiFi.begin("ABCD12345678", "12345678");
}
```

The esp runs great with Sketch 1. After Flashing Sketch 2 i can't connect to the Router.
Because Sketch 2 not working i tried Sketch 1 and now this is not working.

After a complete Flash erase, Sketch 1 works without problems.
##

**Comment by Links2004** [comment] 2016-01-02 21:48
may the SDK stores the WIFI_PHY_MODE_11B setting,
does your router support WiFi mode B?

**Comment by onkelfunny** [comment] 2016-01-02 22:01
the router don't support mode b.

i ave tried to set mode g and mode n but without luck.

I think the idk stores the information... the question ist how i can reset the mode without full flash reset?

**Comment by Links2004** [comment] 2016-01-02 22:30
the sdk docs not write over it, you can try set it to 0 or
```ESP.eraseConfig();``` this will delete all SDK config

**Comment by devyte** [comment] 2017-10-19 05:38
I can't reproduce this with latest git and my router. Closing.

**Closed by devyte** 2017-10-19 05:38 UTC
