### ISSUE TITLE
Queue.h error not resolved

### ISSUE THREAD

**Issue by Yavar007** [esp8266/Arduino#4218] opened 2018-01-23 02:49 UTC
#### Hardware
Hardware:			ESP-01S Module with ESP8266 wifi Core

### Description

Problem description:
just that damn queue.h errror i dont know how do you work with this library without problems?
in all examples they use this library but hoooooow? why i get errors ? :|

### Sketch

```cpp

#include <ESP8266WiFi.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
fatal error :queue.h:no such file or directory...............
```

**Comment by devyte** [comment] 2018-01-25 19:47
@Yavar007 Most likely you have a dirty installation, wrong board selected, or some incompatible library that hasn't been ported to the ESP.
There are currently no known build issues, as shown by CI. Also, I can't reproduce this with any of my own applications, and I just tested with an empty sketch like shown above, and everything builds fine.
Closing due to can't reproduce.

**Closed by devyte** 2018-01-25 19:47 UTC
