### ISSUE TITLE
flush() is a TX related function

### ISSUE THREAD

**Issue by jandrassy** [esp8266/Arduino#4018] opened 2017-12-24 14:31 UTC
WiFiClient.flush should send all data from tx buffer. it is not true that in Arduino world it is a rx buffer thing. the Client class is inherited from Print class and the [flush method](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamflush/)  is from Print. And in Print implementations the flush is a tx thing. And the reference for the Client class implementation is [Ethernet library](https://www.arduino.cc/en/Reference/ClientFlush).

**Comment by d-a-v** [comment] 2017-12-25 17:46
Duplicate of issue #1002.
This has been very recently fixed by #3967 and is currently in git master (not 2.4.0-rc2).

**Comment by devyte** [comment] 2017-12-25 18:24
Closing as duplicate of #1002 .

**Closed by devyte** 2017-12-25 18:24 UTC

**Comment by d-a-v** [comment] 2017-12-25 23:42
@jandrassy  (from #3967)
> and moving flush() from Stream to Print?

The ::flush() beeing a tx not rx stuff was #1002's point and fix is merged.
::flush() in arduino is declared in Print:: which is inherited by Stream::, and our flush() is declared only in Stream::. 


So you were suggesting for moving it to Print:: ?
Can you please elaborate ?

**Comment by jandrassy** [comment] 2017-12-26 06:04
flush() accompanies write functions in Print. so yes it should be in Print. Stream adds read functions. flush() is important for effective implementations of write() with buffering. most Arduino user programmers do not use flush(). Therefore in my implementations of Print (mostly derived from Stream or Client) I add flush into available() if rx buffer is empty and tx buffer is not sent. It is much better the [sending by one byte over some protocol with frame bytes overhead.](https://github.com/jandrassy/UnoWiFiDevEdSerial1/wiki/Story)

**Comment by d-a-v** [comment] 2017-12-26 13:52
Since current implementation does not exactly follows arduino's core library, this is a fair proposal.
Have you considered making yourself a pull request for this ?

**Comment by jandrassy** [comment] 2017-12-26 15:29
no, because it would take to much time for me to fork the project and set it up for testing

**Comment by d-a-v** [comment] 2017-12-26 22:04
I hope you'll have time to try #4029
