### ISSUE TITLE
Invalid library found in (Arduino 1.6.6)

### ISSUE THREAD

**Issue by domonetic** [esp8266/Arduino#993] opened 2015-11-09 13:57 UTC
in 1.6.6 version on select genericesp8266 board 
Invalid library found in C:\Users\maxid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-1160-gef26c5f\libraries\esp8266: C:\Users\maxid\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-1160-gef26c5f\libraries\esp8266

**Comment by grahamehorner** [comment] 2015-11-09 16:17
also getting this with a clean install of arduino.cc IDE v1.6.6 and esp8266 from git hub following instructions on page

**Comment by domonetic** [comment] 2015-11-09 16:24
I have a clean install and use the staging repository

2015-11-09 13:17 GMT-03:00 Grahame Horner <notifications@github.com>:

> also getting this with a clean install of arduino.cc IDE v1.6.6 and
> esp8266 from git hub following instructions on page
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/esp8266/Arduino/issues/993#issuecomment-155111642>.
>



-- 
El que pregunta aprende, y el que contesta aprende a responder.

No a la obsolecencia programada:
http://www.rtve.es/noticias/20110104/productos-consumo-duran-cada-vez-menos/392498.shtml

Linux User #495070
http://domonetic.com/blog

**Comment by WheezeNL** [comment] 2015-11-09 17:03
Yesterday I had the same problem.
IDE 1.6.6 on Win10 gives a load of warnings and errors.
IDE 1.6.5 works perfectly.

**Comment by Links2004** [comment] 2015-11-09 17:04
the problem is noted done here: #965
currently we not support 1.6.6 it may work in some cases
but OTA is for example broken (work is going in there).

**Comment by domonetic** [comment] 2015-11-09 17:15
ok ok back to the past!!!
Thanks

2015-11-09 14:04 GMT-03:00 Markus <notifications@github.com>:

> the problem is noted done here: #965
> <https://github.com/esp8266/Arduino/issues/965>
> currently we not support 1.6.6 it may work in some cases
> but OTA is for example broken (work is going in there).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/esp8266/Arduino/issues/993#issuecomment-155126101>.
>



-- 
El que pregunta aprende, y el que contesta aprende a responder.

No a la obsolecencia programada:
http://www.rtve.es/noticias/20110104/productos-consumo-duran-cada-vez-menos/392498.shtml

Linux User #495070
http://domonetic.com/blog

**Comment by igrr** [comment] 2015-11-15 21:44
Fixed with 74aec43.

**Closed** 2015-11-30 08:32 UTC
Labels: arduino 1.6.6

**Comment by NimdaEng** [comment] 2017-06-15 13:23
delete all folders in C:\Users\<USER>\Documents\Arduino
