### ISSUE TITLE
Serial Port Error 

### ISSUE THREAD

**Issue by iemektar** [esp8266/Arduino#4607] opened 2018-04-04 15:27 UTC
#### Platform

- Hardware:				ESP-01
- Core Version:			28.03.2018
- Development Env:		Arduino IDE 1.8.5
- Operating System:		Windows

### Settings in IDE

-Board: Generic ESP8266 Module
-Flash Mode: QIO
-Flash Size: 512K (no SPIFFS)
-Debug Port: Disabled
-Debug Level: None
-IwIP: v2 Lower Memory
-Reset Method: ck
-Crystal Frequency: 24 MHz
-Flash Frequency: 40 MHz
-CPU Frequency: 80 MHz
-Buildin Led: 2
-Upload Speed: 115200
-Erase Flash: Only sketch
-Port: COM3

### Problem Description

I have Arduino Mega 2560, esp8266-01, gps and bluetooth modules. I need to use 3 serial ports but when i try use them i'm taking " Serial2 was not declared in this scope" error.

I try to fix it but I couldn't. Can you help me?

```cpp

#include <ESP8266WiFi.h>

void setup() {

  Serial.begin(115200);
  Serial1.begin(115200);
  Serial2.begin(9600);
}

void loop() {

}

```

### Debug Messages

```
...
sketch_apr04a:7: error: 'Serial2' was not declared in this scope

   Serial2.begin(9600);

   ^

exit status 1
'Serial2' was not declared in this scope
```

**Comment by Pablo2048** [comment] 2018-04-04 15:33
Not a bug IMO - ESP8266 has only 2 hw serial ports (and the second one is TX only).

**Comment by iemektar** [comment] 2018-04-04 15:45
I dont know and want to learn. Which esp module i must use?

**Comment by d-a-v** [comment] 2018-04-04 15:52
Like @Pablo2048 tells, there are only 1½ Hardware serial ports on every tastes of esp8266.
Use the SoftwareSerial library to have more.

**Comment by devyte** [comment] 2018-04-04 18:48
@iemektar if you don't know, and need guidance, this is not the right place to ask for it. This is an issue tracker, meant to track issues in the core code. Please read the issue POLICY doc, as mentioned in the issue template that you saw when opening this issue.
Closing due to user error and off-topic.

**Closed by devyte** 2018-04-04 18:48 UTC
