### ISSUE TITLE
SoftAP authentication error from Android after reset

### ISSUE THREAD

**Issue by Menion2k** [esp8266/Arduino#5597] opened 2019-01-07 13:40 UTC
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:				ESP-12E
- Core Version:			2.4.2
- Development Env:		Arduino IDE 1.8.7
- Operating System:		Windows

### Settings in IDE

- Module:  			ESP-12E
- Flash Mode:			qio
- Flash Size: 		        4MB
- lwip Variant:                  v1.4|v2 Lower Memory
- Reset Method:		nodemcu
- Flash Frequency:	        40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:              921600

### Problem Description

Hello
I have a problem in making a reliable softAP operation. It is the same issue in #1755
I run a 4Mbyte ESP8266 device, and I start a softAP together with STA connection
The fact that I have also the STA connection running (connected or not to an Access Point), seems to have nothing to do with the issue
The issue is an authentication error I often receive from my android phone attempting to connect to the ESP8266 softAP
In order to check what is happening, I have set up the connected and disconnected softAP event callbacks, and I see that I first receive a "connected" event then after a second or so, I receive a disconnected event, and the android phone report "authentication error".
If on the android phone I remove the ESP8266 wireless network and I rejoin it, reinserting the password (that never change), then I almost always I succeed to connect until the next reset
Set persistent to false does not help either
It seems that something happen across a reset of the ESP8266 module together with authentication machanism
I use a Samsung Galaxy S8+

**Comment by devyte** [comment] 2019-11-10 00:32
No MCVE showing the wifi setup. 
I can't reproduce this with any of my ESP12 based boards (Wemos D1 mini r2, nodemcu, WittyCloud), nor with my Wemos D1 Pro boards. They all serve a SoftAP to which I can connect with my android phone without issues. I can even switch modes and reconnect, no problems.
Closing.

**Closed by devyte** 2019-11-10 00:32 UTC
