### ISSUE TITLE
SNTP Server

### ISSUE THREAD

**Issue by Meinsda** [esp8266/Arduino#5642] opened 2019-01-19 21:12 UTC
I have a problem with tasmota and the ntp function. My Hardware is a Sonoff RF Gateway. The problem is the ntp function don't work. I don't get the actual time and date. So i take a look at the source Code and see they only use the function from esp8266 to get time and date. 
The ntp i used is outside my Network. On my router i see there will be packages send to the udp port 123 but to the router and not to the Server outside my Network (i get the udp package in my "in Queue" and not in the "Forward Queue").

**Comment by devyte** [comment] 2019-01-22 04:48
@Meinsda You ignored the issue template. You didn't provide an MCVE or any code example or reference whatsoever. The explanation is not for our core in isolation, but in relation to a 3rd party lib (Tasmota) which we don't develop.
I suggest asking at the Tasmota repo first. If an issue in our core here is found, then please open a new issue, provide the details requested in the issue template, including an MCVE sketch that doesn't rely on a 3rd party lib, and explain in detail how to reproduce the problem.

As a side note, I am able to sync NTP time from a remote server outside of my private network without issues.

Closing due to lack of info.

**Closed by devyte** 2019-01-22 04:48 UTC
