### ISSUE TITLE
hellomesh.ino issues

### ISSUE THREAD

**Issue by kaihangchen** [esp8266/Arduino#5872] opened 2019-03-13 03:08 UTC
### Basic Infos

- [ x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x ] I have tested that the issue is present in current master branch (aka latest git).
- [ x] I have searched the issue tracker for a similar issue.
- [ x] If there is a stack dump, I have decoded it.
- [x ] I have filled out all fields below.

#### Platform

- Hardware:					[nodemcu v1 （ESP-12E）]
- Core Version:			[2.5.0]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Nodemcu]
- Flash Mode:			[other]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

When I upload the program to three nodemcu, the serial monitor prints out "Setting up mesh node...", "No mesh AP found." or "Time out Connection failed to mesh AP". I don't know why. I haven't changed anything except the value of exampleWiFiPassword [] .

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMesh.h>
#include <TypeConversionFunctions.h>
#include <assert.h>

/**
   NOTE: Although we could define the strings below as normal String variables,
   here we are using PROGMEM combined with the FPSTR() macro (and also just the F() macro further down in the file).
   The reason is that this approach will place the strings in flash memory which will help save RAM during program execution.
   Reading strings from flash will be slower than reading them from RAM,
   but this will be a negligible difference when printing them to Serial.

   More on F(), FPSTR() and PROGMEM:
   https://github.com/esp8266/Arduino/issues/1143
   https://arduino-esp8266.readthedocs.io/en/latest/PROGMEM.html
*/
const char exampleMeshName[] PROGMEM = "MeshNode_";
const char exampleWiFiPassword[] PROGMEM = "12345678";

unsigned int requestNumber = 0;
unsigned int responseNumber = 0;

String manageRequest(const String &request, ESP8266WiFiMesh &meshInstance);
transmission_status_t manageResponse(const String &response, ESP8266WiFiMesh &meshInstance);
void networkFilter(int numberOfNetworks, ESP8266WiFiMesh &meshInstance);

/* Create the mesh node object */
ESP8266WiFiMesh meshNode = ESP8266WiFiMesh(manageRequest, manageResponse, networkFilter, FPSTR(exampleWiFiPassword), FPSTR(exampleMeshName), "", true);

/**
   Callback for when other nodes send you a request

   @param request The request string received from another node in the mesh
   @param meshInstance The ESP8266WiFiMesh instance that called the function.
   @returns The string to send back to the other node
*/
String manageRequest(const String &request, ESP8266WiFiMesh &meshInstance) {
  // We do not store strings in flash (via F()) in this function.
  // The reason is that the other node will be waiting for our response,
  // so keeping the strings in RAM will give a (small) improvement in response time.
  // Of course, it is advised to adjust this approach based on RAM requirements.

  /* Print out received message */
  Serial.print("Request received: ");
  Serial.println(request);

  /* return a string to send back */
  return ("Hello world response #" + String(responseNumber++) + " from " + meshInstance.getMeshName() + meshInstance.getNodeID() + ".");
}

/**
   Callback for when you get a response from other nodes

   @param response The response string received from another node in the mesh
   @param meshInstance The ESP8266WiFiMesh instance that called the function.
   @returns The status code resulting from the response, as an int
*/
transmission_status_t manageResponse(const String &response, ESP8266WiFiMesh &meshInstance) {
  transmission_status_t statusCode = TS_TRANSMISSION_COMPLETE;

  /* Print out received message */
  Serial.print(F("Request sent: "));
  Serial.println(meshInstance.getMessage());
  Serial.print(F("Response received: "));
  Serial.println(response);

  // Our last request got a response, so time to create a new request.
  meshInstance.setMessage(String(F("Hello world request #")) + String(++requestNumber) + String(F(" from "))
                          + meshInstance.getMeshName() + meshInstance.getNodeID() + String(F(".")));

  // (void)meshInstance; // This is useful to remove a "unused parameter" compiler warning. Does nothing else.
  return statusCode;
}

/**
   Callback used to decide which networks to connect to once a WiFi scan has been completed.

   @param numberOfNetworks The number of networks found in the WiFi scan.
   @param meshInstance The ESP8266WiFiMesh instance that called the function.
*/
void networkFilter(int numberOfNetworks, ESP8266WiFiMesh &meshInstance) {
  for (int networkIndex = 0; networkIndex < numberOfNetworks; ++networkIndex) {
    String currentSSID = WiFi.SSID(networkIndex);
    int meshNameIndex = currentSSID.indexOf(meshInstance.getMeshName());

    /* Connect to any _suitable_ APs which contain meshInstance.getMeshName() */
    if (meshNameIndex >= 0) {
      uint64_t targetNodeID = stringToUint64(currentSSID.substring(meshNameIndex + meshInstance.getMeshName().length()));

      if (targetNodeID < stringToUint64(meshInstance.getNodeID())) {
        ESP8266WiFiMesh::connectionQueue.push_back(NetworkInfo(networkIndex));
      }
    }
  }
}

void setup() {
  // Prevents the flash memory from being worn out, see: https://github.com/esp8266/Arduino/issues/1054 .
  // This will however delay node WiFi start-up by about 700 ms. The delay is 900 ms if we otherwise would have stored the WiFi network we want to connect to.
  WiFi.persistent(false);

  Serial.begin(115200);
  delay(50); // Wait for Serial.

  //yield(); // Use this if you don't want to wait for Serial.

  // The WiFi.disconnect() ensures that the WiFi is working correctly. If this is not done before receiving WiFi connections,
  // those WiFi connections will take a long time to make or sometimes will not work at all.
  WiFi.disconnect();

  Serial.println();
  Serial.println();

  Serial.println(F("Note that this library can use static IP:s for the nodes to speed up connection times.\n"
                   "Use the setStaticIP method as shown in this example to enable this.\n"
                   "Ensure that nodes connecting to the same AP have distinct static IP:s.\n"
                   "Also, remember to change the default mesh network password!\n\n"));
  // Serial.println(Esp.getFullVersion);
  Serial.println(F("Setting up mesh node..."));

  /* Initialise the mesh node */
  meshNode.begin();
  meshNode.activateAP(); // Each AP requires a separate server port.
  // meshNode.setStaticIP(IPAddress(192, 168, 4, 21)); // Activate static IP mode to speed up connection times.
}

int32_t timeOfLastScan = -10000;
void loop() {
  if (millis() - timeOfLastScan > 3000 // Give other nodes some time to connect between data transfers.
      || (WiFi.status() != WL_CONNECTED && millis() - timeOfLastScan > 2000)) { // Scan for networks with two second intervals when not already connected.
    String request = String(F("Hello world request #")) + String(requestNumber) + String(F(" from ")) + meshNode.getMeshName() + meshNode.getNodeID() + String(F("."));
    meshNode.attemptTransmission(request, false);
    timeOfLastScan = millis();

    // One way to check how attemptTransmission worked out
    if (ESP8266WiFiMesh::latestTransmissionSuccessful()) {
      Serial.println(F("Transmission successful."));
    }

    // Another way to check how attemptTransmission worked out
    if (ESP8266WiFiMesh::latestTransmissionOutcomes.empty()) {
      Serial.println(F("No mesh AP found."));
    } else {
      for (TransmissionResult &transmissionResult : ESP8266WiFiMesh::latestTransmissionOutcomes) {
        if (transmissionResult.transmissionStatus == TS_TRANSMISSION_FAILED) {
          Serial.println(String(F("Transmission failed to mesh AP ")) + transmissionResult.SSID);
        } else if (transmissionResult.transmissionStatus == TS_CONNECTION_FAILED) {
          Serial.println(String(F("Connection failed to mesh AP ")) + transmissionResult.SSID);
        } else if (transmissionResult.transmissionStatus == TS_TRANSMISSION_COMPLETE) {
          // No need to do anything, transmission was successful.
        } else {
          Serial.println(String(F("Invalid transmission status for ")) + transmissionResult.SSID + String(F("!")));
          assert(F("Invalid transmission status returned from responseHandler!") && false);
        }
      }
    }
    Serial.println();
  } else {
    /* Accept any incoming connections */
    meshNode.acceptRequest();
  }
}

```

### Debug Messages

```
Debug messages go here
```

**Comment by devyte** [comment] 2019-03-13 20:04
@aerlon you [said](https://github.com/esp8266/Arduino/issues/5867#issuecomment-472084189) that you checked with latest master branch. What about release 2.5.0?

**Comment by kaihangchen** [comment] 2019-03-14 04:18
I Installed it 2.5.0 with Boards Manager. But when I check the version, the link of online help is 2.5.0-beta3. I think it might be the development board URL (http://arduino.esp8266.com/versions The content of /2.5.0/package_esp8266com_index.json) is not updated. what should I do

**Comment by aerlon** [comment] 2019-03-14 19:17
@kaihangchen Just to make sure, you did upload the same code with the modified password to all nodes AFTER you changed the password, right? Otherwise the nodes will be using different passwords and that gives exactly the symptoms you are describing. Also it seems as though the WiFi password has to be at least 8 characters long, otherwise the AP will not be found during scan (I'll add a comment about this in the next version of the example).

If uploading with the password "12345678" for every node does not fix your problem, I'll make a clean Arduino IDE install tomorrow and try the 2.5.0 version out.

**Comment by kaihangchen** [comment] 2019-03-15 05:20
I am truely install the library 2.5.0 with the Boards Manager. And upload the code to  device .And I am Set the different IP address for two nodes at 192.168.4.xx.But it still not working .
![image](https://user-images.githubusercontent.com/32416615/54409320-26aee600-4721-11e9-8de0-9a4d1761f2ac.png)
![image](https://user-images.githubusercontent.com/32416615/54409652-ee100c00-4722-11e9-9e4d-687be3777e10.png)
One serial monitor 
![image](https://user-images.githubusercontent.com/32416615/54409791-8c03d680-4723-11e9-90d3-080215de1715.png)
another serial monitor
![image](https://user-images.githubusercontent.com/32416615/54409887-03396a80-4724-11e9-8eb6-9c472c6e9991.png)

**Comment by aerlon** [comment] 2019-03-15 19:55
Now I've tried the following on Windows 10.

1. I downloaded the latest Aruino IDE (version 1.8.9).
2. I installed Arduino Core for ESP8266 version 2.5.0 with Boards Manager.
3. I copy pasted the MCVE Sketch you provided above into the editor window, replacing all other code there.
4. I uploaded the MCVE Sketch to two different ESP8266 without changing anything in the sketch between the uploads.

This is the result for the node that connects to the AP of the other: 

![HelloMesh demo](https://user-images.githubusercontent.com/39123666/54457854-ce98d380-4762-11e9-8f30-995dae7c6349.png)

So it works for me.

Try to follow the four steps above exactly. If that still does not work for you, it may be a hardware problem. In that case you may want to try with other ESP8266 modules. Also, you may want to ensure that there are two MeshNode WiFi networks with different names available (although that does not seem to be a likely problem for you, since an AP was acquired). That can be done by simple checking the WiFi network list in a laptop or smartphone with WiFi enabled when the ESP8266 modules are connected.

**Comment by devyte** [comment] 2019-03-15 21:20
Closing for now as can't reproduce. If additional info is provided that allows reproducing it can be reopened.

**Closed by devyte** 2019-03-15 21:20 UTC
Labels: waiting for feedback
