### ISSUE TITLE
Infrared Library

### ISSUE THREAD

**Issue by gamecompiler** [esp8266/Arduino#32] opened 2015-04-01 22:12 UTC
Hi,

does somebody know a infrared library which works with this esp8266 Arduino IDE ?
Id not found one, because they all dependt on avr interupts.

Arduino: 1.6.1 (Windows 8.1), Platine: "Generic ESP8266 board"

C:\Users\####\Documents\Arduino\libraries\Arduino-IRremote\IRremote.cpp:25:27: fatal error: avr/interrupt.h: No such file or directory

 #include < avr/interrupt.h >

compilation terminated.

Sorry for my English.
Thanks in advance.

**Comment by probonopd** [comment] 2015-04-04 17:11
See https://github.com/esp8266/Arduino/issues/6

**Comment by igrr** [comment] 2015-05-12 22:59
Closing as duplicate of #6.

**Closed by igrr** 2015-05-12 22:59 UTC
