### ISSUE TITLE
SoftwareSerial missing

### ISSUE THREAD

**Issue by s0170071** [esp8266/Arduino#3880] opened 2017-11-25 20:01 UTC
It was part of  2.4.0rc2, now it is gone.

**Comment by Pablo2048** [comment] 2017-11-25 20:09
Its not gone - its just not part of the gihub version (its third party library actually...)

**Comment by devyte** [comment] 2017-11-25 20:09
Closing as duplicate of #3596 .

**Closed** 2017-11-25 20:09 UTC
