### ISSUE TITLE
Captive Portal SSID behaviour on apple devices

### ISSUE THREAD

**Issue by kapyaar** [esp8266/Arduino#1061] opened 2015-11-20 09:10 UTC
In captive portal

```
    String ssidString = "Setup-" + String(system_get_chip_id());
    const char *ssid = ssidString.c_str();
    WiFi.softAP(ssid);
```

Does not popup the captiveportal window on apple devices. 
`WiFi.softAP("Setup-12345');`

Works without any issues. Has anyone else observed this behaviour?
##

**Comment by me-no-dev** [comment] 2015-11-20 12:14
try 
```cpp
String ssidString = "Setup-" + String(system_get_chip_id());
WiFi.softAP((const char *)ssidString.c_str());
```

**Comment by avarachanvc** [comment] 2015-11-20 16:18
Thanks for the suggestion. Tried it, it works on iphone now, but not on macbook. Windows has no issues with any method though.

**Comment by devyte** [comment] 2017-10-19 18:58
I can't reproduce this in latest git. Closing.

**Closed by devyte** 2017-10-19 18:58 UTC
Labels: type: question
