### ISSUE TITLE
WiFiClientBasic example slow to connect

### ISSUE THREAD

**Issue by Craig1516** [esp8266/Arduino#2684] opened 2016-11-12 07:29 UTC
### Basic Infos  Using NodeMCU Dev board in the Arduino IDE 
                           Attempting to run WiFiClientBasic example

#### Hardware
Hardware:	ESP-12E

### Description

Successfully loaded the example program and am obtaining simple data from a GET request.  My problem is that the first time through Loop takes either 7.9 or 3.9 seconds (and nothing in between).  The second time through loop takes less than 200 ms.  I'm hoping that the first time though can be as fast as the second time though.  The design attempt is to report a bus schedule at the push of a button, then go to deep sleep.   On recovery (RST) 7.9 seconds is a bit long to wait.  Anybody know how I can speed up the performance the first time around.

[WiFiClientBasic.txt](https://github.com/esp8266/Arduino/files/587119/WiFiClientBasic.txt)

**Comment by devyte** [comment] 2017-10-10 05:01
@Craig1516 no basic info, no IDE settings.
I'm not aware of such a long startup time in latest git, which makes me suspect something related to DNS, but that's a WAG. 
If the issue is still valid, please test and report back here.

**Comment by Craig1516** [comment] 2017-10-10 05:38
Hi Develo,

 

Not sure what this relates to.  I’m a fan of esp8266’s but I’m not Craig1516.  I saw your online comment and received this email.  Hopefully Craig1516 is dialed in to the blog.  Hope you can reach him/her.  

 

Hope it helps,

Craig

**Comment by devyte** [comment] 2017-10-10 06:42
@Craig1516 weirdest thing to happen to me here in a long time. Maybe an email change or something. Sorry for the trouble!
Closing.

**Closed by devyte** 2017-10-10 06:42 UTC
Labels: waiting for feedback
