### ISSUE TITLE
ESP8266 keeps crashing after OTA update

### ISSUE THREAD

**Issue by Madhavagg** [esp8266/Arduino#3649] opened 2017-09-26 07:06 UTC
Hello,

I am using ESP8266 in production. After I receive it from assembly line and if I try to perform an OTA update then it keeps resetting/crashing after it. But at the same time if I again burn the rboot manually, OTA works fine. Can this be an issue where rboot doesn't get flashed properly? But if so, then should ESP run the application code normally? 

Please let me know!

**Comment by devyte** [comment] 2017-09-26 13:13
@Madhavagg no basic info, no IDE settings, no explanation of the procedure used for flashing, no xpla ation about which OTA procedure is used. The issue template was completely ignored.
This firmware doesn't use rboot (at least not yet), it uses eboot.
Your question provides the most likely answer: there is probably something wrong with your production flashing.
I suggest discussing at a forum like esp8266.com or stackoverflow to figure out what the problem is. If you find an issue with the core, feel free to open an issue, but please make use of the template.
Closing due to lack of info.

**Closed by devyte** 2017-09-26 13:13 UTC
