### ISSUE TITLE
WIFI problem with version 2.3.0

### ISSUE THREAD

**Issue by dibyamani** [esp8266/Arduino#3575] opened 2017-09-05 18:30 UTC
I confirmed that there is problem with WIFI connection with the esp8266 2.3.0 however there no any issues with same code in version 2.2.0. 
Wifi is not connected if NodeMCU is restarted by pulling and plugging USB cable.

Although, I tried with WiFiManager  library and it is working fine in both version but ESP8266WiFi library doesn't work well with 2.3.0.
Following is my code for setting up wifi:
void setup_wifi() { 
  IPAddress ip(192, 168, 0, 202); 
  IPAddress gateway(192, 168, 0, 1);
  IPAddress subnet(255, 255, 255, 0);  
  WiFi.config(ip, gateway, subnet);  
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);
    WiFi.begin(ssid, password);
    delay(1000);
  } 
Serial.println("Connected to wifi successfully.");
}

Please let me know if it is fixed in version 2.3.0.

**Comment by devyte** [comment] 2017-09-05 22:57
I just confirmed that there is no issue either in 2.3.0 or latest git. Tested on Wemos D1 mini, Nodemcu v3 lolin, and wittycloud, and WiFi works as intended.
Therefore, I suspect user error of some kind.

Your description is incomplete at best. When you open an issue, you are presented with a template with specific fields to fill out. Your description doesn't even include a full minimal sketch, or basic info about which board you are using. 
Please look at the WiFi examples and try them out, and ask at esp8266.com or stackoverflow for usage assistance. If you still think there is an issue in the core libs, open a new issue, and please make correct use of the template, as well as text markup.
Closing due to lack of info.

**Closed by devyte** 2017-09-05 22:57 UTC
