### ISSUE TITLE
constantly disconnected /reconnect in station mode,

### ISSUE THREAD

**Issue by mkeyno** [esp8266/Arduino#2827] opened 2017-01-03 22:28 UTC
#### Hardware
Hardware:			?ESP-12F
Core Version:      	?2.3.0-rc2?
webserver type  async server & async websocket 
### Description

My module constantly disconnected /reconnect in station mode, I turn on debug output and it shows following output , but I cant decipher it what is actually happened 
any help really appreciated 
`
bcn_timout,ap_probe_send_start
ap_probe_send over, rest wifi status to disassoc
state: 5 -> 0 (1)
rm 0
pm close 7
WS [2] Disconnected!
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 
state: 5 -> 2 (fc0)
rm 0
reconnect
state: 2 -> 0 (0)
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 

connected with keyno, channel 1
dhcp client start...
ip:192.168.1.150,mask:255.255.255.0,gw:192.168.1.1
pm open,type:2 0
`
### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

**Comment by wfraga18** [comment] 2017-02-28 01:56
me too

**Comment by devyte** [comment] 2017-10-04 22:56
@mkeyno No sketch, no basic info, no IDE settings.
I see a message about scandone in between the other messages. If you scan, the radio will jump channels and can disconnect (the ESP has a single radio).
I haven't seen a single disconnect issue with latest git in any of all the boards I have running 24/7, and I'm also using the async webserver.
Closing due to lack of info, and can't reproduce. If the issue still exists, please open a new issue, and provide the details requested in the issue template.

**Closed by devyte** 2017-10-04 22:56 UTC
