### ISSUE TITLE
OTA times out unless the wifi AP is immediatly next to the esp8266

### ISSUE THREAD

**Issue by paai** [esp8266/Arduino#6012] opened 2019-04-24 07:37 UTC
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ x] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:			        Robotdyn wifi D1R2 esp8266,  WEMOS mini

- Core Version:			all versions 2.5.0, including 2.5.0-beta3,  SDK version 2.2.1(cfd48f3)
- Development Env:		Arduino IDE 1.8.5, 1.8.9
- Operating System:		Ubuntu

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Mode:			[qio|dio|other]
- Flash Size: 		        4MB
- lwip Variant:                   v2 Lower Memory
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		80Mhz
- Upload Using:		OTA
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

OTA times out immediatly or halfway transfer.

I use the BasicOTA.ino from the example list.

Wifi works fine if used for normal communication like connecting to an AP or function as website etc. The new OTA is visible in the Arduino IDE in the list with ports. However, uploads fail unless the esp8266 is about on top of the AP (two or three meters) and even then times out half of the time.

I took care to use only the git updates, not those of the IDE. There are just four or five WIFI routers visible, including three of myself. The logfile of the Fritzbox that I use for the experiment shows that the esp8266 registers:
24.04.19 09:06:38 WLAN station registered. Name: -, IP address: -, MAC address: 84:F3:EB:5E:08:7D, throughput: 54 MBit/s.

I posted this eight days ago as 'OTA stopped working completely with 2.5.0' but then bogged down in learning how to do git updates. I hope that this new information helps to track down the problem.

(edit) Today I tried the Webupdater example and found that it also loaded very slow. But apparently there is no timeout in that routine, so after five minutes or so the upload succeeded. Still, the Fritzbox router that the esp8266 attached to scores -45 db, so the physical connection should not be a problem.

And very important, when I go back to version 2.4.0 I have no problems!

```

### Debug Messages

```
Debug messages go here
```

**Comment by earlephilhower** [comment] 2021-01-13 20:52
Closing due to age and un-reproducibility.

**Closed by earlephilhower** 2021-01-13 20:52 UTC
