### ISSUE TITLE
Android + softap

### ISSUE THREAD

**Issue by sxserjio** [esp8266/Arduino#1755] opened 2016-03-11 22:40 UTC
I recently purchased the ESP-12E module and installed the Arduino IDE 1.6.6. I ran into a problem! The standard example "WiFiAccessPoint" does not work in conjunction softap + Android. Android phone and tablet display the authorization error, while iOs devices work perfectly! The solution posted here [https://github.com/esp8266/Arduino/issues/515](https://github.com/esp8266/Arduino/issues/515) not helping me.
##

**Comment by igrr** [comment] 2016-03-12 20:07
Are you able to connect to an AP set up with AT firmware on the same module?

**Comment by sxserjio** [comment] 2016-03-14 11:42
No! I used the firmware AT21SDK95-2015-01-24 and AT22SDK100-2015-03-20-boot1.3b.bin. None of them, I could not connect to the esp8266 module. But I found the Samsung Galaxy S3. It connects to the access point you created as the firmware and the Arduino IDE without problems.

**Comment by sxserjio** [comment] 2016-03-14 11:48
Sketch TestEspApi when attempting to connect displays the message "EVENT_MAX".

**Comment by igrr** [comment] 2016-03-14 11:55
@sxserjio if your issue persists with AT firmware, then it is out of scope of this project. We can not go troubleshooting the bugs in the SDK. Your best bet is to report this issue to Espressif.

**Comment by devyte** [comment] 2017-10-18 04:57
I can connect with any device, including Android/iOS/laptop+Windows/laptop+Linux, to an ESP12's SoftAP.
Can't reproduce => closing.

**Closed by devyte** 2017-10-18 04:57 UTC
Labels: type: troubleshooting
