### ISSUE TITLE
fatal error: Arduino.h: No such file or directory

### ISSUE THREAD

**Issue by takiuddinahmed** [esp8266/Arduino#3909] opened 2017-12-04 19:48 UTC
Hello, i am facing a problem. when I compile any esp8266 code by selecting 'Generic ESP8266' board manager from my arduino ide the error which are happening are as follows:

> C:\Users\ASUS\AppData\Local\Temp\arduino_build_855432\sketch\esp1st.ino.cpp:1:21: fatal error: Arduino.h: No such file or directory
>
>
>
 > #include <Arduino.h>
  >                   ^
>
> compilation terminated.
>
> exit status 1
> Error compiling for board Generic ESP8266 Module.

**Comment by devyte** [comment] 2017-12-05 01:44
@takiuddinahmed I suggest a clean install, both of the IDE and the core. Please read the instructions carefully. If you still need help, please seek assistance at a community forum first to figure out what you are doing wrong.
Closing as can't reproduce.

**Closed by devyte** 2017-12-05 01:44 UTC

**Comment by takiuddinahmed** [comment] 2017-12-06 16:39
It works. Thanks

**Comment by mikelau1** [comment] 2018-02-11 23:53
hi can you please let know how did you resolve it? thanks!
