### ISSUE TITLE
Time Hour Format symbols

### ISSUE THREAD

**Issue by victor7376** [esp8266/Arduino#8496] opened 2022-02-25 17:13 UTC
While trying to code a clock from:

https://github.com/Qrome/marquee-scroller

Which uses the Time library from:

https://github.com/PaulStoffregen/Time

The clock pulls the correct time and displays it in 24 hour format, but as soon as you try to use the 12 hour format, it displays symbols for the hour.

I've been able to track down part of the issue between the Time library (link above) which uses the command 'hourFormat12'.  If using the ESP8266 core library version 2.5.2 the clock works fine, but as soon as I try to use the latest version it shows the symbols instead of hours.

Any advice please?  As I would prefer to use the latest version if possible.

**Comment by mcspr** [comment] 2022-02-25 19:50
Can you try changing `hourFormat12()` to `String(hourFormat12())`?
https://github.com/Qrome/marquee-scroller/blob/6135f7596c01ac85a774937c59e088b0af5c55b5/marquee/marquee.ino#L473

At a glance, the `int` happens to be overloaded as `char`, causing a type-cast for whatever the timestamp is to some unprintable character. Looks like a duplicate of https://github.com/esp8266/Arduino/issues/8430, another surprise b/c String is converting everything into everything...

And have you asked the author? :)

**Closed by mcspr** 2022-02-25 19:50 UTC
