### ISSUE TITLE
Need help understanding SPIFFS on 4M ESP-12E/F

### ISSUE THREAD

**Issue by pimvanpelt** [esp8266/Arduino#2529] opened 2016-09-16 21:01 UTC
#### Hardware

Hardware:           ESP-12 / NodeMCU 1.0 clone from Banggood
Core Version:       2.3.0

Esptool flash_id and chip_id:
- Chip ID: 0x002454cf
- Flash:
  -   Manufacturer: e0
  -   Device: 4016
### Description

I am ultimately trying to get 4M flash to contain a 3M SPIFFS and 1M code. I cannot open SPIFFS or format it, although I can upload it with the ESP8266 Sketch Data Uploader in Arduino 1.6.10 with ESP8266 2.3.0 and sketches with esptool.py. I'm trying to understand how this works, as it is unclear to me how to use SPIFFS on the ESP12E, unless I spec 512K/64K as flash size.
#### Sketch Output (see below)

```
Flash real id:   001640E0
Flash real size: 4194304

Flash ide  size: 524288
Flash ide speed: 40000000
Flash ide mode:  QIO
Flash Chip configuration wrong!
```

Curiously, the 'ide size/speed/mode' is read from the first 4 bytes of the flash: `E9 01 02 40` and according to ESP.cpp line 212 that `40` means `EspClass::magicFlashChipSize` should return `4_MB`. The third byte `02` is an `FlashMode_t` and it means `FM_DIO` in ESP.h line 80.

But obviously, I'm missing something as the sketch output shows `Flash ide` being 512K, not 4M; and `Flash ide mode` being **QIO**, not **DIO**.

If I change the Arduino Flash settings to, say, 2M/1M the first four bytes are `E9 01 02 30` (and 0x3 is a `2_MB` flash size), so I think the linker and compiler and things work well. For what it's worth, my linker and esptool commands are as follows:

```
"/home/pim/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-gcc" -g -w -Os -nostdlib -Wl,--no-check-sections -u call_user_start -Wl,-static "-L/home/pim/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lib" "-L/home/pim/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/ld" "-Teagle.flash.2m.ld" -Wl,--gc-sections -Wl,-wrap,system_restart_local -Wl,-wrap,register_chipv6_phy  -o "/tmp/buildb9c8b728d9a115017ceaf88393906ba2.tmp/FlashInfo.ino.ino.elf" -Wl,--start-group "/tmp/buildb9c8b728d9a115017ceaf88393906ba2.tmp/sketch/FlashInfo.ino.ino.cpp.o" "/tmp/buildb9c8b728d9a115017ceaf88393906ba2.tmp/arduino.ar" -lm -lgcc -lhal -lphy -lpp -lnet80211 -lwpa -lcrypto -lmain -lwps -laxtls -lsmartconfig -lmesh -lwpa2 -llwip_gcc -lstdc++ -Wl,--end-group  "-L/tmp/buildb9c8b728d9a115017ceaf88393906ba2.tmp"
"/home/pim/.arduino15/packages/esp8266/tools/esptool/0.4.9/esptool" -eo "/home/pim/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/bootloaders/eboot/eboot.elf" -bo "/tmp/buildb9c8b728d9a115017ceaf88393906ba2.tmp/FlashInfo.ino.ino.bin" -bm dio -bf 40 -bz 2M -bs .text -bp 4096 -ec -eo "/tmp/buildb9c8b728d9a115017ceaf88393906ba2.tmp/FlashInfo.ino.ino.elf" -bs .irom0.text -bs .text -bs .data -bs .rodata -bc -ec
/home/pim/.local/bin/esptool.py --port /dev/ttyUSB0 --baud 115200 write_flash 0x00000 /tmp/buildb9c8b728d9a115017ceaf88393906ba2.tmp/FlashInfo.ino.ino.bin 
```
### Settings in IDE

Module:             Generic ESP8266 Module
Flash Size:         4MB/1MB
CPU Frequency:  80Mhz
Flash Mode:     DIO
Flash Frequency:    40Mhz
Upload Using:       SERIAL
Reset Method:       ck
### Sketch

.../libraries/esp8266/examples/CheckFlashConfig/CheckFlashConfig.ino
from 2.3.0 release.

**Comment by devyte** [comment] 2017-10-12 06:56
@pimvanpelt it's possible to select 4M/3M spiffs from the Arduino IDE. This works correctly, I am using it myself.
Closing as can't reproduce.

**Closed by devyte** 2017-10-12 06:56 UTC
