### ISSUE TITLE
NodeMCU v1.0 throwing exception 3 upon WiFi.begin..

### ISSUE THREAD

**Issue by suntribe** [esp8266/Arduino#2157] opened 2016-06-15 21:59 UTC
#### Hardware
Hardware:			NodeMCU ESP-12(e)?

### Description
I'm trying to upload a sketch to nodemcu (it says Lolin on it, so I assume it with the esp12e chip on it), and if I try to use any of the WiFi related methods, I get an exception 3...

### Settings in IDE

Module:  			NodeMCU v1.0
CPU Frequency:		80Mhz
Flash Size:			4M (3M SPIFSS)
Upload Using:		USB SERIAL

### Sketch
#include <ESP8266WiFi.h>

const char* ssid     = "your-ssid";
const char* password = "your-password";

void setup() {
  Serial.begin(115200);
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");  
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void loop() {
}

### Stack trace

 1264, room 16 
tail 0
chksum Connecting to your-ssid

Exception (3):
epc1=0x401003e9 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40027c39 depc=0x00000000

ctx: cont 
sp: 3ffef6a0 end: 3ffefa80 offset: 01a0

>>>stack>>>
3ffef840:  feefeffe feefeffe feefeffe feefeffe  
3ffef850:  feefeffe feefeffe feefeffe 3ffef9b7  
3ffef860:  00000484 00000484 000003fe 401004f4  
3ffef870:  00000000 00001000 000003fe 40106dd4  
3ffef880:  40004b31 3ffef8b0 0000001c 40219dc1  
3ffef890:  401054a2 40219ea9 3fff0044 000003ff  
3ffef8a0:  000003fd 3ffef9b7 3fff0044 000003fd  
3ffef8b0:  ffffff01 55aa55aa 0000000d 0000001c  
3ffef8c0:  0000001c 00000047 00000045 000003ff  
3ffef8d0:  4021a298 3fff0044 3fff0044 000000ff  
3ffef8e0:  00000001 3ffef9d7 4021a3f3 00000008  
3ffef8f0:  3fff0044 000000ff 3ffef9b7 00000000  
3ffef900:  3fff0104 3ffefa18 00000001 4021a480  
3ffef910:  3ffef9b7 3fff0044 00000000 00000004  
3ffef920:  3ffef9d7 3fff637c 3fff0044 00000000  
3ffef930:  4021a4bc 3ffe83f3 3ffe8401 feefeffe  
3ffef940:  40201f3e 3ffe8401 3ffe83f3 40201e5f  
3ffef950:  3fff0500 00000018 3ffefab0 402033a7  
3ffef960:  3ffefa70 3ffecf40 3ffefab0 402033d9  
3ffef970:  3ffefa00 3ffefacc 3ffefab0 40203455  
3ffef980:  3ffeeae4 000000fd 000000fd 4010020c  
3ffef990:  4021ac4a 3ffeeb04 3ffeea04 3fffdad0  
3ffef9a0:  4021ba73 3ffefab0 402035e4 3ffeeb40  
3ffef9b0:  ffffff00 79ffffff 2d72756f 64697373  
3ffef9c0:  feefef00 feefeffe feefeffe 0001c200  
3ffef9d0:  0000001c 79000000 2d72756f 73736170  
3ffef9e0:  64726f77 00000000 3ffe856d 40202764  
3ffef9f0:  00000000 00000008 3ffe8409 3ffeea54  
3ffefa00:  3ffe836c 00000009 3ffeea28 40202359  
3ffefa10:  3ffe856c 00000000 3ffeea28 40202359  
3ffefa20:  3ffee938 00000000 00000001 40202384  
3ffefa30:  feefeffe feefeffe 3ffeea28 3ffeea54  
3ffefa40:  3ffe836c 3ffee938 3ffeea28 40201c25  
3ffefa50:  feefeffe feefeffe feefeffe feefeffe  
3ffefa60:  3fffdad0 00000000 3ffeea4c 402025f8  
3ffefa70:  feefeffe feefeffe 3ffeea60 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

### Decoded stack

0x401003e9: _umm_malloc at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/umm_malloc/umm_malloc.c line 1380
0x401004f4: calloc at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/umm_malloc/umm_malloc.c line 1682
0x40106dd4: pvPortZalloc at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/heap.c line 33
0x4021aa55: wifi_param_save_protect_with_check at ?? line ?
0x401054a2: spi_flash_read at ?? line ?
0x4021ab3d: system_param_save_with_protect at ?? line ?
0x4021af2c: wifi_station_ap_number_set at ?? line ?
0x4021b087: wifi_station_ap_number_set at ?? line ?
0x4021b114: wifi_station_ap_number_set at ?? line ?
0x4021b150: wifi_station_set_config at ?? line ?
0x4020223a: ESP8266WiFiSTAClass::begin(char const*, char const*, int, unsigned char const*, bool) at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp line 143
0x4020215b: ESP8266WiFiSTAClass::begin(char const*, char const*, int, unsigned char const*, bool) at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp line 101
0x402033a7: IPAddress::fromString(char const*) at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/IPAddress.cpp line 87
0x402033d9: Print::write(unsigned char const*, unsigned int) at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/Print.cpp line 76
0x40203455: preloop_update_frequency() at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/core_esp8266_main.cpp line 54
0x4010020c: _umm_free at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/umm_malloc/umm_malloc.c line 1285
0x4021ac4a: system_param_load at ?? line ?
0x4021ba73: wifi_softap_get_config_default at ?? line ?
0x402035e4: __udivmoddi4 at /home/igrokhotkov/xtensa/crosstool-NG/.build/src/gcc-4.8.2/libgcc/libgcc2.c line 1011
:  (inlined by) __umoddi3 at /home/igrokhotkov/xtensa/crosstool-NG/.build/src/gcc-4.8.2/libgcc/libgcc2.c line 1168
0x402033e4: Print::write(unsigned char const*, unsigned int) at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/Print.cpp line 76
0x4010502a: ets_timer_setfn at ?? line ?
0x40202bb5: Print::write(char const*) at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/Print.cpp line 76
0x40202bb5: Print::write(char const*) at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/Print.cpp line 76
0x40202be0: Print::println() at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/Print.cpp line 76
0x402010ae: delay at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/core_esp8266_wiring.c line 53
0x40201cd9: setup at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino line 33
0x4020318c: loop_wrapper at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/core_esp8266_main.cpp line 43
0x40100718: cont_norm at /home/agim/.arduino15/packages/esp8266/hardware/esp8266/2.2.0/cores/esp8266/cont.S line 109

**Comment by igrr** [comment] 2016-06-16 02:10
Closing as duplicate of #1997

**Closed by igrr** 2016-06-16 02:10 UTC
