### ISSUE TITLE
Arduino Scheduler lib does not work for esp8266

### ISSUE THREAD

**Issue by shiftleftplusone** [esp8266/Arduino#4162] opened 2018-01-13 22:08 UTC
the Scheduler examples (e.g. SchedulerBlink) do not compile for the esp8266
https://github.com/mikaelpatel/Arduino-Scheduler/tree/master/examples/SchedulerBlink
https://www.arduino.cc/en/Reference/Scheduler

when will there be a working adapted Scheduler lib for the esp8266?

(Arduino IDE 1.8.5, 1.8.4, 1.8.3 tested)

**Comment by 5chufti** [comment] 2018-01-13 23:24
why not ask the author of Arduino-Scheduler?
Or get hands-on and port it yourself?
This is not an issue with the arduino esp8266 core, so please close this issue per issue policy #3571

**Comment by devyte** [comment] 2018-01-14 00:10
This is not implemented, and is not currently planned within this repo.
Closing as duplicate of #3390 .

**Closed by devyte** 2018-01-14 00:10 UTC
