### ISSUE TITLE
 fatal error: ESP8266HTTPClient.h: 2.1.0-rc1 with arduino 1.6.5

### ISSUE THREAD

**Issue by mmiscool** [esp8266/Arduino#1392] opened 2016-01-08 22:52 UTC
I installed using the board mangers link for the staging version.

removed the old arduino15 directory from the appdata roaming folder before install to start fresh. Getting this error when compiling my project. 

C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:33:31: fatal error: ESP8266HTTPClient.h: No such file or directory
 #include <ESP8266HTTPClient.h>
                               ^
compilation terminated.
Error compiling.
##

**Comment by Links2004** [comment] 2016-01-09 11:02
you need to include the ESP8266HTTPClient lib in you sketch
```cpp
#include <ESP8266HTTPClient.h>
```

**Comment by mmiscool** [comment] 2016-01-10 17:46
I added that include to my sketch. Now I get the following error. 

This did work in the last staging version 

In file included from ESP8266Basic.ino:29:0:
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:129:20: error: 'String' has not been declared
         void begin(String url, String httpsFingerprint = "");
                    ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:129:32: error: 'String' has not been declared
         void begin(String url, String httpsFingerprint = "");
                                ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:131:38: error: 'uint16_t' has not been declared
         void begin(const char *host, uint16_t port, const char * url  = "/", bool https = false, const char * httpsFingerprint = "");
                                      ^
In file included from ESP8266Basic.ino:29:0:
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:132:20: error: 'String' has not been declared
         void begin(String host, uint16_t port, String url = "/", bool https = false, String httpsFingerprint = "");
                    ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:132:33: error: 'uint16_t' has not been declared
         void begin(String host, uint16_t port, String url = "/", bool https = false, String httpsFingerprint = "");
                                 ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:132:48: error: 'String' has not been declared
         void begin(String host, uint16_t port, String url = "/", bool https = false, String httpsFingerprint = "");
                                                ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:132:86: error: 'String' has not been declared
         void begin(String host, uint16_t port, String url = "/", bool https = false, String httpsFingerprint = "");
                                                                                      ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:142:25: error: 'uint16_t' has not been declared
         void setTimeout(uint16_t timeout);
                         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:148:18: error: 'uint8_t' has not been declared
         int POST(uint8_t * payload, size_t size);
                  ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:148:37: error: 'size_t' has not been declared
         int POST(uint8_t * payload, size_t size);
                                     ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:149:18: error: 'String' has not been declared
         int POST(String payload);
                  ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:150:44: error: 'uint8_t' has not been declared
         int sendRequest(const char * type, uint8_t * payload = NULL, size_t size = 0);
                                            ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:150:70: error: 'size_t' has not been declared
         int sendRequest(const char * type, uint8_t * payload = NULL, size_t size = 0);
                                                                      ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:151:44: error: 'Stream' has not been declared
         int sendRequest(const char * type, Stream * stream, size_t size = 0);
                                            ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:151:61: error: 'size_t' has not been declared
         int sendRequest(const char * type, Stream * stream, size_t size = 0);
                                                             ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:151:13: error: 'int HTTPClient::sendRequest(const char*, int*, int)' cannot be overloaded
         int sendRequest(const char * type, Stream * stream, size_t size = 0);
             ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:150:13: error: with 'int HTTPClient::sendRequest(const char*, int*, int)'
         int sendRequest(const char * type, uint8_t * payload = NULL, size_t size = 0);
             ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:153:30: error: 'String' does not name a type
         void addHeader(const String& name, const String& value, bool first = false);
                              ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:153:38: error: ISO C++ forbids declaration of 'name' with no type [-fpermissive]
         void addHeader(const String& name, const String& value, bool first = false);
                                      ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:153:50: error: 'String' does not name a type
         void addHeader(const String& name, const String& value, bool first = false);
                                                  ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:153:58: error: ISO C++ forbids declaration of 'value' with no type [-fpermissive]
         void addHeader(const String& name, const String& value, bool first = false);
                                                          ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:156:61: error: 'size_t' does not name a type
         void collectHeaders(const char* headerKeys[], const size_t headerKeysCount);
                                                             ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:156:68: error: ISO C++ forbids declaration of 'headerKeysCount' with no type [-fpermissive]
         void collectHeaders(const char* headerKeys[], const size_t headerKeysCount);
                                                                    ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:157:9: error: 'String' does not name a type
         String header(const char* name);   // get request header value by name
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:158:9: error: 'String' does not name a type
         String header(size_t i);              // get request header value by number
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:159:9: error: 'String' does not name a type
         String headerName(size_t i);          // get request header name by number
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:166:9: error: 'WiFiClient' does not name a type
         WiFiClient & getStream(void)  __attribute__ ((deprecated)) ;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:167:9: error: 'WiFiClient' does not name a type
         WiFiClient * getStreamPtr(void);
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:168:27: error: 'Stream' has not been declared
         int writeToStream(Stream * stream);
                           ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:169:9: error: 'String' does not name a type
         String getString(void);
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:171:16: error: 'String' does not name a type
         static String errorToString(int error);
                ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:176:11: error: 'String' does not name a type
           String key;
           ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:177:11: error: 'String' does not name a type
           String value;
           ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:181:9: error: 'WiFiClient' does not name a type
         WiFiClient * _tcp;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:182:9: error: 'WiFiClientSecure' does not name a type
         WiFiClientSecure * _tcps;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:185:9: error: 'String' does not name a type
         String _host;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:186:9: error: 'uint16_t' does not name a type
         uint16_t _port;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:188:9: error: 'uint16_t' does not name a type
         uint16_t _tcpTimeout;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:191:9: error: 'String' does not name a type
         String _url;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:193:9: error: 'String' does not name a type
         String _httpsFingerprint;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:195:9: error: 'String' does not name a type
         String _Headers;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:196:9: error: 'String' does not name a type
         String _userAgent;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:197:9: error: 'String' does not name a type
         String _base64Authorization;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:201:9: error: 'size_t' does not name a type
         size_t           _headerKeysCount;
         ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:212:36: error: 'Stream' has not been declared
         int writeToStreamDataBlock(Stream * stream, int len);
                                    ^
In file included from ESP8266Basic.ino:29:0:
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:129:58: error: invalid conversion from 'const char*' to 'int' [-fpermissive]
         void begin(String url, String httpsFingerprint = "");
                                                          ^
In file included from ESP8266Basic.ino:29:0:
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:132:61: error: invalid conversion from 'const char*' to 'int' [-fpermissive]
         void begin(String host, uint16_t port, String url = "/", bool https = false, String httpsFingerprint = "");
                                                             ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:132:112: error: invalid conversion from 'const char*' to 'int' [-fpermissive]
         void begin(String host, uint16_t port, String url = "/", bool https = false, String httpsFingerprint = "");
                                                                                                                ^
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0-rc1\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:150:64: error: 'NULL' was not declared in this scope
         int sendRequest(const char * type, uint8_t * payload = NULL, size_t size = 0);
                                                                ^
Error compiling.

**Comment by Links2004** [comment] 2016-01-10 18:31
what IDE you use for compiling?
eclipse need:
```
#include <Arduino.h>
```
before.

the Arduino IDE does it in background for you.

**Comment by mmiscool** [comment] 2016-01-10 18:41
I am using arduino ide 1.6.5

**Comment by mmiscool** [comment] 2016-02-25 03:23
Any word on this one?

**Comment by Links2004** [comment] 2016-02-25 09:40
this is woking for me in Arduino 1.6.5
with 2.1.0-rc1 and 2.1.0-rc2 with git version too.
try to remove all core versions that you may have and install them new.
```cpp
/**
 * httpUpdate.ino
 *
 *  Created on: 27.11.2015
 *
 */

#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <ESP8266HTTPClient.h>
#include <ESP8266httpUpdate.h>

#define USE_SERIAL Serial

ESP8266WiFiMulti WiFiMulti;

void setup() {

    USE_SERIAL.begin(115200);
    // USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

    for(uint8_t t = 4; t > 0; t--) {
        USE_SERIAL.printf("[SETUP] WAIT %d...\n", t);
        USE_SERIAL.flush();
        delay(1000);
    }

    WiFiMulti.addAP("SSID", "PASSWORD");

}

void loop() {
    // wait for WiFi connection
    if((WiFiMulti.run() == WL_CONNECTED)) {

        t_httpUpdate_return ret = ESPhttpUpdate.update("http://server/file.bin");
        //t_httpUpdate_return  ret = ESPhttpUpdate.update("https://server/file.bin");

        switch(ret) {
            case HTTP_UPDATE_FAILED:
                USE_SERIAL.printf("HTTP_UPDATE_FAILD Error (%d): %s", ESPhttpUpdate.getLastError(), ESPhttpUpdate.getLastErrorString().c_str());
                break;

            case HTTP_UPDATE_NO_UPDATES:
                USE_SERIAL.println("HTTP_UPDATE_NO_UPDATES");
                break;

            case HTTP_UPDATE_OK:
                USE_SERIAL.println("HTTP_UPDATE_OK");
                break;
        }
    }
}
```

**Comment by kmat** [comment] 2016-09-08 13:45
i have same error.
Anyone help us please.

**Comment by devyte** [comment] 2017-10-19 00:59
Can't reproduce with latest git. Closing.

**Closed by devyte** 2017-10-19 00:59 UTC

**Comment by pikolo84** [comment] 2018-10-17 22:07
I have this:
.piolibdeps\FirebaseArduino\src/ESP8266HTTPClient.h:138:10: error:   initializing argument 2 of 'bool HTTPClient::begin(String, uint16_t, String)' [-fpermissive]
bool begin(String host, uint16_t port, String uri = "/");
if add firebase to project with library httpupdater.

**Comment by ahmadasmndr** [comment] 2019-09-06 21:33
> 
> 
> you need to include the ESP8266HTTPClient lib in you sketch
> 
> ```c++
> #include <ESP8266HTTPClient.h>
> ```

thanks it worked for platform IO
