### ISSUE TITLE
warning: incompatible implicit declaration of built-in function 'memcpy'

### ISSUE THREAD

**Issue by grahamehorner** [esp8266/Arduino#1408] opened 2016-01-11 19:58 UTC
warning when compiling:-

...\2.1.0-rc1\cores\esp8266\core_esp8266_phy.c: In function '__wrap_register_chipv6_phy':

...\2.1.0-rc1\cores\esp8266\core_esp8266_phy.c:248:7: warning: incompatible implicit declaration of built-in function 'memcpy' [enabled by default]

```
   memcpy(init_data, phy_init_data, sizeof(phy_init_data));

   ^
```
##

**Comment by nouser2013** [comment] 2016-01-14 20:05
I do have the same issue with the GIT version that I installed not 5 minutes ago. It does not seem to affect code or functionality though.

**Comment by devyte** [comment] 2017-10-18 21:28
I don't see this message when building with latest git. Closing as can't reproduce.

**Closed by devyte** 2017-10-18 21:28 UTC
