### ISSUE TITLE
rst cause:1, boot mode:(3,7)

### ISSUE THREAD

**Issue by akashtalole** [esp8266/Arduino#2688] opened 2016-11-14 10:59 UTC
#### Hardware
Hardware:			NodeMCU ESP8266-12E
Core Version:      	?2.1.0-rc2?

### Description

Problem description
wdt 
### Settings in IDE

Module:  			NodeMCU ESP8266 12E 1.0 Module
Flash Size: 		4MB
CPU Frequency:	80Mhz
Flash Mode:			?qio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		 nodemcu1

### Debug Messages

Exception (9):
epc1=0x40203790 epc2=0x00000000 epc3=0x00000000 excvaddr=0x33342042 depc=0x00000000

ctx: sys 
sp: 3ffffdd0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffff70:  3fff1114 401017a7 00000000 00000000  
3fffff80:  401017e2 00000000 00000002 3ffee260  
3fffff90:  3fffdc10 00000000 3fff10e4 4021e86c  
3fffffa0:  40000f49 3fffdab0 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,0)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vc9f0c112
~ld

**Comment by devyte** [comment] 2017-10-10 04:39
@akashtalole without a sketch, there isn't much that we can do. Also, please use [EspExceptionDecoder](https://github.com/me-no-dev/EspExceptionDecoder) to get a human readable stack dump.
Closing due to lack of info, and old. If the issue is still valid, please open a new issue, and provide the info requested in the issue template.

**Closed by devyte** 2017-10-10 04:39 UTC
