### ISSUE TITLE
(Arduino IDE) ESP8266 E12 Wifi Board won't Connect to Wi-Fi

### ISSUE THREAD

**Issue by CiscoFrancis** [esp8266/Arduino#5227] opened 2018-10-11 12:37 UTC
Hi guys 
This is the error I get every time I try to get the Esp8266 connected to my Wi-Fi, I run the blink test and works fine, but when I try to get it connected to Wi-Fi I get the the attached error, I was suppose to get the serial monitor printing the IP Address .

this is my code `#include <ESP8266WiFi.h>

const char* ssid="ssid";
const char* password = "pass";

int ledPin = 13;

void setup() {
  
  pinMode(ledPin,OUTPUT);
  digitalWrite(ledPin,LOW);

  Serial.begin(115200);
  Serial.println();      
  Serial.print("Wifi connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid,password);
                                                Serial.println();
  Serial.print("Connecting");

  while( WiFi.status() != WL_CONNECTED )
  {
      delay(500);
      Serial.print(".");        
  }

  digitalWrite( ledPin , HIGH);
  Serial.println();

  Serial.println("Wifi Connected Success!");
  Serial.print("NodeMCU IP Address : ");
  Serial.println(WiFi.localIP() );

}

void loop() {
 
}`

![capture2](https://user-images.githubusercontent.com/44059528/46804155-2cfbf900-cd62-11e8-8500-fb1ae8a08385.PNG)

Waiting for your replies , thanks.

**Comment by devyte** [comment] 2018-10-11 15:15
I can't reproduce this on a wemos d1 r2, nodemcu, or wittycloud.
I'd say you likely have a hardware issue, e.g. high power drain for some reason and/or poor power supply.
Issue template was ignored, and can't reproduce, so closing.

**Closed by devyte** 2018-10-11 15:15 UTC
