### ISSUE TITLE
Different circuit neeeded for automatic upload using CP210x

### ISSUE THREAD

**Issue by probonopd** [esp8266/Arduino#480] opened 2015-06-28 13:19 UTC
[Comment shortened in order not to confuse people -- see https://github.com/esp8266/Arduino/issues/480#issuecomment-122993574 for the recommended circuit]

I can reliably upload using baud rate 921600.

It would be good if others could test this setup too and if it works for everyone, it could be changed in the README.

**Comment by Links2004** [comment] 2015-06-28 15:21
the problem is the Arduino IDE or you Serial terminal.

is the boot loading still working with the 10k?
i don't think its good for the stability of the uploading.

the problem shut be fixed in software (Arduino IDE) so that DTR and RTS is not activate in our case.
i use "real term" for serial debugging there i can control DTR and RTS manually.

**Comment by probonopd** [comment] 2015-06-28 15:24
Yes 921600 is working fine for me.

**Comment by cimba007** [comment] 2015-06-28 20:48
I thing I have the same problem here. What are your values for "pull up and pull down"? I am using 10k and only get ~2,2V on my gpio0, resulting from 3,3V high on DTR as it is not in use and a 10k pulldown but ofc. this is not enough if DTR got some decent amps I guess.

**Comment by probonopd** [comment] 2015-06-28 22:35
10K

**Comment by cimba007** [comment] 2015-06-29 10:01
What are u doing with GPIO0 and RESET when the CP210x  is not connected? What values are you using in this case?

**Comment by probonopd** [comment] 2015-06-29 13:43
Good point. In my case the CP210x is always connected and is also used to provide the 3.3V (which appears to work in my case).

**Comment by Links2004** [comment] 2015-06-29 15:25
https://github.com/esp8266/Arduino/blob/esp8266-sdk-1.0/README.md#minimal-hardware-setup-for-running-only

**Comment by probonopd** [comment] 2015-07-20 19:13
Following advice from igrr, I am now using the circuitry from the NodeMCU 1.0 for my ESP-12Es. See schematics of the NodeMCU 1.0.

Two 2N2222 npn transistors (10K) and 3 resistors, thereof 1 pullup for CH_PD. Working well.This circuit can be used for flashing and running, it does auto-reset and the serial monitor in the IDE can be used.

Possibly the documentation in the README should be updated to reflect this.

**Comment by JeroenBeemster** [comment] 2015-07-23 19:16
Thanks probonopd, This solved my issue aswell.For everyone who find it hard to read electronic schematics. I created a simplified example using a breadboard explanation.
http://www.arduinesp.com/blink

**Comment by probonopd** [comment] 2015-07-23 20:02
Thanks JeroenBeemster, I hope you are not offended if I attach your example for quick reference here.

![ttl-to-esp01-blink-npn](https://cloud.githubusercontent.com/assets/2480569/8860804/7206ca3c-3186-11e5-9dce-f9429a381d3b.png)

**Closed** 2015-07-30 07:00 UTC

**Comment by ReMiA00** [comment] 2015-10-14 07:41
I have tried several methods on resetting the ESP-12E for flashing with Arduino IDE
However none worked great, and all will break the "serial monitor" in the IDE

Since i had a **ATtiny85** lying around i used this to send the reset to the ESP and keep the GPIO0 down for a second after reset. 
- The RTS pulse on my CP2102 lasts about 5 to 8 millis
- When serial monitor is started RTS remains low until the monitor is closed.

```
/*
  Reset ESP-12E with ATTiny85 (8Mhz)
 */

#include <SoftwareSerial.h>
// Definitions
#define rxPin 3  
#define txPin 4

SoftwareSerial mySerial(rxPin, txPin);

const int RTS_pin = 2; // Pin 7 on Attiny
const int RST_pin = 0; // Pin 5 on Attiny
const int GPIO0_pin = 1; // Pin 6 on Attiny

// Hookup 
// ESP     <--> Tiny pin <--> CP2102 or FT232RL
//  GND   <--> 4           <--> GND
//  5V      <--> 8 
//                    7           <--> RTS 
//  RST    <--> 5            
//  GPIO0 <--> 6                  
//  RX <-------------------> TX
//  TX <-------------------> RX

unsigned long StartReset = 0;
unsigned long Puls = 0; 

void setup() {
  mySerial.begin(9600);

// USB to Serial Converter Flow Control
  pinMode(RTS_pin,INPUT);

// ESP Pins
  pinMode(RST_pin,OUTPUT);
  pinMode(GPIO0_pin,OUTPUT);
  digitalWrite(RST_pin, HIGH);
  digitalWrite(GPIO0_pin, HIGH);
}

void loop() {
  int RTS = digitalRead(RTS_pin);
  
  if (RTS == 0 and StartReset == 0 ) { // Start Reset Puls
    StartReset = millis();
    mySerial.println("Reset");
  } 
  if (RTS == 1 and StartReset > 0 ) {  // Eind Reset Puls
    Puls = millis() - StartReset;
    mySerial.print("Puls = ");
    mySerial.println(Puls);
    StartReset = 0;
    
    if (Puls > 0 and Puls < 20) { // puls is around 5 to 8 millis
      digitalWrite(RST_pin, LOW);
      digitalWrite(GPIO0_pin, LOW);
      delay(5);        // length Reset puls
      digitalWrite(RST_pin, HIGH);
      delay(1000);        // Wait for ESP to boot
      digitalWrite(GPIO0_pin, HIGH);
      Puls = 0;
    }  
  }
}
```

I used a Arduino Nano with ArduinoISP sketch to program the ATTiny using IDE 1.6.5 
Add in "Boards Manager" https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json

Wire it up:
// Hookup to Program ATTiny85
// NANO   <--> Tiny pin
//  GND   <--> 4
//  5V    <--> 8
//  10    <--> 1
//  11    <--> 5
//  12    <--> 6
//  13    <--> 7

Choose ATTiny85 Board at 8Mhz and flash the Bootloader
Now you can upload the sketch to the ATTiny (use Arduino as ISP as programmer)

Wires for Serial debugging
// NANO   <--> Tiny pin
//  RX(0) <--> 3 serial monitor
//  TX(1) <--> 4 serial monitor

**Comment by vicatcu** [comment] 2015-10-20 14:33
@igrr @probonopd ... reading the README on the [esptool github repository](https://github.com/themadinventor/esptool), and using pin nomenclature from [the wiki](https://github.com/esp8266/esp8266-wiki/wiki/Pin-definition), it says:

> esptool uses the RTS and DTR modem status lines to automatically enter the bootloader. Connect RTS to CH_PD (which is used as active-low reset) and DTR to GPIO0.

I believe CHIP_EN is synonymous with CH_PD (i.e. pin 7 of the ESP8266).. Looking at the whole NodeMCU 0.9 schematic, it would appear that they label this net "EN" and it is simply pulled up to 3.3V. They effectively connect the net named "nRST" which is synonymous with EXT_RSTB (i.e. pin 32 of the ESP8266), to the DTR line, and effectively connect GPIO0 to the RTS line. That's quite a difference to the recommendations of esptool. 

GPIO0, GPIO2, and EXT_RSTB are also passively pulled up to 3.3V, and GPIO15 is passively pulled down to GND.

The difference between CHIP_EN and EXT_RSTB is pretty subtle, so it probably doesn't matter (?) which one gets wiggled for auto-reset/upload support.. But I'm more doubtful where it comes to the differences between RTS and DTR. Is the circuitry in this thread above still sound, or should new hardware wire to DTR in agreement with the esptool  recommendations?

**Comment by igrr** [comment] 2015-10-20 15:08
The circuit in this thread works with esptool-ck when reset method is set
to 'nodemcu'. It might be different with esptool.py which you linked to.

**Comment by vicatcu** [comment] 2015-10-20 15:14
@igrr interesting, didn't realize there was a difference. So does auto-reset not work for "Generic ESP8266 Module" selections, or is the same wiring applicable in that case? I'm asking because I'm putting designing in an ESP8266 module on a board right now and would like to have it be compatible with this project.

**Comment by hallard** [comment] 2015-11-12 18:32
For those who just have FTDI cable with only DTR and no RTS line, I'm using this one (FTDI 5V compatible) with great success on ESP12 and ESP07

![image](https://cloud.githubusercontent.com/assets/2471931/11127193/4a29a71a-8973-11e5-9548-e8c2effe4d6f.png)

Of course for this to work, don't forget Pull up on GPIO0 and Reset (10K each) and pull down on GPIO15 (10K also) and 10K pullup on CH_PD but you know this one.

If your FTDI is 3V3 don't try to power your board with it (use another source), lot's of FTDI onboard reg can't do 200mA needed sometimes by ESP

**Comment by hallard** [comment] 2015-11-17 18:53
After some investigation, it's better to reset with CH_PT
here it [why](http://hallard.me/esp8266-autoreset/) I've update previous schematic

**Comment by ReMiA00** [comment] 2015-11-17 22:46
This looks promosing !
Will the serial monitor also work in the IDE ?

**Comment by hallard** [comment] 2015-11-17 22:55
@ReMiA00 
yes Serial monitor works fine with this and FTDI like cable, I I use it every day ;-)

**Comment by tablatronix** [comment] 2015-12-22 20:04
I am using the nodemcu circuit and it works great for programing, but my module reboots when I open and close the serial monitor.

My logic probe, says my adapter DTR and RST are both high at rest and LOW when serial monitor is open ( same for putty ). Changes to neither `serial.disable...` settings makes any difference either,

Using IDE 1.6.6, and git version of repo.

**Comment by tablatronix** [comment] 2015-12-22 21:24
FYI, I am using 2n3904 transistors (have a bunch) with 10k base resistors, I have not bothered calculating proper resistor values yet.. Seems to work ok for programming every time so far.

**Comment by jayseeee** [comment] 2016-01-03 23:11
I had to come up with another circuit to do the "autoreset" with the FDTI interface as none of the above mentioned worked for me. I designed the PCB as an interface in between the FDTI an the board to be programmed, with an additional output of RESET and FLASH (GPIO0).

![autoreset_sch](https://cloud.githubusercontent.com/assets/1778255/12081377/0247d548-b277-11e5-98ef-7dfe8c18e613.png)

**Comment by muke1970** [comment] 2016-07-08 22:17
I tried JeroenBeemster's circuit on esp8266-01 and work very well. I tried the same on esp8266-12F but receive warning: espcomm_sync failed error: espcomm_open failed error: espcomm_upload_mem failed. The same with hallard's. Do you have suggestions for me? :-)

**Comment by muke1970** [comment] 2016-07-09 02:31
Sorry I make a mistake to wiring esp8266-12F.
It work like a charm!
Thanks again.
Emiliano.

**Comment by tablatronix** [comment] 2016-07-09 02:40
Make sure you are using nodemcu reset mode not ck

**Comment by paulwww** [comment] 2016-08-02 13:52
ReMiA00 many thanks for the attiny85 solution. It is working well for me. At first I got it to work on an atmega328 since I could easily debug/test there. I then went to the attiny85 and built a circuit between my FTDI and ESP8266, now it is even more fun to develop for the ESP8266.
