### ISSUE TITLE
ctags pattern is missing

### ISSUE THREAD

**Issue by johnjcouture** [esp8266/Arduino#4051] opened 2017-12-31 00:38 UTC
#### Hardware
Hardware:	Generic ESP8266
Core Version:      	Arduino 1.8.5

### Description

Haven't used IDE for about a month.  
Started with simple blink example and selected Generic ESP8266.  
Preferences set with index.json
Program will not compile.

Reinstalled IDE, no joy

Deleted  the preferences.txt file and rebuilt it.  no joy

program with just setup and loop and it still will not compile.

I know I'm missing something simple.

**Comment by devyte** [comment] 2017-12-31 01:29
Delete everything and install from scratch. Don't forget to back up your sketches first.
Closing as can't reproduce.

**Closed by devyte** 2017-12-31 01:29 UTC

**Comment by johnjcouture** [comment] 2017-12-31 17:17
Ok, Thank you.
