### ISSUE TITLE
Processor crash when WIFi goes down

### ISSUE THREAD

**Issue by bsculley** [esp8266/Arduino#3395] opened 2017-07-02 22:17 UTC
#### Hardware
Hardware:			WeMos D1 Mini
Core Version:      	2.3.0 commit b695898 
### Description

My WiFi network is being very flakey, which is its own issue, but whenever the ESP-8266 loses the connection it reboots.  I have a whole collection of devices on the network and they are all rebooting constantly.  I have seen lots of posts related to this problem, some claiming that the problem was fixed, but it doesn't look fixed to me.

I need the device to just keep retrying the WiFi connection while it goes on about its other tasks.

### Settings in IDE

Module:  			WeMos D1 Mini
Flash Size: 		4MB
CPU Frequency:       80MHz
Flash Mode:		
Flash Frequency:	
Upload Using:		OTA 
Reset Method:		

### Sketch

Using Sonoff-Tasmota in WeMos D1 Mini configuration

### Debug Messages

Exception 28 flag 2
Exception 29 flag 2

**Comment by devyte** [comment] 2019-11-08 21:43
This report is old. A lot has changed since it was opened, including several relevant fixes.
Closing.
If you think the problem is still relevant, please open a new issue and follow the instructions in the issue template.

**Closed by devyte** 2019-11-08 21:43 UTC
