### ISSUE TITLE
Json file read error

### ISSUE THREAD

**Issue by MrBean14** [esp8266/Arduino#6069] opened 2019-05-11 10:26 UTC
Hello,

this morning I was working with the Wemos D1 Mini board and just as once, I started getting this error : 

```
Geleverd index bestand /Users/alex/Library/Arduino15/package_esp8266com_index.json word overgeslagen, lees fout opgetreden:
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Dropping': was expecting ('true', 'false' or 'null')
 at [Source: (FileInputStream); line: 1, column: 10]

```
Translated it says "Delivered index file .... was skipped, read error appeared"

Any idea what is happening? What can I do to solve it please?

Best regards,

Davy

**Comment by d-a-v** [comment] 2019-05-11 10:30
duplicate of #6068

**Closed by d-a-v** 2019-05-11 10:30 UTC
