### ISSUE TITLE
Reinterpret_cast in async_ping not compiling

### ISSUE THREAD

**Issue by GlenSchaff** [esp8266/Arduino#4419] opened 2018-02-23 09:07 UTC
I upgraded from 2.30 to 2.40, compiling aync_ping.cpp fails.

Compiler errors occur on raw_recv() in async_ping.cpp reinteepret_cast .

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			esp8266
Core Version:      	2.40

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 	2MB
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		generic8266

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by devyte** [comment] 2018-02-27 01:02
Closing as duplicate of #4418

**Closed by devyte** 2018-02-27 01:02 UTC
