### ISSUE TITLE
during erase flash, send data to Serial, module will wdt reset。

### ISSUE THREAD

**Issue by chenkaiyao** [esp8266/Arduino#4316] opened 2018-02-07 15:07 UTC
#### Hardware
Hardware:	        ESP-12
Core Version:      	2.1.0-rc2

### Description

during erase flash, send data to Serial。module will wdt reset。

send data 
```
122222222222221222222222222212222222222222122222222222221222222222222212222222222222122222222222221222222222222212222222222222122222222222221222222222222212222222222222122222222222221222222222222212222222222222
```

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		 SERIAL
Reset Method:		nodemcu

### Sketch

```cpp
extern "C" {
#include "c_types.h"
#include "ets_sys.h"
#include "os_type.h"
#include "osapi.h"
#include "spi_flash.h"
}

extern "C" uint32_t _SPIFFS_end;

void setup()
{
  Serial.begin(115200);
}

uint32_t _sector = ((((uint32_t)&_SPIFFS_end - 0x40200000) / SPI_FLASH_SEC_SIZE));

void loop()
{
  while(Serial.available()>0)
  {
    Serial.print(Serial.read());
  }
  
  Serial.print("erase\r\n");
  noInterrupts();
  spi_flash_erase_sector(_sector);
  interrupts();
}
```

### Debug Messages

```
erase
erase

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v074402e2
~ld
erase
```

**Comment by WereCatf** [comment] 2018-02-08 01:25
Try adding Serial.flush() before noInterrupts() or a delay?

**Comment by devyte** [comment] 2018-02-08 02:08
@chenkaiyao I can't reproduce this on a Wemos D1 mini r2 or on a WittyCloud. I get continous "erase" lines in the Serial monitor non stop. Left it running for a couple of minutes.

Writing to flash draws more current, so it's possible this is a bad power supply.

Closing as can't reproduce.

**Comment by chenkaiyao** [comment] 2018-02-08 02:20
@devyte you should send data to serail

**Comment by chenkaiyao** [comment] 2018-02-08 02:22
@devyte you can send data to module through Serial tool。 eg. 

send data 
```
122222222222221222222222222212222222222222122222222222221222222222222212222222222222122222222222221222222222222212222222222222122222222222221222222222222212222222222222122222222222221222222222222212222222222222
```

**Comment by devyte** [comment] 2018-02-08 06:29
I managed to reproduce on a wemos d1 mini. 
Doing a pure erase loop works.
Doing a pure serial loop works, even with the long string.
Doing both together with a short string works.
Doing both together with the long string doesn't triggers wdt.
Adding yield in the while orn right after it doesn't help.
Adding Serial.flush doesn't help. 
A delay(5) before the erase helps, but I suspect because it slows things down.

**Comment by chenkaiyao** [comment] 2018-02-08 06:55
i find module all enter uart interrupts, end trigger wdt

**Comment by d-a-v** [comment] 2018-02-08 09:01
Do you think this sketch should be converted into pure esp-nonos-sdk C program ?

**Comment by earlephilhower** [comment] 2019-01-24 00:22
I believe this was related to the Serial FIFO overflow crash (since IRQs disabled while in flash op, you wouldn't get the IRQ and the old Serial code would crash).  That's been fixed and a) overflow now is noted and doesn't crash, and b) IRQs aren't disabled by flash ops.

**Closed by earlephilhower** 2019-01-24 00:22 UTC
Labels: component: core, type: bug
