### ISSUE TITLE
SoftAP mode causes http, ping, etc. timeouts and failures.

### ISSUE THREAD

**Issue by Untitled86** [esp8266/Arduino#2687] opened 2016-11-14 06:07 UTC
**In SOFT_AP mode the device fails to respond consistently.** Replicate this simply by running a SoftAP example web server and executing "ping youripaddress -t" from the command line. You might see a few requests go through before it starts failing to respond. Sometimes it does respond, just not constantly.

_Optionally you can replicate this simply by trying to refresh a page a few times in your browser. The 8266 will only respond sometimes. I used the ping example because it eliminates a lot of browser code from the equation._

Solve this by adding MDSN to your sketch!?! ...I have no idea, but I swear, this fixes the problem and the 8266 responds EVERY single time.

Just add...

`#include <ESP8266mDNS.h>`

To the top of your Sketch.

Then add...

`WiFi.hostname("ESP8266");`

Before your "softAP(ssid, pwd)" line.

And last add...

```
MDNS.begin("ESP8266");
MDNS.addService("http", "tcp", 80);
```
After your "softAP(ssid, pwd)" line.

Clearly the ESP8266-Webserver examples should be changed to use this code.  They truly DO NOT FUNCTION PROPERLY without it.

**Comment by devyte** [comment] 2017-10-10 04:44
@Untitled86 If the ESP is put into StationAP mode, or if in SoftAP mode a scan is done, then the connectivity  can be lost. This is due to the ESP having only one radio. In StationAP, if the station part is on one channel, but the SoftAP part is on a different channel, then the radio may skip back and forth, which causes trouble (there is a channel change notification implemented by Espressif, but it's bugged).
This is a known issue, and there isn't much that can be done in this repo at this time.
For a simple SoftAP, without scans, or for StationAP, where the station and AP are on the same channel, I can't reproduce ping loss with latest git. I'm using this myself, and ping is stable over hours.
Closing.

**Closed by devyte** 2017-10-10 04:44 UTC
