### ISSUE TITLE
fmodf() causes link error

### ISSUE THREAD

**Issue by pidloop** [esp8266/Arduino#2517] opened 2016-09-14 15:38 UTC
#### Hardware

Hardware:           ?ESP-12?
Core Version:       ?2.1.0-rc2?
### Description

Problem description
### Settings in IDE

Module:             Adafruit HUZZAH Feather
Flash Size:         ?4MB/1MB?
CPU Frequency:      ?80Mhz?
Flash Mode:         ?qio?
Flash Frequency:    ?40Mhz?
Upload Using:       ?OTA / SERIAL?
Reset Method:       ?ck / nodemcu?
### Sketch

``` cpp

#include <Arduino.h>

void setup() {
    float x = fmodf (10.0, 20.0);
}

void loop() {

}
```
### Debug Messages

```
messages here
```

Whenever I try to use fmodf() I get the following link error:

/Users/ecdowney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/lib/libm.a(lib_a-ef_fmod.o):(.literal+0x0): undefined reference to `__ieee754_remainderf'
/Users/ecdowney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/lib/libm.a(lib_a-ef_fmod.o): In function`__ieee754_fmodf':
ef_fmod.c:(.text+0x36): undefined reference to `__ieee754_remainderf'
collect2: error: ld returned 1 exit status

**Comment by devyte** [comment] 2017-10-12 19:58
@pidloop latest git seems to build fine from Arduino IDE with this.
Closing as can't reproduce.

**Closed by devyte** 2017-10-12 19:58 UTC
