### ISSUE TITLE
udp->endPacket() is silently dropping packets

### ISSUE THREAD

**Issue by everslick** [esp8266/Arduino#2285] opened 2016-07-16 13:00 UTC
This issue is a followup from https://github.com/esp8266/Arduino/issues/1009#issuecomment-189805820

when rapidly sending UDP packets, udp_sendto() (called from libraries/ESP8266WiFi/src/include/UdpContext.h:286 will not report an error, if it silently drops the packet for whatever reason (buffer allocation?).

even though UDP is inherently 'unreliable', the API should still report internal errors if possible, so users of the API can deal with them.

**Comment by barsznica** [comment] 2016-09-29 16:58
Similar to my problem. [Issue #2340](https://github.com/esp8266/Arduino/issues/2340)

**Comment by lovelesh** [comment] 2016-11-02 13:06
@igrr @everslick 
I am trying to send only 64 Byte packets, only first 37 bytes gets transmitted. But sometimes I am able to read all 64 Bytes.

I tried yield() and delay(1) as per your suggestion. Is there any definite for reliable transmission atleast from the device side.

**Comment by everslick** [comment] 2016-11-02 13:23
IMHO there is something else wrong with your code. even though the UDP
stack does not report errors when sending packets too fast, it always sends
complete datagrams as long as they are below the max frame size (~1400
bytes ???). I use UDP a lot and I have never seen shortened or corrupted
datagrams. nevertheless UDP is unreliable per definition (packets might get
lost on the wire) and if you need reliability you should switch to TCP.

**Comment by devyte** [comment] 2017-10-15 02:38
@everslick is this issue still valid in latest git? Does PR #3362 (lwip2) help?

**Comment by igrr** [comment] 2017-10-15 07:34
Yes it is still valid. The root cause is in the SDK, but i would like to keep this open for now.

**Comment by everslick** [comment] 2017-10-15 07:46
This will need some time for me to check. I completely switched to ESP32.
But I will have a look.

**Comment by d-a-v** [comment] 2017-11-18 15:22
The ```udp.endPacket()``` always returning 1 problem seems to be fixed with lwip2 (see #3481)
@lovelesh If you could post your sketch in which you don't receive all your sent data, we can test it with lwip2.

**Comment by lovelesh** [comment] 2017-11-20 05:26
@d-a-v i solved this problem by increasing the buffer in the lwip library based on solution provided in some discussion. Its working fine, so i didnot bother much.

**Comment by everslick** [comment] 2019-02-07 18:02
I'm good with closing this issue. I can confirm, that LwIP2 has this fixed.

**Comment by d-a-v** [comment] 2019-02-07 18:16
> I'm good with closing this issue. I can confirm, that LwIP2 has this fixed.

Thanks for your feedback!

@lovelesh Which buffer did you modify ?

**Comment by d-a-v** [comment] 2019-08-28 23:49
Closing for the same reason as for #1988.
Please open a new issue if it is still relevant with current git master version.

**Closed by d-a-v** 2019-08-28 23:49 UTC
Labels: component: libraries, type: bug, waiting for feedback
