### ISSUE TITLE
Failed to connect with multiple access points

### ISSUE THREAD

**Issue by bseewald** [esp8266/Arduino#3405] opened 2017-07-06 19:48 UTC
I have the following scenario: 

I need to connect in a network with multiple access points (same SSID and open). 
My device always connect to a specific BSSID (20:B3:99:46:91:C8) but it seems that never receives an IP.
PS: I already tried to change the AP and my device location but sometimes connect, sometimes don't. The behavior is unstable.
Through the debug I see the messages:

connected with X, channel Y
dhcp client start...
cnt
wifi evt: 0
wifi evt: 7
wifi evt: 7
wifi evt: 7
..

and this continues forever.

The APs are all Enterasys with dual band, no firewall, open, without certificates. My computer and smartphone connect just fine. 

Any help ?

#### Hardware
Hardware:	        ESP-07
Core Version:      	2.3.0

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		1MB/64k
CPU Frequency:	80Mhz
Flash Mode:		DIO
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		ck

### Sketch

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <ESP8266HTTPClient.h>
#include <ESP8266WebServer.h>

void setup() {
	Debug_print.begin(115200);       
	Serial1.begin(115200);        
	Serial1.setDebugOutput(true);
	initWiFi01();  
        ...
        ...
}

void initWiFi01 (void){
	struct wifiFields {
		String ssid;
		String key;
		bool dhcp;
		IPAddress ip;
		IPAddress mask;
		IPAddress gateway;
		IPAddress dns1;
		IPAddress dns2;
	};
	wifiFields wifiConfig;

	WiFi.setOutputPower(20.5);              
	WiFi.hostname(HOSTNAME);

	wifiConfig.dhcp = readEEPROMuint8 (WIFI_DHCP_STATIC_ADDRESS_EEPROM);
	wifiConfig.ssid = readEEPROMstring (WifiSSID_ADDRESS_EEPROM,32);
	wifiConfig.key = readEEPROMstring (WifiKEY_ADDRESS_EEPROM,32);

	if (wifiConfig.dhcp==DHCP_MANUAL){
		for (unsigned char i=0;i<4;i++){
		wifiConfig.ip[i] = readEEPROMuint8(WIFI_IP_STATIC_ADDRESS_EEPROM + i);
		}
		for (unsigned char i=0;i<4;i++){
			wifiConfig.mask[i] = readEEPROMuint8(WIFI_MASK_STATIC_ADDRESS_EEPROM + i);
		}
		for (unsigned char i=0;i<4;i++){
			wifiConfig.gateway[i] = readEEPROMuint8(WIFI_GATEWAY_STATIC_ADDRESS_EEPROM + i);
		}
		for (unsigned char i=0;i<4;i++){
			wifiConfig.dns1[i] = readEEPROMuint8(WIFI_DNS1_STATIC_ADDRESS_EEPROM + i);
		}
		for (unsigned char i=0;i<4;i++){
			wifiConfig.dns2[i] = readEEPROMuint8(WIFI_DNS2_STATIC_ADDRESS_EEPROM + i);
		}
		WiFi.config(wifiConfig.ip, wifiConfig.gateway, wifiConfig.mask, wifiConfig.dns1, wifiConfig.dns2);
	}

       // Password ?
	signed char _firstChar = wifiConfig.key[0];
	if (_firstChar == '\0'){
		//Debug_println("Inspeção: sem senha");
		WiFiMulti.addAP(wifiConfig.ssid.c_str());
	} else {
		//Debug_println("Inspeção: com senha");
		WiFiMulti.addAP(wifiConfig.ssid.c_str(),wifiConfig.key.c_str());
	}

	Debug_println("Wait for WiFi... ");
	delay(100);
	unsigned long _countAux = millis();
	while (((_countAux+5000)>millis())&&(WiFiMulti.run()!=WL_CONNECTED)){ 
		delay(500);
	}
}

void loop() {
   ...
   blah blah
}
```

### Debug Messages

```
![exception_4](https://user-images.githubusercontent.com/1646231/27928565-1aa6200e-6266-11e7-8a90-102b7c9e8738.jpg)

```

**Comment by devyte** [comment] 2019-11-10 01:28
I have a very similar setup: multiple router APs with the same SSID. In my case they are meshed with each other, and the one that works as an internet gateway is the one that works as a DHCP server for the entire network. I use ESP12Es instead of 7s, but they're similar enough. 
I don't have any issues connecting. I can even walk with an ESP across the different routers.
This issue is old, a whole lot has changed since it was reported.
Closing.
If you think the problem is still relevant, please open a new issue and follow the template instructions.

**Closed by devyte** 2019-11-10 01:28 UTC
