### ISSUE TITLE
std::unordered_map

### ISSUE THREAD

**Issue by tomkcook** [esp8266/Arduino#1513] opened 2016-01-27 12:26 UTC
Similar to #1136, attempting to use `std::unordered_map` gives the following linker errors:

```
sketch/Test.ino.cpp.o:(.text.setup+0x8): undefined reference to `std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned int) const'
sketch/Test.ino.cpp.o: In function `setup':
/home/tkcook/Arduino/Test/Test.ino:3: undefined reference to `std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned int) const'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling.
```

this while compiling the following code:

```
#include <unordered_map>
void setup() {
  std::unordered_map<int,int> map;
}
void loop() {
}
```

I guess the relevant bit of libstdc++ is not being linked in.  Is there some (straightforward) way to get it linked in?
##

**Comment by liquidfalcon** [comment] 2016-01-27 18:10
I don't believe libstdc++ is linked in at all, at least in the standard setup. Add "-lstdc++" to the end of "compiler.c.elf.libs=" in platform.txt and it should link.

**Comment by igrr** [comment] 2016-02-03 22:44
@tomkcook did adding `-lstdc++` resolve this issue for you?

**Comment by GalloTeo** [comment] 2016-06-06 01:39
not for me

**Comment by devyte** [comment] 2017-10-18 18:16
I can't reproduce this with latest git, build works fine. Closing.

**Closed by devyte** 2017-10-18 18:16 UTC
