### ISSUE TITLE
Auto upload working in Win7 but not in Ubuntu Linux

### ISSUE THREAD

**Issue by guyelg** [esp8266/Arduino#498] opened 2015-07-01 08:16 UTC
Hi
I have tried to upload new sketch to Nodemcu Dev Board V0.9 .
Same computer and same USB port.
Its work like charm in Win7  but with Ubuntu i have to press on the upload botton
10x
Guy
##

**Comment by devyte** [comment] 2017-10-20 06:26
I can flash Nodemcu boards from Ubuntu without issues. 
Closing due to age, lack of info, and can't reproduce.

**Closed by devyte** 2017-10-20 06:26 UTC
Labels: component: uploader
