### ISSUE TITLE
WiFiClient connect() fails randomly

### ISSUE THREAD

**Issue by HorstWalter** [esp8266/Arduino#1964] opened 2016-04-23 05:33 UTC
Hardware:           ESP-07
Core Version:       2.1.0 (i think, where do I see it?)

Problem description
Every 5 minutes, I connect fromthe ESP to a Linux remote server (via WAN) which has an open port (and implements my own binary protocol). The ESP8266 connects to this remote port and exchanges data.

It works, but randomly the connect() call fails. The Linux server is running rock solid. I can connect from another Linux box to the same port with the same protocol without any failures.

Is it possible that the yield() call within connect() is sometimes not sufficient, so that connect() returns a failure because the ESP has not enough time to establish a connection?
##

**Comment by igrr** [comment] 2016-04-27 03:27
Can you do a wireshark/tcpdump trace of what is happening on the network?

**Comment by HorstWalter** [comment] 2016-04-27 12:31
How do I put a PC with wireshark between the ESP and the remote server, which is not in the LAN (has a public IP and stands hundreds kilometres away at an ISP)?

**Comment by igrr** [comment] 2016-05-10 15:54
With wireshark you can actually capture packets from the wireless network your ESP is connected to.

**Comment by devyte** [comment] 2017-10-17 16:16
No feedback in over a year, closing per #3655 . If the issue is still valid, please open a new one, and add the relevant details, as well as a MCVE sketch.

**Closed by devyte** 2017-10-17 16:16 UTC
