### ISSUE TITLE
Spaces in SSID and password resets esp8266

### ISSUE THREAD

**Issue by demandajmenso** [esp8266/Arduino#1342] opened 2016-01-01 07:59 UTC
Can anyone confirm this? After some head scratching i finally figured out why my module resets or doesn't respond in some cases when i try to connect to an AP which has spaces in SSID and/or password.
##

**Comment by celsworth** [comment] 2016-01-01 13:47
As a point of reference, my AP password has spaces in it (but my SSID doesn't) and I've never seen a reset because of it.

**Comment by WheresWally** [comment] 2016-05-04 15:08
I had the exact same error because I had a trailing space after the SSID,

**Comment by devyte** [comment] 2017-10-19 05:50
I can't reproduce this with latest git. Connecting to my Android hotspot (ssid has a space) works fine.
Closing as can't reproduce.

**Closed by devyte** 2017-10-19 05:50 UTC

**Comment by nalinda6963** [comment] 2018-07-10 02:12
@AalianKhan did you find the issue with your sonoff. I am having a similar issue with sonoff basic when upgrading the firmware fro 5.14 to 6. I tried to re-flash with 5.14 and the following log keeps coming up. 

00:00:00 CFG: Use defaults
00:00:00 Project sonoff2 Sonoff (Topic sonoff2, Fallback DVES_A7C27E, GroupTopic sonoffs) Version 5.14.0-2_4_1
00:00:00 WIF: Connecting to AP1 <MY-SSID> in mode 11N as sonoffx-xxxx...

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

**Comment by nalinda6963** [comment] 2018-07-13 02:28
@AalianKhan Thanks. I will check the documentation and try this later.

**Comment by AceoStar** [comment] 2020-06-11 22:38
I'm currently seeing this on NodeMCU

**Comment by AceoStar** [comment] 2020-06-11 22:43
I'm still seeing this issue on NodeMCU.
`#include <ESP8266HTTPClient.h>
#include "ESP8266WiFi.h"


char myssid[] = "Spaces are great til they are not";
char mypass[] = "password";

const char* Host = "www.unwiredlabs.com";
String endpoint = "/v2/process.php";

void setup() {
  Serial.begin(115200);

  // Set WiFi to station mode and disconnect from an AP if it was previously connected
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  Serial.println("Setup done");

  // We start by connecting to a WiFi network
  Serial.print("Connecting to ");
  Serial.println(myssid);
  WiFi.begin(myssid, mypass);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println(".");
}
`
