### ISSUE TITLE
Strange behavior on interrupts

### ISSUE THREAD

**Issue by HobbytronicsPK** [esp8266/Arduino#1372] opened 2016-01-05 15:54 UTC
Hi. I am using a two double channel relays with ESP-8266 12E. Please study attached picture for understanding my setup. I am using pubsubclient to publish and subscribe MQTT message to Mosquitto which is connected to Node-red and Domoticz. In short, four AC switches are being controlled from domoticz and also with 4 tactile push button switches with interrupt enabled. This setup works very stable (It's working since a week without any issue) if interrupts are disabled but when I enable interrupts, it behaves strange, if I want to turn relay one off, which is attached to GPIO13, relay four also turns off which is attached to GPIO5. If interrupts are disabled (I can enable and disable interrupts with MQTT messages), system works without any issue. May someone please help me with this problem?
![relay setup](https://cloud.githubusercontent.com/assets/16560199/12119668/d13210c6-b3ee-11e5-999f-4bbbca2e25ee.png)
##

**Comment by Links2004** [comment] 2016-01-05 16:15
you using the china relay boards?
if you switch loads with them they generate a EMC pulse, may it triggers your local switches.
i one setup they generate a reset of my esp, since then i only use solid state relais.
try to add some capacitors  to yous switches => 100nF.
a bigger cap for 3V3 >=47uF may also help 2x 100nF is a bit less for the ESP.

**Comment by vickeyhort** [comment] 2016-01-05 16:44
Yes I am using China boards, May you please suggest where should I add capacitors in switches? I have a solid power supply, and ESP8266 is running very fine, I just have that false interrupt trigger, How can I suppress the effect of EMC pulse? I have a lot of relays already, and I don't wanna waste these.

**Comment by Links2004** [comment] 2016-01-05 17:15
add between GPIOx and GND a ceramic capacitor (100nF or less).
adding a Pullup for D4 and D2 may also helps.
the EMC comes from 2 thinks: 
- the relay coil itself (always the same)
- the closing "switch" inside the relay (more load creates higher EMC pulse)

if you buy new stuff at on point, order solid state relays :)
for big load a good one is SSR-25DA or for load < 450W G3MB-202P both have zero crossing switching which reduce EMC too.

**Comment by vickeyhort** [comment] 2016-01-05 17:21
I also have SSR-10DA. May It run 2 horse power 240 v electric pump?

**Comment by Links2004** [comment] 2016-01-05 17:25
SSR-10DA can handle up to 2400W, how many Watt are "2 horse power" ?

**Comment by vickeyhort** [comment] 2016-01-05 17:33
2 hp = 1491 watts.
Thank you so much Links2004 for your kind support. but sorry I did not understand your previous comments about capacitors. As in picture above, I have four push button switches, which are connected at one end to gpio and to other end to GND, where should I put capacitor between them? Do you mean between gpio and GND of that particular switch prior to press button switch?

**Comment by Links2004** [comment] 2016-01-05 17:51
this is better understandable I think:
![image](https://cloud.githubusercontent.com/assets/974709/12122748/3eaeaafe-b3dd-11e5-9738-eb6b8a291910.png)

**Comment by penfold42** [comment] 2016-01-05 22:10
I've just built something similar and this is very timely.

How quickly does the ESP check the GPIOs for the boot mode on power up ?

The time constant here will mean gpio2 will read low for about a millisecond.

**Comment by Links2004** [comment] 2016-01-05 23:42
good point.
may add a 200nF to the Reset and it can not be a problem.
a lower C value may work the same, the needed size is depending on how strong the EMC is.
lowering R is a potion too, but lower then 1k is not recommended for a pullup.

**Comment by igrr** [comment] 2016-02-29 09:30
@vickeyhort has the issue been resolved for you?

**Comment by vickeyhort** [comment] 2016-02-29 10:00
Nope. Tried all mentioned methods but issue has not resolved yet. I am using two different ESP-8266 modules with two different power supplies, one for driving relays and other for button interrupts.

**Comment by igrr** [comment] 2016-02-29 10:20
Okay, please post the code which demonstrates the issue, so we can reproduce and fix it.

**Comment by vickeyhort** [comment] 2016-03-01 14:15
`                                                            /*
* Arduino code by Waqas Ahmed
* Follow the instruction given below
* Don't make changes in prohibted area

_________________Prohibted Area Start_______________________
                                                            */
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include <ESP8266httpUpdate.h>
#include <ESP8266HTTPClient.h>
#include <ArduinoJson.h>
#include "FS.h"

                                                            /*
_________________Prohibted Area Ended_______________________
It's user library attachment area!
It's user variable declaration area!
Area below can be editted:                                  */

const char* SKETCH_ID = "test";  //Non-overlaping name of sketch
const char* SKETCH_VERSION = "0.5"; // Sketch version
const char* MQTT_PUBLISH_TOPIC = "test-out"; // topic name to publish on mqtt
const char* MQTT_SUBSCRIBE_TOPIC = "test-in"; // topic to subscribe at mqtt for message reception

int NUMBER_OF_GPIOS = 2;  //Number of gpio's to be set as output
int NUMBER_OF_CUSTOM_VARIABLES = 6; //Number of custom variables defined
byte gpio[] = {13, 12}; //LED, Saver pin respectively
int on_state = 1;
int off_state = 0;

int GPIO_DEFAULT_STATE = off_state;
byte gpio_state[20];
byte custom_variable[20];

int led_pin = 13;
int saver_pin  = 12;
int door_pin = 14;
int pir_pin = 3;
int light_button_pin = 5;
int pump_button_pin = 4;

unsigned char* doorInterrupt = &custom_variable[0];
unsigned char* lightInterrupt = &custom_variable[1];
unsigned char* pumpInterrupt = &custom_variable[2];
unsigned char* electricity = &custom_variable[3];
unsigned char* sunset = &custom_variable[4];
unsigned char* activity = &custom_variable[5];

byte interrupt_pin[] = {5, 4}; //light, pump buttons repectively
int no_of_interrupts = 2;

boolean bounce = false; //Store bounce is active or not
long bounce_time = 0; //Time when bounce is activated

long activity_failsave = 0;
boolean door = false;
int door_check = 0;
int door_parked = 0;
long lastinterrupt = 0;

boolean lightsON = false;
long lightsON_time = 0;
boolean turnTheLights = false;
long last_pressed = 0;

boolean motion_sensed = false;
long motion_updated = 0;

float battery_correction = 0.10; //Add 0.10 to actuall reading
long battery_read = 0;
boolean pump_toggle = false;

boolean reed_test = false;

                                                             /*
-------------------------------------------------------------
  Interrupt Functions
-------------------------------------------------------------*/

void reedSwitch()
{
  bounce = true;
  bounce_time = millis();
  detachInterrupt(door_pin);
  door = true;
  door_check = 1;
  lastinterrupt = millis();
}

void lightSwitch()
{
  if ((millis() - last_pressed) > 5000) {
    last_pressed = millis();
    turnTheLights = true;
  }
}

void pumpSwitch()
{
  if ((millis() - last_pressed) > 5000) {
    last_pressed = millis();
    pump_toggle = true;
  }
}

void motionSwitch()
{
  motion_sensed = true;
}


typedef void (*functions) ();
functions interrupt [] =
 {
 lightSwitch,
 pumpSwitch,
 };

void setInterrupt(int pin, int pin_gpio, int state)
{
  if (state == 0) {
    detachInterrupt(pin_gpio);
    send("GPIO " + String(pin_gpio) + ": interrupt detached");
  } else {
    attachInterrupt(pin_gpio, *interrupt[pin], RISING);
    send("GPIO " + String(pin_gpio) + ": interrupt attached");
  }
  custom_variable[pin] = state;
  String ctvar = "customVariable" + String(pin);
  updateDb(ctvar, state);
}
                                                            /*
_________________Prohibted Area Start_______________________
                                                            */

const char* WIFI_SSID = "Ahmed";
const char* WIFI_PASSWORD = "mypassword";
const char* MQTT_SERVER = "192.168.0.30";
const char* MQTT_USER = "pi";
const char* MQTT_PASSWORD = "mypassword";

int wifi_reconnect_tries = 0;
int mqtt_reconnect_tries = 0;
long wifi_reconnect_time = 0L;
long mqtt_reconnect_time = 0L;
long wifi_check_time = 15000L;
long status_sent = 0L;

WiFiClient espClient;
PubSubClient client(espClient);

boolean readDb()
{
  File databaseFile = SPIFFS.open("/config.json", "r");
  if (!databaseFile) {
    Serial.println("Failed to open database file");
    return false;
  }
  size_t size = databaseFile.size();
  if (size > 1024) {
    Serial.println("database file size is too large");
    return false;
  }
  std::unique_ptr<char[]> buf(new char[size]);
  databaseFile.readBytes(buf.get(), size);
  
  StaticJsonBuffer<500> jsonBuffer;
  JsonObject& database = jsonBuffer.parseObject(buf.get());
  if (!database.success()) {
    Serial.println("Failed to parse database file");
    return false;
  }
  boolean update_database = false;
  for (int i = 0; i < NUMBER_OF_GPIOS ; i++) {
    String gpioS = "gpio" + String(i);
    pinMode(gpio[i], OUTPUT);
    if (database.containsKey(gpioS)) {
      gpio_state[i] = database[gpioS];
      Serial.print("gpio[");
      Serial.print(gpio[i]);
      Serial.print("] = ");
      Serial.println(gpio_state[i]);
      if(!initgpio(gpio[i], gpio_state[i])) {
        gpio_state[i] = GPIO_DEFAULT_STATE;
        database[gpioS] = gpio_state[i];
        update_database = true;
        Serial.print("gpio[");
        Serial.print(gpio[i]);
        Serial.print("] = ");
        Serial.println(gpio_state[i]);
      }
    } else {
      gpio_state[i] = GPIO_DEFAULT_STATE;
      database[gpioS] = gpio_state[i];
      initgpio(gpio[i], gpio_state[i]);
      update_database = true;
      Serial.print("gpio[");
      Serial.print(gpio[i]);
      Serial.print("] = ");
      Serial.println(gpio_state[i]);
    }
  }
  for (int i = 0; i < NUMBER_OF_CUSTOM_VARIABLES; i++) {
    String cVar = "customVariable" + String(i);
    if (database.containsKey(cVar)) {
      custom_variable[i] = database[cVar];
      Serial.print("custom_variable[");
      Serial.print(i);
      Serial.print("] = ");
      Serial.println(custom_variable[i]);
    } else {
      database[cVar] = 99;
      update_database = true;
    }
  }
  if (update_database) {
    File databaseFile = SPIFFS.open("/config.json", "w");
    database.printTo(databaseFile);
    Serial.println("Failure was detected in parsing and default value wrote to failed entities");
    return true;
  }
  Serial.println("database parsed successfully");
  return true;
}

boolean writeDb()
{
  StaticJsonBuffer<500> jsonBuffer;
  JsonObject& database = jsonBuffer.createObject();
  for (int i = 0; i < NUMBER_OF_GPIOS; i++) {
    gpio_state[i] = GPIO_DEFAULT_STATE;
    String gpioS = "gpio" + String(i);
    database[gpioS] = gpio_state[i];
    initgpio(gpio[i], gpio_state[i]);
  }
  for (int i = 0; i < NUMBER_OF_CUSTOM_VARIABLES; i++) {
    String cVar = "customVariable" + String(i);
    database[cVar] = custom_variable[i];
  }
  File databaseFile = SPIFFS.open("/config.json", "w");
  if (!databaseFile) {
    Serial.println("Failed to open config file for writing");
    return false;
  }
  database.printTo(databaseFile);
  Serial.println("gpio default values wrote to database file");
  return true;
}

void updateDb(String entity, int state)
{
  File databaseFile = SPIFFS.open("/config.json", "r");
  size_t size = databaseFile.size();
  std::unique_ptr<char[]> buf(new char[size]);
  databaseFile.readBytes(buf.get(), size);
  StaticJsonBuffer<500> jsonBuffer;
  JsonObject& database = jsonBuffer.parseObject(buf.get());
  if (database[entity] != state) {
    database[entity] = state;
    File databaseFile = SPIFFS.open("/config.json", "w");
    database.printTo(databaseFile);
    Serial.print(state);
    Serial.println(" status updated to database against ");
    Serial.println(entity);
  }
}

void gpioDrive(int pin, int state)
{
  Serial.print("gpioDrive command: pin = ");
  Serial.print(pin);
  Serial.println(" state = ");
  Serial.println(state);
  if((state == 0) || (state == 1)) {
    String db = "gpio" + String(pin);
    int gpio_pin = gpio[pin];
    if (digitalRead(gpio_pin) != state) {
      digitalWrite(gpio_pin, state);
      int pin_number = db.toInt();
      gpio_state[pin_number] = state;
      String gpioS = "gpio" + String(pin);
      if (state == off_state) {
        send("gpio-" + String(pin) + "-Off");
      } else {
        send("gpio-" + String(pin) + "-On");
      }
      updateDb(db, state);
    } else {
      Serial.print("gpio ");
      Serial.print(pin);
      Serial.print("is already set to ");
      Serial.println(state);
      send("gpio" + String(pin) + " is already set to " + String(state));
    }
  } else {
    Serial.print(state);
    Serial.print(" is not a valid state for gpio ");
    Serial.println(pin);
    send(String(state) + " is not a valid state for gpio: " + String(pin));
  }
}

boolean initgpio(int pin, int state)
{
  if((state == 0) || (state == 1)) {
    digitalWrite(pin, state);
    return true;
  } else {
    digitalWrite(pin, GPIO_DEFAULT_STATE);
    Serial.println("invalid gpio state");
    return false;
  }
}

void wifi()
{

  ++ wifi_reconnect_tries;
  if (mqtt_reconnect_tries != 0) {
    mqtt_reconnect_tries = 0;
  }
  boolean networkScan = false;
  int n = WiFi.scanNetworks();
  delay(300);
  for (int i = 0; i < n; ++i) {

    if (WiFi.SSID(i) == WIFI_SSID) {
      Serial.print(WIFI_SSID);
      Serial.print(" is available");
      Serial.println("");
      networkScan = true;
      break;
    }
  }
  if(networkScan) {
    if (wifi_reconnect_tries > 1) {
      Serial.print("Retrying:: ");
    }
    Serial.print("Connecting to ");
    Serial.print(WIFI_SSID);
    Serial.println("");
    long wifi_initiate = millis();
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    while (WiFi.status() != WL_CONNECTED) {
      Serial.print(".");
      if (WiFi.status() == WL_CONNECTED) {
        break;
      }
      if ((millis() - wifi_initiate) > 15000L) {
        break;
      }
      delay(500);
    }
    if (WiFi.status() == WL_CONNECTED) {
      Serial.print(" Connected!!");
      Serial.println("");
      Serial.println(WiFi.localIP());
      wifi_reconnect_tries = 0;
    } else if ((WiFi.status() != WL_CONNECTED) && (wifi_reconnect_tries > 3)) {
      Serial.print(" Failed to connect to ");
      Serial.print(WIFI_SSID);
      Serial.println("");
      Serial.println("Rebooting...");
      delay(1000);
      digitalWrite(16, LOW);
    }
  } else {
    Serial.print(WIFI_SSID);
    Serial.print(" is offline");
    Serial.println("");
    if (wifi_reconnect_tries > 3) {
      wifi_check_time = 300000L;
      wifi_reconnect_tries = 0;
      Serial.println("System will try again after 5 minutes");
    }
  }
}

void mqtt()
{
  if (mqtt_reconnect_tries > 1) {
    Serial.print("Retrying:: ");
  }
  Serial.print("Connecting to mqtt server: ");
  Serial.println(MQTT_SERVER);
  client.connect(SKETCH_ID, MQTT_USER, MQTT_PASSWORD);
  delay(500);
  if (client.connected()) {
    client.publish(MQTT_PUBLISH_TOPIC, "system bootup"); // Initial system status publish to server
    client.subscribe(MQTT_SUBSCRIBE_TOPIC); // Subscribe to your MQTT topic
    Serial.println(".. Connected!!");
    mqtt_reconnect_tries = 0;
  } else {

    Serial.print("Failed to connect to mqtt server, rc=");
    Serial.print(client.state());
    Serial.println("");
  }
}

                                                            /*
_________________Prohibted Area Ended_______________________
                                                            */

void setup() {
  pinMode(pir_pin, INPUT);
  attachInterrupt(pir_pin, motionSwitch, HIGH);
  pinMode(door_pin, INPUT);
  attachInterrupt(door_pin, reedSwitch, RISING);
  
  //Set pin mode and Attach interrupts
  for (int i=0; i<no_of_interrupts; i++) { //Change i<3 to i<4 to use motion sensor interrupt
    pinMode(interrupt_pin[i], INPUT);
    setInterrupt(i, interrupt_pin[i], custom_variable[i]);
  }
  // Set LightsON variable to current state, whether any light is on or not
  boolean saver_state = digitalRead(saver_pin) == 0;
  boolean led_state = digitalRead(led_pin) == 0;
  if ((!saver_state) && (!led_state)) {
    lightsON = false;
  } else {
    lightsON = true;
  }  

                                                            /*
_________________Prohibted Area Start_______________________
                                                            */
  pinMode(16, OUTPUT);
  digitalWrite(16, HIGH);
//  Serial.begin(115200);
  Serial.begin(115200, SERIAL_8N1,SERIAL_TX_ONLY);
  SPIFFS.begin();
  Serial.println("System started");
  if(!readDb()) {
    if(!writeDb()) {
      Serial.println("Problem generating database file");
      Serial.println("Formating file system");
      if(SPIFFS.format()) {
        Serial.println("Succeeded in formating file system");
        writeDb();
      }
    }
  }
  client.setServer(MQTT_SERVER, 1883);
  client.setCallback(callback);
  wifi();
}

void callback(char* topic, byte* payload, unsigned int length)
{
  String message = String();
  for (int i = 0; i < length; i++) {
    char input_char = (char)payload[i];
    message += input_char;
  }
  Serial.print("mqtt message received (");
  Serial.print(message);
  Serial.println(")");
  int message_length = message.length();

  if (message == "update") { // When we receive ota notification from MQTT, start the update
    update();
  } else if (message == "reboot") {
    reboot();
  } else if (message == "format") {
    format();
  } else if (message == "info") {
    String ip_address = ipToString(WiFi.localIP());
    String firmware = String(SKETCH_ID) + "_" + String(SKETCH_VERSION) + ".cpp.bin";
    send(firmware + "@ " + ip_address);
  } else if ((strstr(message.c_str(), "gpio")) && (message_length == 8)) {
    int oneIndex = message.indexOf('-');
    int secondIndex = message.indexOf('-', oneIndex+1);
    String gpio_pin = message.substring(oneIndex+1, secondIndex);
    String gpio_state = message.substring(secondIndex+1);
    int gpio_pin_int = gpio_pin.toInt();
    int gpio_state_int = gpio_state.toInt();
    gpioDrive(gpio_pin_int, gpio_state_int);
  } else if (strstr(message.c_str(), "set")) {
    int oneIndex = message.indexOf('-');
    int secondIndex = message.indexOf('-', oneIndex+1);
    String setter = message.substring(oneIndex+1, secondIndex);
    String value = message.substring(secondIndex+1);
    int setter_int = setter.toInt();
    int value_int = value.toInt();
    set(setter_int, value_int);
  } else if (strstr(message.c_str(), "get")) {
    int oneIndex = message.indexOf('-');
    int secondIndex = message.indexOf('-', oneIndex+1);
    String job = message.substring(oneIndex+1, secondIndex);
    String entity = message.substring(secondIndex+1);
    int entity_int = entity.toInt();
    get(job, entity_int);
  } else if (strstr(message.c_str(), "electricity")) {
    int oneIndex = message.indexOf('-');
    String electricity_status = message.substring(oneIndex+1);
    int electricity_status_int = electricity_status.toInt();
    custom_variable[3] = electricity_status_int;
    updateDb("customVariable3", electricity_status_int);
    send("electricity is set to " + String(electricity_status_int));
  } else if (strstr(message.c_str(), "night")) {
    int oneIndex = message.indexOf('-');
    String sunset_status = message.substring(oneIndex+1);
    int sunset_status_int = sunset_status.toInt();
    custom_variable[4] = sunset_status_int;
    updateDb("customVariable4", sunset_status_int);
    send("sunset status [" + String(sunset_status_int) + "] updated to system");
  } else if (strstr(message.c_str(), "interrupt")) {
    int oneIndex = message.indexOf('-');
    int secondIndex = message.indexOf('-', oneIndex+1);
    String interrupt_pin_str = message.substring(oneIndex+1, secondIndex);
    String interrupt_status_str = message.substring(secondIndex+1);
    int interrupt_pin_int = interrupt_pin_str.toInt();
    int interrupt_status_int = interrupt_status_str.toInt();
    setInterrupt(interrupt_pin_int, interrupt_pin[interrupt_pin_int], interrupt_status_int);
  } else if (strstr(message.c_str(), "light")) {
    turnTheLights = true;    
  }
                                                            /*
_________________Prohibted Area Ended_______________________
It's user mqtt message receive area!
Area below can be editted:                                  */

  
  else {
    send("command undefined");
  }
                                                            /*
_________________Prohibted Area Start_______________________
                                                            */
}

void loop()
{
  client.loop();
  if((WiFi.status() != WL_CONNECTED) && ((millis() - wifi_reconnect_time) > wifi_check_time)) {
      wifi_check_time = 15000L;
      wifi_reconnect_time = millis();
      wifi();
    }
  if ((WiFi.status() == WL_CONNECTED) && (!client.connected()) && ((millis() - mqtt_reconnect_time) > 5000L)) {
      mqtt_reconnect_time = millis();
      ++ mqtt_reconnect_tries;
      mqtt();
      if ((mqtt_reconnect_tries > 5) && (!client.connected())) {
        Serial.println("Rebooting");
        delay(1000);
        digitalWrite(16, LOW);
      }
    }
  if ((millis() - status_sent) > 600000) {
    status_sent = millis();
    send("online since: " + String(millis()));
  }
                                                            /*
_________________Prohibted Area Ended_______________________
It's user loop area!
Area below can be editted:                                  */
  debounce();
  bathroomStatus();
  doorParked();
  failsave();
  lights();
  battery();
  powersaver();
  motion();
  pump();
  delay(1);
}

void debounce()
{
  if (((millis() - bounce_time) > 5000) && (bounce)) {
    bounce = false;
    attachInterrupt(door_pin, reedSwitch, RISING);
  }
}

void doorParked()
{
  if ((door_check == 1) && ((millis() - lastinterrupt) > 6000)) {
    int door_status = digitalRead(door_pin);
    if (door_status == 1) {
      door_parked = 1;
    }
    door_check = 0;
  }
}

void bathroomStatus()
{
  if (door) {
    door = false;
    if ((*activity == 0) && (door_parked == 0)) {
      if (*sunset == 1) {
        turnTheLights = true;
      }
      send("BathStatus-Busy"); //Update status at server
      custom_variable[5] = 1; //Update activity variable value
      updateDb("customVariable5", 1); //Update activity variable value in database
    } else if ((*activity == 1) && (door_parked == 0)) {
      send("BathStatus-Free"); //Update status at server
      if (lightsON) {
        delay(5000);
        turnTheLights = true;
      }
      custom_variable[5] = 0; //Update activity variable value
      updateDb("customVariable5", 0);  //Update activity variable value in database
    } else {
      door_parked = 0;
    }
  }
}

void lights()
{
  if (turnTheLights) {
    turnTheLights = false;
    if (*electricity == 0) {
      boolean pin_state = digitalRead(led_pin) == off_state;      
      if (pin_state) {
        gpioDrive(0, on_state); //turn on LED
        lightsON = true;
        lightsON_time = millis();
      } else {
        gpioDrive(0, off_state); // turn off LED
        lightsON = false;
      }
    } else {
      boolean pin_state = digitalRead(saver_pin) == off_state;
      if (pin_state) {
        gpioDrive(1, on_state); //turn on Saver
        lightsON = true;
        lightsON_time = millis();
      } else {
        gpioDrive(1, off_state); //turn off Saver
        lightsON = false;
      }
    }
  }
}

void failsave()
{
  if ((lightsON) && ((millis() - activity_failsave) > 500)) {
    activity_failsave = millis();
    boolean led_was_on = (digitalRead(led_pin) == on_state);
    boolean saver_was_on = (digitalRead(saver_pin) == on_state);
    if ((!led_was_on) && (!saver_was_on)) { //if both of lights are OFF
      lightsON = false;
    } else { //If any of two lights is ON
      if ((*electricity == 0) && (!led_was_on)) {
        gpioDrive(0, on_state); //turn led ON
        delay(10);
        gpioDrive(1, off_state); //turn saver OFF
        
      } else if ((*electricity == 1) && (!saver_was_on)) {
        gpioDrive(1, on_state); //turn saver ON
        delay(10);
        gpioDrive(0, off_state); //turn led OFF
      }
    }
  }
}

void battery()
{
  if ((millis() - battery_read) > 60000) { //every 10 minutes = 600000 milli seconds
    battery_read = millis();
    float batt = 0;
    int rounds = 0;
    while((millis() - battery_read) < 1000) {
      float reading = analogRead(A0);
      float calculation = ((reading * (((1.0 * (1000000+46600))/47000)/1023)) + batt);
      batt = calculation;
      ++rounds;
    }
    
//  float batt_mean = ((batt / 20) - 0.37); //average and calibration
    float batt_mean = (batt / rounds); //average and calibration
    Serial.print("Battery status: ");
    Serial.print(batt_mean);
    Serial.print(" volts");
    Serial.println();
    send(String(batt_mean) + " volts");
  }
}

void powersaver()
{
  if (((millis() - lightsON_time) > 7200000) && (lightsON)) { //If any of light remains ON for two hours = 7200000 milli seconds
    turnTheLights = true;
  }
}

void motion()
{
  if (motion_sensed) {
    motion_sensed = false;
    if ((millis() - motion_updated) > 1000) {
      motion_updated = millis();
      send("motion sensed");
    }
  }
}

void pump()
{
  if (pump_toggle) {
    pump_toggle = false;
    send("pump-toggle");
  }
}


                                                            /*
_________________Prohibted Area Start_______________________
                                                            */


void update()
{
  Serial.println("starting system update");
  client.publish(MQTT_PUBLISH_TOPIC, "starting system update", true);
  send("current sketch: " + String(SKETCH_ID) + "_" + String(SKETCH_VERSION) + ".cpp.bin");
  String link = "/";
  link += String(SKETCH_ID) + "_" + String(SKETCH_VERSION) + ".cpp.bin";
  ESPhttpUpdate.update(MQTT_SERVER, 80, link);
}

void reboot()
{
  Serial.println("rebooting system");
  send("rebooting system");
  digitalWrite(16, LOW);
}

void format()
{
  Serial.println("initiating SPIFF file system format");
  send("initiating SPIFF file system format");
  if(SPIFFS.format()) {
    Serial.println("Succeeded to format file system");
    send("SPIFF file system format completed");
  }
}

int get(String job, int entity)
{
  if (job == "gpio") {
    int read_state = digitalRead(gpio[entity]);
    send("gpio[" + String(entity) + "] is set to " + String(read_state));
  } else if (job == "var") {
    send("custom_variable[" + String(entity) + "] is set to " + String(custom_variable[entity]));
  }
}

int set(int var, int val)
{
  custom_variable[var] = val;
  String cVar = "customVariable" + String(var);
  updateDb(cVar, val);
  send("custom_variable[" + String(var) + "] is set to " + String(val));
}

boolean send(String message)
{
  client.publish(MQTT_PUBLISH_TOPIC, message.c_str(), true);
}

boolean send(const char* topic, String message)
{
  client.publish(topic, message.c_str(), true);
}

String ipToString(IPAddress ip){
  String s="";
  for (int i=0; i<4; i++)
    s += i  ? "." + String(ip[i]) : String(ip[i]);
  return s;
}

                                                            /*
_________________Prohibted Area Ended_______________________
                                                            */`

**Comment by sundeep110** [comment] 2017-01-19 17:25
Hi HobbytronicsPK, 
I am facing exactly the same issue, i was interested in the software solution you proposed. However, by a glance at the code and your description above, I could see that we are assuming that only after 400ms the rising pin (5 in this case) is changing to high. 
However, for me this is not the case, the interrupt is raised immediately and pin changes its state immediately, I am interested if this software solution worked for you. Or please suggest if any other hardware or software solution worked for you.
Thanks in advance.

**Comment by HobbytronicsPK** [comment] 2017-01-19 17:45
I have tried number of solutions but I faced problems using interrupt. As
ESP8266 is very sensitive to EMI.

In my case, I used interrupts for toggle buttons and experienced issues. So
I just switched it towards reading pin's state in loop and perform
functions accordingly. Being ESP8266 much fast, It worked for me at least
better than those false triggers occurred while using interrupts.

--
Your's own,
HobbyTronics Pakistan,
Mochiwali, Kahror Pakka, 59340,
Punjab, Islamic Republic of Pakistan.
whatsapp: +92-300-732-1041
www.hobbytronics.com.pk

On Jan 19, 2017 10:25 PM, "sundeep110" <notifications@github.com> wrote:

Hi HobbytronicsPK,
I am facing exactly the same issue, i was interested in the software
solution you proposed. However, by a glance at the code and your
description above, I could see that we are assuming that only after 400ms
the rising pin (5 in this case) is changing to high.
However, for me this is not the case, the interrupt is raised immediately
and pin changes its state immediately, I am interested if this software
solution worked for you. Or please suggest if any other hardware or
software solution worked for you.
Thanks in advance.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/esp8266/Arduino/issues/1372#issuecomment-273840927>,
or mute
the thread

**Comment by vicnevicne** [comment] 2017-01-19 19:56
@HobbytronicsPK What cabling (length and type of cable) do you have between the ESP and the switches ? If it is long and wires are close to each other, capacitive coupling between them causes very short peaks on the wires adjacent to the one of the pressed button, which are sufficient to trigger interrupts.
If you want to rule this out, can you place the buttons right next to the ESP ?

**Comment by HobbytronicsPK** [comment] 2017-01-20 03:48
I also tried your method by placing reed switch 8 feet apart. If both sides
of reed switch are close to each other then interrupt works fine by adding
above mentioned software solution.

However, same false trigger experiences if reed switch is kept under opened
state.

As far as type of cable is concerned, I also tried variety of cables and
all exhibited same results.

Even SSR relay also triggered false interrupt on turning load on or off
(Heavy load such as Water Pump).

All this EMI comes from AC source used as power supply to feed ESP8266. Try
feeding ESP8266 from battery being charged by solar charger etc.  may solve
this problem which I have not tried yet.

Just try reading input pin continously in loop (in place of interrupt
driven) You will get promising results.

--
Your's own,
HobbyTronics Pakistan,
Mochiwali, Kahror Pakka, 59340,
Punjab, Islamic Republic of Pakistan.
whatsapp: +92-300-732-1041
www.hobbytronics.com.pk

**Comment by duncan-a** [comment] 2017-01-20 21:46
What value are the pullup/pulldown resistors on the inputs? Sounds like
something may be floating...

**Comment by HobbytronicsPK** [comment] 2017-01-21 03:45
10K Pullup resistors

--
Your's own,
HobbyTronics Pakistan,
Mochiwali, Kahror Pakka, 59340,
Punjab, Islamic Republic of Pakistan.
whatsapp: +92-300-732-1041
www.hobbytronics.com.pk

**Comment by vicnevicne** [comment] 2017-01-21 09:33
I share Links2004 opinion that RC filtering is the most efficient way to solve the issue in hardware (for switch bounce, external EMI and crosstalk between lines altogether). My own experience (reed switches up to 10m away from my RPi-based alarm system) has shown that aggressive filtering was required to avoid spurious interrupts. I ended up with [this](https://www.screencast.com/t/SKcFP2mnud) and never got any issue since then...
Now software filtering is a valid option of course but unless that's the only task your ESP has to do, using a timer instead of a code called by interrupt might prove much more efficient (if you have bounces, the interrupt might be called tens of times in a row). To make sure it's not a resource hog, I suggest you temporarily add a counter incremented at the start of the interrupt. and print its value regularly.
For a detailed list of solutions, both hardware and software, see [this page](http://www.ganssle.com/debouncing-pt2.htm) (it's focused on debounce, but the symptoms are mostly the same).

**Comment by ksundeep** [comment] 2017-01-21 13:24
@HobbytronicsPK I am also using loop way instead of interrupts, thanks for the suggestion.

**Comment by HobbytronicsPK** [comment] 2017-01-21 13:27
No doubt, Interrupts are more efficient and filters do work but It always
causes trouble especially in case of using ESP8266 in environment with high
EMI. Good luck @ksundeep.

*W*aqas *A*hmed
00923007321041
*Malik Agriculture Farms*
*Mochiwali village, Wigha-mal road*
*Kahror Pakka, District Lodhran, Punjab*
*Islamic republic of Pakistan*

**Comment by penfold42** [comment] 2017-01-21 23:15
An optocoupler on the input might help too.

Long wires on relatively high impedence inputs would make a great antenna.

**Comment by HobbytronicsPK** [comment] 2017-01-22 05:21
As far as, I have investigated the issue, EMI was coming from power source
used to power up ESP8266.

Using filtering capacitors at power source ranging from 22uF to above 400uF
did not even solved my problem.

--
Your's own,
HobbyTronics Pakistan,
Mochiwali, Kahror Pakka, 59340,
Punjab, Islamic Republic of Pakistan.
whatsapp: +92-300-732-1041
www.hobbytronics.com.pk

**Comment by devyte** [comment] 2017-10-19 05:30
Closing per #3655 .

**Closed by devyte** 2017-10-19 05:30 UTC
Labels: type: troubleshooting
