### ISSUE TITLE
If WiFi.softAP() after WiFi connected, then Blynk can't work.

### ISSUE THREAD

**Issue by bestpika** [esp8266/Arduino#3884] opened 2017-11-27 09:33 UTC
#### Hardware

Hardware: `WeMos D1 mini`
Core Version: 7b09ae5f69f8dccb5152d128c8484ec9a18adb11
Blynk Version: https://github.com/blynkkk/blynk-library/commit/dd7fe1f6d135ec671f5632c5d7cb366d246344c2

### Description

If WiFi.softAP() after WiFi connected, then Blynk can't work.
But 5c01841430d5f93d5334c56f3b708995912a8675 is okay.

### Sketch

Not work

```cpp
#define BLYNK_PRINT Serial

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

void setup()
{
  Serial.begin(115200);
  Serial.println();
  WiFi.mode(WIFI_AP_STA);
  WiFi.begin("STA ssid", "STA passphrase");

  int wait = 0;
  while (!WiFi.isConnected() && wait++ < 10) {
    Serial.print(".");
    delay(1000);
  }
  WiFi.softAP("AP ssid", "AP passphrase");

  Blynk.config("Blynk Token", "blynk-cloud.com");
  Blynk.connect();
}

void loop()
{
  Blynk.run();
}
```

Serial

```txt
[10495]
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.4.10 on Arduino

[10499] Connecting to blynk-cloud.com:8442
[15500] Connecting to blynk-cloud.com:8442
[20501] Connecting to blynk-cloud.com:8442
```

Work

```cpp
#define BLYNK_PRINT Serial

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

void setup()
{
  Serial.begin(115200);
  Serial.println();
  WiFi.mode(WIFI_AP_STA);
  WiFi.begin("STA ssid", "STA passphrase");

  WiFi.softAP("AP ssid", "AP passphrase");
  int wait = 0;
  while (!WiFi.isConnected() && wait++ < 10) {
    Serial.print(".");
    delay(1000);
  }

  Blynk.config("Blynk Token", "blynk-cloud.com");
  Blynk.connect();
}

void loop()
{
  Blynk.run();
}
```

Serial

```txt
[8525]
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.4.10 on Arduino

[8527] Connecting to blynk-cloud.com:8442
[8695] Ready (ping: 77ms).
```

### Debug Messages

```
wifi evt: 2
wifi evt: 0
wifi evt: 3

[9634] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.4.10 on Arduino

[9635] Connecting to blynk-cloud.com:8442
[hostByName] request IP for: blynk-cloud.com
[hostByName] Host: blynk-cloud.com IP: 188.166.206.43
wifi evt: 7
wifi evt: 7
[14636] Connecting to blynk-cloud.com:8442
[hostByName] request IP for: blynk-cloud.com
[hostByName] Host: blynk-cloud.com IP: 188.166.206.43
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
[19637] Connecting to blynk-cloud.com:8442
[hostByName] request IP for: blynk-cloud.com
[hostByName] Host: blynk-cloud.com IP: 188.166.206.43
wifi evt: 7
wifi evt: 7
[24638] Connecting to blynk-cloud.com:8442
[hostByName] request IP for: blynk-cloud.com
[hostByName] Host: blynk-cloud.com IP: 188.166.206.43
wifi evt: 7
```

**Comment by d-a-v** [comment] 2017-11-27 09:53
Can you retry with core version 7b09ae5 (latest master) and with lwip-v1.4 instead of v2 in menus ?

**Comment by bestpika** [comment] 2017-11-27 10:05
@d-a-v I can't find lwip-v1.4
![image](https://user-images.githubusercontent.com/5698157/33261388-9a26943c-d39d-11e7-8629-72829586b8c1.png)

**Comment by bestpika** [comment] 2017-11-27 10:09
I try `Prebuilt Source (gcc)`, then it work.
![image](https://user-images.githubusercontent.com/5698157/33261546-0b257720-d39e-11e7-9589-31d67026989b.png)

```txt
wifi evt: 2
wifi evt: 0
wifi evt: 3

[9869] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.4.10 on Arduino

[9871] Connecting to blynk-cloud.com:8442
[hostByName] request IP for: blynk-cloud.com
[hostByName] Host: blynk-cloud.com IP: 188.166.206.43
[10050] Ready (ping: 75ms).
wifi evt: 7
wifi evt: 7
wifi evt: 7
```

**Comment by d-a-v** [comment] 2017-11-27 10:10
> ![image](https://user-images.githubusercontent.com/5698157/33261388-9a26943c-d39d-11e7-8629-72829586b8c1.png)

There is v2, and the others which all are v1.4.
Try the first one (Prebuilt), it was the default before v2 appeared.

**Comment by d-a-v** [comment] 2017-11-27 10:11
So lwip-v2 is the cause. I'll work on it. Thanks for the report !

**Comment by bestpika** [comment] 2017-11-27 10:13
Thank you.

**Comment by d-a-v** [comment] 2017-11-27 10:57
I can't reproduce it. It works with both sketch.
Can you remove your ```++wait<10``` test and re-check ?

**Comment by d-a-v** [comment] 2017-11-27 12:41
Apparently my softAP password was not long enough :]
I finally could reproduce the bug. I also added the simple web server in your sketch.
Oddly, with lwip2 + webserver and softAP after STA, blinky does not work but webserver works on both interfaces.

tcpdump shows the ARP request and answer for blynk-cloud.com resolving.

Now digging into Blynk lib...

**Comment by d-a-v** [comment] 2017-11-27 13:49
@bestpika Are you trying with exactly the sketches above ?
I could reproduce the bug only because I forgot to remove an ```ESP.eraseConfig()``` lost in my tryings.

Both your sketches are OK with lwip2 here.
I need more input, or someone else try.

It may be not related but I also noticed blink services takes 5 seconds more everytime I reset the ESP right after beeing connected (I guess it is a fair protection against buggy device).

**Comment by bestpika** [comment] 2017-11-27 15:02
I will try tomorrow.
By the way, I using Arduino IDE 1.8.5 and Windows 10 1703 x64.

**Comment by devyte** [comment] 2017-11-27 17:51
My quick test seems to agree with @d-a-v . 
Closing as can't reproduce.

**Closed by devyte** 2017-11-27 17:51 UTC

**Comment by bestpika** [comment] 2017-11-28 03:04
Today I try over 20 times.
Not work still not work.

**Comment by d-a-v** [comment] 2017-11-28 10:15
Are you using exactly the sketch above with your IDs ?

**Comment by bestpika** [comment] 2017-11-28 10:55
@d-a-v yes.

**Comment by d-a-v** [comment] 2017-11-28 14:20
@devyte I think this is an interesting issue with lwip-v1.4 working where lwip2 does not, so I think it is worth investigating a bit more.
@bestpika can you activate lwip2 log and retry ?
you need to:
```
cd tools/sdk/lwip2
make
```
edit ```builder/glue/gluedebug.h``` and change ```ULWIPDEBUG``` from 0 to 1, then
```
make install
```
In your sketch, add ```Serial.setDebugOutput(true);``` right after ```Serial.begin()```, then restart your failing sketch.
If you can post the console somewhere so we can check the IP traffic.
