### ISSUE TITLE
Erase saved WiFi access points

### ISSUE THREAD

**Issue by hieuv** [esp8266/Arduino#3066] opened 2017-03-21 08:23 UTC
I used `WiFiMulti` in the past to connect to different WiFi networks. Now I want to forget all of those WiFi configurations (the module keep trying to connect to a (now turned) bad AP).
I tried to follow #1494 and investigate these solutions:

`
  ESP.eraseConfig();
  *((int*)0) = 0;
`

`
  ESP.eraseConfig();
  ESP.reset();
`

Neither worked.

Do anyone know any better way to do this?

**Comment by tablatronix** [comment] 2017-03-26 16:04
in code or permanently ?
You can use the esptool to erase_flash entirely.

**Comment by hieuvt6-fti** [comment] 2017-03-27 03:06
Ah, yes. after a while I decided to erase flash and it turned out to be the solution.

But now I have two questions.

1. I read some GitHub issues and learned that WiFiMulti is not actually using the flash space reserved for storing WiFi credentials. If so, how is it storing WiFi credentials in a non-volatile way?

2. If I want to erase WiFiMulti's stored credentials during run time, what are my options?

**Comment by tablatronix** [comment] 2017-03-27 11:51
It stores the last successful ap but not all.
You can disable persistent to disaae autonsaving

**Comment by devyte** [comment] 2017-09-08 03:40
@hieuv did calling persistent(false) address your issue?

**Comment by hieuv** [comment] 2017-09-09 07:00
To be honest with you, this was so long ago that I do not remember any details anymore. I will see if I can reproduce the issue and see if the solution above fixes it.

**Comment by devyte** [comment] 2017-10-10 06:26
@hieuv were you able to reproduce the issue?

**Comment by barsznica** [comment] 2018-01-02 12:12
WiFi.disconect() worked for me first go.

ESP.eraseConfig then ESP.reset() OR  ESP.eraseConfig() then ESP.restart() did not work for me.
I did not try the `*((int*) 0) = 0;` thing.

The answer to this question was covered [here](url=https://github.com/tzapu/WiFiManager/issues/142) and [here](url=https://github.com/tzapu/WiFiManager/issues/142).

**Comment by devyte** [comment] 2018-02-28 15:09
Closing due to age and previous comment.

**Closed by devyte** 2018-02-28 15:09 UTC
Labels: waiting for feedback
