### ISSUE TITLE
Modemcu 0.9 espcomm error

### ISSUE THREAD

**Issue by petrd** [esp8266/Arduino#699] opened 2015-08-16 15:51 UTC
Hello,
in the new version 1.6.5-1044-g170995a not working properly espcomm. When you upload reports:
<pre><code>
warning: failed espcomm_sync

Error: failed espcomm_open
</code></pre>
On Modemcu 0.9 is required to hold the flash button for the correct upload. Modemcu 1.0 works flawlessly.

**Comment by igrr** [comment] 2015-08-16 16:35
Duplicate of #684

**Comment by petrd** [comment] 2015-08-16 21:21
I'm sorry I missed it.

**Closed** 2015-08-16 21:21 UTC
