### ISSUE TITLE
light sleep without beeing connected to a WLAN

### ISSUE THREAD

**Issue by Yoshi20** [esp8266/Arduino#557] opened 2015-07-15 15:29 UTC
I would like to configure my ESP8266 as an access point only in a specific state (of a state machine).
In the meantime I just set some GPIOs and wait (with delays).
The problem now is, that light sleep won't be activated unless the ESP8266 is connected to a WLAN (or was connected once -> it seems to save the ssid and the ssid-pw internaly!)

Just setting the sleep type (with "wifi_set_sleep_type(LIGHT_SLEEP_T)")
and changing the opmode to WIFI_STA doesn't seem to be sufficient.

Is there an other way to go into light sleep without beeing connected to a WLAN?
Are there other ways in the SW to reduce power consumption during the runtime?
##

**Comment by Humancell** [comment] 2015-12-01 23:37
Bump.

I'm looking for an example or more details on using "light sleep" in a sketch.  I'm not finding much in the docs or when I search ... any pointers that someone can provide?

I'll write things up when I get it figured out, but am looking for a good starting point on using it.

Thoughts?  Links?

**Comment by Yoshi20** [comment] 2016-02-11 15:52
It seems to be still not possible to enable the 'light sleep' when the ESP is not yet connected to a WLAN.
But #1381 seems to approach a solution for the problem.

**Comment by devyte** [comment] 2017-10-20 06:25
Duplicate of #1381. Closing this one.

**Closed by devyte** 2017-10-20 06:25 UTC
