### ISSUE TITLE
Ardunio ESP8226 could not open port(6)

### ISSUE THREAD

**Issue by Vikass8246** [esp8266/Arduino#8232] opened 2021-07-23 05:52 UTC
Arduino: 1.8.15 (Windows Store 1.8.49.0) (Windows 10), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

ICACHE : 32768           - flash instruction cache 

IROM   : 388144          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 28453   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 

DATA   : 1500  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 3448  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 26376 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 421545 bytes (40%) of program storage space. Maximum is 1044464 bytes.

Global variables use 31324 bytes (38%) of dynamic memory, leaving 50596 bytes for local variables. Maximum is 81920 bytes.

esptool.py v3.0

Serial port COM6

Traceback (most recent call last):

  File "C:\Users\Lenovo\OneDrive\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.1/tools/upload.py", line 66, in <module>

    esptool.main(cmdline)

  File "C:/Users/Lenovo/OneDrive/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 3551, in main

    esp = chip_class(each_port, initial_baud, args.trace)

  File "C:/Users/Lenovo/OneDrive/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 271, in __init__

    self._port = serial.serial_for_url(port)

  File "C:/Users/Lenovo/OneDrive/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.1/tools/pyserial\serial\__init__.py", line 90, in serial_for_url

    instance.open()

  File "C:/Users/Lenovo/OneDrive/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.1/tools/pyserial\serial\serialwin32.py", line 64, in open

    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))

serial.serialutil.SerialException: could not open port 'COM6': OSError(22, 'The semaphore timeout period has expired.', None, 121)

serial.serialutil.SerialException: could not open port 'COM6': OSError(22, 'The semaphore timeout period has expired.', None, 121)

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by earlephilhower** [comment] 2021-07-31 00:39
I've just gone and installed Arduino IDE 1.8.15 from the Windows Store on W10 and can confirm that, assuming the proper serial port driver is running and you can see the board in the Tools->Port menu, that it uploads just fine.

![image](https://user-images.githubusercontent.com/11875/127723284-efe45d98-989b-409d-93e5-dd504498d133.png)

Closing as can't reproduce with the info given.  Suggest checking cables, device driver, and *not* installing in OneDrive which is believed to break many things.

**Closed by earlephilhower** 2021-07-31 00:39 UTC
