### ISSUE TITLE
No or very bad WLAN connection to ESP8266

### ISSUE THREAD

**Issue by wkraft-fablabka** [esp8266/Arduino#6557] opened 2019-09-27 09:37 UTC
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:      		[ESP-12|Wemos D1 mini]
- Core Version:			[September 20th, 2019]
- Development Env:		[Arduino IDE 1.8.10]
- Operating System:		[Windows 7/10|Ubuntu|]

### Settings in IDE
 - not related to problem

### Problem Description
**No or very bad WLAN connection to ESP8266**
While flashing a bunch of Wemos D1 mini (with ESP12) i had the problem, that more than 50% (10 out of 18) of the flashed ESP8266 had network problems in AP mode.
Investigating the problem in detail shows, that this seems to be dependend on the chipset used on the client.
With an "Intel Wifi Link 5300" and a "Realtek RTL8188ETV" with Win7/Win10/Ubuntu 18.04 the client either can't see the SSID at all, or the WiFi connection can't be established or the connection always breaks.
Using an Atheros9271 everything is fine with all three tested operating systems. The client sees the SSID with a signal strength of -30db and better. Connection is stable.

In STA mode the tested devices had no problems to connect to all tested AP/routers.  

I could reduce the used sketch to this minimum sketch:
```cpp
#include <ESP8266WiFi.h>

void setup(void) {
  WiFi.mode(WIFI_AP);
  WiFi.softAP("mySSID", "password");
}

void loop(void) {
}
```
The problem seems related to several problems found while researching.  E.g. https://github.com/esp8266/Arduino/issues/2433
With one ESP failing, I also would have thrown it away, but now with 10 out of 18 having this problems I tried to nail that down. 

Any ideas, what to research next?

### Debug Messages
In thoses cases, where I can see the SSID and only WiFi connections are flaky, I receive the following log-messages :

```
add 1
aid 1
station: 00:21:6a:71:be:2e join, AID = 1
err already associed!
station: 00:21:6a:71:be:2e leave, AID = 1
rm 1
max connection!
max connection!
max connection!
max connection!
add 1
aid 1
station: 00:21:6a:71:be:2e join, AID = 1
err already associed!
station: 00:21:6a:71:be:2e leave, AID = 1
rm 1
max connection!
max connection!
max connection!
add 1
aid 1
station: 00:21:6a:71:be:2e join, AID = 1
err already associed!
station: 00:21:6a:71:be:2e leave, AID = 1
rm 1
max connection!
add 1
aid 1
station: 00:21:6a:71:be:2e join, AID = 1
err already associed!
station: 00:21:6a:71:be:2e leave, AID = 1
rm 1
max connection!
```

**Comment by devyte** [comment] 2019-10-01 23:58
@wkraft-fablabka compatibility issues like this are usually in the wifi stack, which is part of the Espressif SDK closed source libs, and not our core. As a result, in cases like this there isn't much we can do.
I suggest the following:
-Learn how to build a binary with the bare SDK (look at the bare SDK examples and read their docs)
-Reproduce the issue with that binary
-Test with both SDK 2.2.x (our core is built on this) and SDK 3.x (the newer branch)
-Report it at their repo [here](https://github.com/espressif/ESP8266_NONOS_SDK)
-Please report back here any progress, because if Espressif implements a fix, we'll need to update our SDK version

Closing for now.

**Closed by devyte** 2019-10-01 23:58 UTC
