### ISSUE TITLE
How to remove the handlers to reuse the server?

### ISSUE THREAD

**Issue by RazgrizX** [esp8266/Arduino#4402] opened 2018-02-20 12:52 UTC
Have spent few hours trying to close() the server to begin () it again with new handlers but nothing works. I am adding handlers with server.on() Here is part of my code:
ESP8266WebServer server(80);
void setup() {
server.on("/def", HTTP_GET, {
server.send ( 200, "text/plain", "DefStillHere");
});
server.on("/test", HTTP_GET, {
server.send ( 200, "text/plain", "StillAlive");
});
server.begin();
}
SetMode("CONFIG_MODE");
void SetMode(String MODE) {
//works?
delay(200);
if( MODE=="CONFIG_MODE"){
//set variables
StartAP();
SetEndpoints();
}
server.begin();
}
P.S. just want to remove the handlers, so I wont have to check if they should be available.

**Comment by devyte** [comment] 2018-02-20 14:03
@RazgrizX the handlers are set in the webserver object. Calling close() closes the server, it doesn't reset the webserver object, which means the handlers are still there.
Calling begin() restarts the server, and then the set handlers come into play.
Closing as intended behavior.

**Closed by devyte** 2018-02-20 14:03 UTC

**Comment by RazgrizX** [comment] 2018-02-21 15:03
Thanks, I get it. But isn't there a way to reset the server or recreate it with the same name?
