### ISSUE TITLE
WDT with callback registered with Waveforms

### ISSUE THREAD

**Issue by mcbp223** [esp8266/Arduino#5609] opened 2019-01-12 05:21 UTC
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12]
- Core Version:			[0fd86a0]
- Development Env:		[Arduino IDE]
- Operating System:		[Ubuntu]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[dio]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [921600] (serial upload only)

### Problem Description

I am trying to register an interrupt callback with the Waveforms framework, and I am getting WDT resets. In the example my callback is the only participating component in the time-sharing, no other waveform is requested. If you set USE_FRAMEWORK to false in the example, there is a manually implemented ISR that's spending time only managing this callback, and it doesn't give watchdog resets. In this example also I had to use a local _sigmaDeltaWrite()_ implementation, since _sigmaDeltaWrite()_ from _core_esp8266_sigma_delta.c_ is not decorated with ICACHE_RAM_ATTR.
Maybe there could be more optimizations possible inside _void timer1Interrupt()_ from _core_esp8266_waveform.c_, to make running registered callbacks less time constricted.
The example is a function generator that constructs an analog waveform using the ESP hardware ΣΔ DAC, at a sample rate given by an interrupt, NMI in this case. 

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp
#include <sigma_delta.h>
#include <core_esp8266_waveform.h>

constexpr bool USE_FRAMEWORK = true;

constexpr unsigned long SIGNAL_MIN_FREQUENCY = 1;
constexpr unsigned long SIGNAL_MAX_FREQUENCY = 24000;
constexpr uint8_t       SIGNAL_GPIO = 0; // D3 on NodeMCU
constexpr uint8_t       SIGNAL_CHANNEL = 0;

constexpr uint8_t       SIGMA_DELTA_PRESCALER = 10; // 80/10 = 8MHz, = 128 x 62500Hz

String   _waveType;
unsigned _samplesPerPeriod = 0;
unsigned _phaseOffset = 0; // used to smooth out frequency changes
unsigned _ampli = 127;

// variables used to manage timings for the test version of ISR
int _irqFreq = 48000;
int _irqTargetPeriod = 80000000/_irqFreq;
int _irqPause = 1000;
unsigned _last_cycle = 0;

static void setSignalFrequency(unsigned f) {
  unsigned cpufreq = ESP.getCpuFreqMHz() * 1000000;
  unsigned reqSamplesPerPeriod = cpufreq/f;

  if(_samplesPerPeriod > 0) {
    // keep the same phase angle, to smooth the transition
    unsigned cycle = ESP.getCycleCount();
    unsigned phase = (cycle + _phaseOffset) % _samplesPerPeriod;
    phase = uint64_t(1) * phase * reqSamplesPerPeriod / _samplesPerPeriod;
    _phaseOffset = phase - cycle;
  }

  _samplesPerPeriod = reqSamplesPerPeriod;
}

static inline void ICACHE_RAM_ATTR sigma_delta_test(bool enable, uint8_t target = 0, uint8_t prescale = 0) {
  constexpr int GPSDT =  0; // target, 8 bits
  constexpr int GPSDP =  8; // prescaler, 8 bits
  constexpr int GPSDE = 16; // enable

  ESP8266_REG(0x368) = (target << GPSDT) | (prescale << GPSDP) | ((enable ? 1 : 0) << GPSDE);
}

// Bhaskara I sine approximation
__attribute__((optimize("-O3"))) // no difference really
static inline int ICACHE_RAM_ATTR sine8(const unsigned period, unsigned phase, const unsigned ampli) {
  phase %= period; // slow
  const unsigned half = period/2;
  register unsigned x = (phase < half) ? phase : phase - half; // sample, < half

  x = 180 * x / half; // angle, max 180
  x = x * (180 - x); // max 8100
  x = ampli * 4 * x / (40500 - x);
  const int val = x;
  
  return (phase < half) ? val : -val;
}

uint32_t ICACHE_RAM_ATTR timer1Callback() {
  unsigned cycle = ESP.getCycleCount();
  unsigned phase = (cycle + _phaseOffset) % _samplesPerPeriod;
  unsigned first = _samplesPerPeriod/2;
  uint8_t DAC;
  
  char type = 0;
  if(_waveType.length())
    type = _waveType[0];

  switch(type) {
    case 'r': // ramp
      DAC = phase * (_ampli * 2 + 1) / _samplesPerPeriod;
      break;

    case 't': // triangle
      DAC = phase < first ? phase * (_ampli * 2 + 1) / first : (_ampli * 2 + 1) - (phase - first) * (_ampli * 2 + 1) / (_samplesPerPeriod - first);
      break;

    case 'q': // square
      DAC = phase < first ? _ampli * 2 + 1 : 0;
      break;

    case 'h': // half sine
      DAC = phase < first ? sine8(_samplesPerPeriod, phase, _ampli * 2 + 1) : 0;
      break;

    case 's': // sine
    default:
      DAC = 128 + sine8(_samplesPerPeriod, phase, _ampli);
      break;    
  }
  
  //sigmaDeltaWrite(SIGNAL_CHANNEL, DAC); // not decorated with ICACHE_RAM_ATTR
  sigma_delta_test(true, DAC, SIGMA_DELTA_PRESCALER);

  if(!USE_FRAMEWORK) {
    int measured = cycle - _last_cycle;
    _last_cycle = cycle;
  
    // adjust for irq frequency
    if(measured > _irqTargetPeriod) {
      if(_irqPause > 200)
        _irqPause --;
    } else if(measured < _irqTargetPeriod) {
      if(measured > 0)
        _irqPause ++;
    }
  }

  return 0; // ASAP
}

void ICACHE_RAM_ATTR fnTimer1_ISR_test() {
  if ((T1C & ((1 << TCAR) | (1 << TCIT))) == 0)
    TEIE &= ~TEIE1;//edge int disable
  T1I = 0;//9

  timer1Callback();

  //T1L = IRQ_PAUSE & 0x7FFFFF;//23
  T1L = _irqPause & 0x7FFFFF;//23
  if ((T1C & (1 << TCIT)) == 0)
    TEIE |= TEIE1; //edge int enable
}

void startTimer1_test() {
  _irqTargetPeriod = ESP.getCpuFreqMHz() * 1000000 / _irqFreq;
  
  timer1_disable();

  if(true) { // NMI
    ETS_FRC_TIMER1_INTR_ATTACH(NULL, NULL);
    ETS_FRC_TIMER1_NMI_INTR_ATTACH(fnTimer1_ISR_test);
  } else {
    timer1_attachInterrupt(fnTimer1_ISR_test);
    timer1_isr_init();
  }

  timer1_enable(TIM_DIV1, TIM_EDGE, TIM_SINGLE);
  timer1_write(1);
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  delay(100);
  Serial.println();
  Serial.println("Function generator example");
  Serial.println("You need an oscilloscope to see the signal");
  Serial.println("Type numbers for frequency");
  Serial.println("Type letters for signal type");
  Serial.println("\ts: sine");
  Serial.println("\tr: ramp");
  Serial.println("\tt: triangle");
  Serial.println("\tq: square");
  Serial.println("\th: half sine");

  setSignalFrequency(100);

  sigmaDeltaAttachPin(SIGNAL_GPIO, SIGNAL_CHANNEL);
  sigmaDeltaEnable();
  sigmaDeltaSetPrescaler(SIGMA_DELTA_PRESCALER);

  if(USE_FRAMEWORK)
    setTimer1Callback(timer1Callback);
  else
    startTimer1_test();
}

void loop() {
  // put your main code here, to run repeatedly:
  if(Serial.available()) {
    String s = Serial.readString();
    s.trim();
    if(s.length()) {
      if(isdigit(s[0])) {
        unsigned long f = s.toInt();
        if(SIGNAL_MIN_FREQUENCY <= f && f <= SIGNAL_MAX_FREQUENCY) {
          Serial.printf("frequency: %lu Hz", f); Serial.println();
          setSignalFrequency(f);
        } else {
          Serial.printf("%lu out of range", f); Serial.println();
        }
      } else {
        _waveType = s;
        Serial.print("type: "); Serial.println(_waveType);
      }
    }
  }
}
```

### Debug Messages

```

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v0fd86a07
~ld

```

**Comment by earlephilhower** [comment] 2019-01-12 07:02
There's an update just merged that redoes the waveform generator, you should try the GIT version for future tests.  That said, it won't help your existing code.

Your code fails even with `irqFreq=1000`, so it's completely unrelated to IRQ latency in the waveform generator.  Your code is never giving any app time in the platform codepath, while using the irqdelay bit in the ETS_* path.  It's IRQ'ing at much more than 48khz until the WDT kicks in

I'm not sure what you were trying to do, but you need to return the delay in core cycles your handler wants to get the next IRQ at so the tickless generator can take it into consideration (i.e. are there other waveforms with a sooner deadline that need to be handled).

What you've done now is always return 0, which gives no time ever to the main app code (well, the min counter we'll set is 7us, but irq enter and exit eat up a good portion of that if you always expect to a few clock cycles are guaranteed but it's not enough to make any real process in the loop or setup code if you always do it as this code does).

Also, at 48K IRQs/sec, and something like 3us/IRQ overhead just enter/exit the IRQ handler, that's ~30% of the total clocks available just in CPU and OS overhead to get to your 1st interrupt instruction.  You're also directly using a String in the IRQ and main code w/o protection, so you're gonna experience some interesting crashes when its state is not fully updated in the main code.

I2S and a delta-sigma SW DAC are way less CPU intensive to do what you're trying to do, I think.  The 8266 can decode and playback 44.1khz MP3s with enough CPU left over to stream over the internet since it's getting 1/100th or less interrupts that way.  Check ESP8266Audio for the I2SNoDAC implementation, it's very simple to do and gives a very good reproduction for being so straightforward.

A return value of something like `microsecondsToClockCycles(20)` would get you in the ballpark for 48khz if you're really intent on it, but you've got other issues and very little CPU to do anything else (wifi kicks in, you may die, unprotected object accesses, etc.)

**Closed by earlephilhower** 2019-01-12 07:02 UTC

**Comment by mcbp223** [comment] 2019-01-12 07:41
Thanks for the detailed explanation, I wasn't really sure what the return value represented when I gave 0.
I am currently using this implementation in the field, with 2.4.1, WiFi turned on and serving pages and json, at 40kHz NMI with no watchdog issues. Initially I have used I2SNoDAC, but for the range of frequencies I need, this manual procedure gives me more flexibility for landing closer to an exact frequency of the signal I am generating, and easier to generate parametric analogic waveforms.

**Comment by mcbp223** [comment] 2019-01-12 21:36
Hello, I have tested against GIT, and also per your suggestion stopped using String inside the ISR. I am also returning now a computed value from the callback, greater than zero. I still get WDT resets for sine wave since that function has one modulo and one division time consuming operations, but for the easier ones such as triangle is allright.

I have looked at the assembly of your code, and the macros that I have suspected of doing divisions are optimized by the compiler (microsecondsToClockCycles), everything looks neatly done.

I think that if you disable interrupts at the beginning of the ISR it's going to resolve many issues though, including mine. I have tested with 
```cpp
  if ((T1C & ((1 << TCAR) | (1 << TCIT))) == 0)
    TEIE &= ~TEIE1;//edge int disable
  T1I = 0;//9
```
and I have also added an _if_ before reenabling them at the end, with
```cpp
  if ((T1C & (1 << TCIT)) == 0)
    TEIE |= TEIE1; // Edge int enable
```
Do you know what the _if_ is for?
I had the ESP previously connected to WiFi, and it reconnects automatically even though I don't call it, so I think there were conflicts between wifi and this NMI when not disabling it at the beginning of ISR. Now it's all smooth, no more WDT restarts.
Would you please consider this change for a commit?
I am copy/pasting the corrected MCVE in it's entirety too, for testing.
Thanks!

```cpp
#include <sigma_delta.h>
#include <core_esp8266_waveform.h>

constexpr bool USE_FRAMEWORK = true;

constexpr unsigned long SIGNAL_MIN_FREQUENCY = 1;
constexpr unsigned long SIGNAL_MAX_FREQUENCY = 24000;
constexpr uint8_t       SIGNAL_GPIO = 0; // D3 on NodeMCU
constexpr uint8_t       SIGNAL_CHANNEL = 0;

constexpr uint8_t       SIGMA_DELTA_PRESCALER = 10; // 80/10 = 8MHz, = 128 x 62500Hz

char     _waveType = 't';
unsigned _samplesPerPeriod = 0;
unsigned _phaseOffset = 0; // used to smooth out frequency changes
unsigned _ampli = 127;

// variables used to manage ISR timings, trying to get keep close to the target sample rate
int _irqFreq = 48000;
int _irqTargetPeriod = 80000000/_irqFreq;
int _irqPause = 1000;
unsigned _last_cycle = 0;

static void setSignalFrequency(unsigned f) {
  unsigned cpufreq = ESP.getCpuFreqMHz() * 1000000;
  unsigned reqSamplesPerPeriod = cpufreq/f;

  if(_samplesPerPeriod > 0) {
    // keep the same phase angle, to smooth the transition
    unsigned cycle = ESP.getCycleCount();
    unsigned phase = (cycle + _phaseOffset) % _samplesPerPeriod;
    phase = uint64_t(1) * phase * reqSamplesPerPeriod / _samplesPerPeriod;
    _phaseOffset = phase - cycle;
  }

  _samplesPerPeriod = reqSamplesPerPeriod;
  
}

static inline void ICACHE_RAM_ATTR sigma_delta_test(bool enable, uint8_t target = 0, uint8_t prescale = 0) {
  constexpr int GPSDT =  0; // target, 8 bits
  constexpr int GPSDP =  8; // prescaler, 8 bits
  constexpr int GPSDE = 16; // enable

  ESP8266_REG(0x368) = (target << GPSDT) | (prescale << GPSDP) | ((enable ? 1 : 0) << GPSDE);
}

// Bhaskara I sine approximation
__attribute__((optimize("-O3"))) // no difference really
static inline int ICACHE_RAM_ATTR sine8(const unsigned period, unsigned phase, const unsigned ampli) {
  phase %= period; // slow
  const unsigned half = period/2;
  register unsigned x = (phase < half) ? phase : phase - half; // sample, < half

  x = 180 * x / half; // angle, max 180
  x = x * (180 - x); // max 8100
  x = ampli * 4 * x / (40500 - x);
  const int val = x;
  
  return (phase < half) ? val : -val;
}

uint32_t ICACHE_RAM_ATTR timer1Callback() {
  unsigned cycle = ESP.getCycleCount();
  unsigned phase = (cycle + _phaseOffset) % _samplesPerPeriod;
  unsigned first = _samplesPerPeriod/2;
  uint8_t DAC;
  
  switch(_waveType) {
    case 'r': // ramp
      DAC = phase * (_ampli * 2 + 1) / _samplesPerPeriod;
      break;

    case 't': // triangle
      DAC = phase < first ? phase * (_ampli * 2 + 1) / first : (_ampli * 2 + 1) - (phase - first) * (_ampli * 2 + 1) / (_samplesPerPeriod - first);
      break;

    case 'q': // square
      DAC = phase < first ? _ampli * 2 + 1 : 0;
      break;

    case 'h': // half sine
      DAC = phase < first ? sine8(_samplesPerPeriod, phase, _ampli * 2 + 1) : 0;
      break;

    case 's': // sine
    default:
      DAC = 128 + sine8(_samplesPerPeriod, phase, _ampli);
      break;    
  }
  
  //sigmaDeltaWrite(SIGNAL_CHANNEL, DAC); // not decorated with ICACHE_RAM_ATTR
  sigma_delta_test(true, DAC, SIGMA_DELTA_PRESCALER);

  int measured = cycle - _last_cycle;
  _last_cycle = cycle;

  // adjust for irq frequency
  if(measured > _irqTargetPeriod) {
    if(_irqPause > 200)
      _irqPause --;
  } else if(measured < _irqTargetPeriod) {
    if(measured > 0)
      _irqPause ++;
  }

  return _irqPause; // ASAP
}

void ICACHE_RAM_ATTR fnTimer1_ISR_test() {
  if ((T1C & ((1 << TCAR) | (1 << TCIT))) == 0)
    TEIE &= ~TEIE1;//edge int disable
  T1I = 0;//9

  timer1Callback();

  //T1L = IRQ_PAUSE & 0x7FFFFF;//23
  T1L = _irqPause & 0x7FFFFF;//23
  if ((T1C & (1 << TCIT)) == 0)
    TEIE |= TEIE1; //edge int enable
}

void startTimer1_test() {
  _irqTargetPeriod = ESP.getCpuFreqMHz() * 1000000 / _irqFreq;
  
  timer1_disable();

  if(true) { // NMI
    ETS_FRC_TIMER1_INTR_ATTACH(NULL, NULL);
    ETS_FRC_TIMER1_NMI_INTR_ATTACH(fnTimer1_ISR_test);
  } else {
    timer1_attachInterrupt(fnTimer1_ISR_test);
    timer1_isr_init();
  }

  timer1_enable(TIM_DIV1, TIM_EDGE, TIM_SINGLE);
  timer1_write(1);
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  delay(100);
  Serial.println();
  Serial.println("Function generator example");
  Serial.println("You need an oscilloscope to see the signal");
  Serial.println("Type numbers for frequency");
  Serial.println("Type letters for signal type");
  Serial.println("\ts: sine");
  Serial.println("\tr: ramp");
  Serial.println("\tt: triangle");
  Serial.println("\tq: square");
  Serial.println("\th: half sine");

  setSignalFrequency(100);

  sigmaDeltaAttachPin(SIGNAL_GPIO, SIGNAL_CHANNEL);
  sigmaDeltaEnable();
  sigmaDeltaSetPrescaler(SIGMA_DELTA_PRESCALER);

  if(USE_FRAMEWORK)
    setTimer1Callback(timer1Callback);
  else
    startTimer1_test();
}

void loop() {
  // put your main code here, to run repeatedly:
  if(Serial.available()) {
    String s = Serial.readString();
    s.trim();
    if(s.length()) {
      if(isdigit(s[0])) {
        unsigned long f = s.toInt();
        if(SIGNAL_MIN_FREQUENCY <= f && f <= SIGNAL_MAX_FREQUENCY) {
          Serial.printf("frequency: %lu Hz", f); Serial.println();
          setSignalFrequency(f);
        } else {
          Serial.printf("%lu out of range", f); Serial.println();
        }
      } else {
        _waveType = s[0];
        Serial.print("type: "); Serial.println(_waveType);
      }
    }
  }
}
```

**Comment by earlephilhower** [comment] 2019-01-13 03:03
Interesting observation, but I'm not sure I see it working.

The timer is in 1-shot mode (count to zero, fire interrupt, then do nothing), and the IRQ can only be called by that count hitting zero.  The countdown timer itself isn't reloaded until the very last line of code in the ISR (there is more code in the SDK that's hidden to save/restore the registers/etc.).  Therefore, there can't be any timer interrupts while actually in the NMI code (that we've written...set it too short and it'll re-interrupt during the OS restoring of registers/etc, possibly).

Therefore enabling or disabling edge interrupts from timer1 should be a complete no-op in the core code.  It's simply not possible to generate an IRQ until we reload.

Plus the fact that the code is now running at NMI level, which means nobody else can interrupt it anyway (even itself) unless the core code is doing something verrry weird (unlikely but definitely not impossible).

What may be happening is that you're consuming enough time in NMI IRQs that even regular IRQs are shut out and code can't advance, or those maskable interrupts themselves start to back up in a bad way and get into a loop.

You could try increasing the ` if (nextEventCycles < microsecondsToClockCycles(10)) { nextEventCycles = microsecondsToClockCycles(10); }` check/set to 12us.

But that would hurt PWM accuracy in the general case.  PWMs are guaranteed to only have a max of 16 IRQs/period (1ms or so normally) so a shorter delay is completely safe for them since there's an upper bound to IRQs.

Your setup doing 50k IRQs/sec is definitely not a usual use case, so I think you're going to be stuck with overriding the interrupts yourself.

**Comment by mcbp223** [comment] 2019-01-13 20:52
I cannot figure out why this is, from Xtensa ISA or from Expessif documentation for timer registers, either in Appendix 4 or anywhere else; can we ask @igrr about the details of TEIE handling that he used in _core_esp8266_timer.c_ ? Doing it like there certainly helped my test case.
As of the high rate of IRQs/sec, in the last MCVE I return a calculated value `_irqPause` until the next Interrupt requested, no less than 200 cycles. This function generator can live with a variable sample rate, since it gets the phase information from the current clock cycle in absolute terms, from which it calculates the phase angle relative to the requested signal period.

While polluting this closed thread, where can I ask you for another little addition to Waveforms? I am using another ΣΔ generator, this time software, since hardware there's only one in ESP8266, to drive a slower changing analog output, such as for LEDs but more exactly other outputs that can take advantage of the noise shaping particularities of ΣΔ, driven by the same NMI. The code is short, and looks something like this, maybe I will add it to the test case above.
```cpp
class AnalogToPulseModulator {
	double _min, _max, _val, _err = 0;
	uint8_t _pin;

	// constructor, etc...
	void onTick_SigmaDelta_1st_order() {
		double v = _val - _min;
	
		if(_err > v) {
			_err -= v;
			::digitalWrite(_pin, LOW);
		} else {
			_err += _max - _min - v;
			::digitalWrite(_pin, HIGH);
		}
	}
};
```
The above would need a relatively constant tick frequency I guess, since the integrating time between ticks is not taken into account when updating `_err`.
I have tried a 2nd order generator too, with no luck, someone with better math skills could help with that.

**Comment by earlephilhower** [comment] 2019-01-13 23:03
Howdy,

200 ESP cycles may not even be enough to get out of the IRQ return code.  Should code be in flash and not cached (your example would be cached since it's so small), I imagine main code wouldn't get more than a handful of cycles.  The 8266 is pretty neat, but it's not like an AVR and not really good at such high frequency, high workload ops.  Your specific single-purpose code might be able to run, but it's not going to be able to run a general app with tones/servos/etc., which is what the waveform consolidated (all the periodic functions now are compatible, whereas before you couldn't Tone() if you had an analogWrite or Servo).

If you really want it to run and can stand phase skew/etc, try increasing the min it returns to no less than cyclesToMicroseconds(15) and you may be able to run some apps (but WiFi is probably right out at that level).

For a SW delta-sigma, I'm not sure you can do it in SW w/o a dedicated shifter due to the high frequencies required for meaningful SNR.  IIRC after doing the math on the SW one I did for ESP8266Audio, with 16x oversampling of 44.1khz (i. e. an impossible 700khz IRQ rate if the shifting was done in SW) I got something like 8 or 9 bits.  This is something that really needs dedicated HW (SPI or I2S).

**Comment by mcbp223** [comment] 2019-01-14 22:08
Hello
You're right about my 200 cycles limit gross estimation.
I have taken measurements, with the pause requested until the next IRQ calculated in a feedback loop with `++/--`, as you can see in the example posted, for _irqPause.
The multitasking conditions are:
- 0.96" oled updated full of text, no faster than every 80ms
- json being served sporadically, it doesn't seem to affect the measurements
- serving a 40kB HTML does affect it, it goes lower, but doesn't seem to affect the signal produced, seen on the oscilloscope
- the same NMI drives a software ΣΔ modulator, like in the code shown in my last message
The NMI is with edge int disabled like in _core_esp8266_timer.c_.
The columns are CPU frequency, NMI target frequency, what calculations are done inside the function generator, and the last column is the calculated pause I until the next NMI requested. Shown on the OLED it varies wildly, but the first digit remains stable.

(CPU: 80MHz, NMI:10kHz, 1xramp): 6930 cycles
(CPU: 80MHz, NMI:20kHz, 1xramp): 2920 cycles
(CPU: 80MHz, NMI:30kHz, 1xramp): 1600 cycles
(CPU: 80MHz, NMI:40kHz, 1xramp):  920 cycles
(CPU: 80MHz, NMI:50kHz, 1xramp):  WDT

(CPU: 80MHz, NMI:10kHz, 1xsine): 6800 cycles
(CPU: 80MHz, NMI:20kHz, 1xsine): 2800 cycles
(CPU: 80MHz, NMI:30kHz, 1xsine): 1430 cycles
(CPU: 80MHz, NMI:40kHz, 1xsine):  800 cycles
(CPU: 80MHz, NMI:50kHz, 1xsine):  WDT

(CPU: 80MHz, NMI:10kHz, 2xsine): 6500 cycles
(CPU: 80MHz, NMI:20kHz, 2xsine): 2600 cycles
(CPU: 80MHz, NMI:30kHz, 2xsine): 1200 cycles
(CPU: 80MHz, NMI:40kHz, 2xsine):  WDT

(CPU:160MHz, NMI:10kHz, 2xsine): 7540 cycles
(CPU:160MHz, NMI:20kHz, 2xsine): 3240 cycles
(CPU:160MHz, NMI:30kHz, 2xsine): 1910 cycles
(CPU:160MHz, NMI:40kHz, 2xsine): 1250 cycles
(CPU:160MHz, NMI:50kHz, 2xsine):  850 cycles
(CPU:160MHz, NMI:60kHz, 2xsine):  WDT

What scares me is that with 2.5.0 I think I get WDT resets where I didn't get with 2.4.1, but I can still use it for the application, which doesn't have anything to do with audio btw. And about the SW sigma delta modulator, I use it to replace a PWM modulator, to move the noise up in frequency for easier filtering; I had to drive it by the same NMI, since there's only one in 8266, and using it excludes the PWM's from arduino code; it does the job and can even produce a low frequency signal.
I have tried a function generator with I2S, but you have to feed the beast at the sampling rate, so one way or another I still had to do calculations at that rate, and done for I2S inside Arduino loop() function it lagged at times; it turned out faster when done in NMI.

**Comment by earlephilhower** [comment] 2019-01-14 22:32
I'm not quite sure what you're measuring there.

In 2.4.1 there was no concept of a timer callback so you must have been taking the timer1 and IRQ over directly.  Are you saying that you're doing that again and at 50-60khz you get NMIs when before you didn't?  The SDK was updated in the meantime, so it could be something inside the closed source Espressif code that's resulting in this.

Just as an aside, you're perfectly welcome to override the timer1 if you're not expecting anything else to use it (i.e. no tone/analogWrite/etc.) in any version.  It'll be the same as earlier versions where you can't do anything else w/the timer.  If you were using timer1 in your own code + analogWrite in 2.4.1, the PWM would not be what it was trying to generate.

In any case, you're using up time that the app+OS were using when in NMI, even if you're using your own routine.  So you've got anywhere from 10-80% fewer user cycles before the WDT fires depending on that irqPause.  Sprinkling your app code liberally with lots of `delay(0);`s may help there, but unfortunately the WDT exception doesn't make it easy to pinpoint where the problem is.   It could be in the WIFI code itself in which case you simply can't add them.

I2S has DMA buffers so you don't need to fill in the FIFO in your app.  On average you need to generate the proper # of samples, of course, but you can have significant variation w/o underflow (plus it's less wasteful of CPU to do multiple loops of delta-sigma, and you're guaranteed the expected output frequency which is gonna be 32x(!) higher than you can do now...44.1khz*32b/sample, shifting the noise even higher in F).

I think it's neat how much you're getting out of the core, but it looks to me like you're squeezing a balloon and running out of absolute clock cycles to do everything you want to do.

**Comment by mcbp223** [comment] 2019-01-14 23:18
Yes it's stretching the limits of 8266, obviously.

The number measured is what I would return to the NMI from my callback, adjusted dynamically with ++/-- to keep close to the target sample frequency.
In the application I am using a manually implemented ISR since in 2.4.1 there was no callback to setup.

I think too that the closed source code got bigger meantime and may do more, what compiled to 720kB now compiles to 860kB.

I did try I2S with two methods, one with feeding in the loop(), another with precomputed DMA buffers.
The one with feeding had to compute not only the sample every time, but also the bits inside the sample, to simulate PDM.
The method with prefilled buffers was obviously very easy to the processor, but didn't let me fine tune the signal frequency, only in certain steps. I had a table in memory with the I2S dividers precomputed for 20k different frequencies, each position occupying 32bit, and also tables with the waveforms, it worked well but I couldn't get to vary the signal frequency smoothly, it had glitches since every time a new frequency started, it was from phase zero, and I couldn't control at what phase the previous signal stopped.
So regarding frequencies, in the example posted I am using a sampling frequency of around 48kHz, just as an example that many applications may not need, but the hardware sigma delta that 8266 has does the oversampling at 8MHz when prescaled with 10, so the output looks really good.

**Comment by earlephilhower** [comment] 2019-01-14 23:31
If you're adventurous, maybe you can directly hook the IRQ vector instead of using the framework, and jump into the espressif's OS interrupt handler if it's not your timer1 interrupt.  Check the interrupt vector section in Xtensa ISA Reference Guide.  I think there's only one vector the core jumps to, which is then responsible for figuring out why it was called by examining peripherals and jumping to the appropriate callback.  You're going to need to write assembly to save and restore all registers/etc., of course.  Not fun, but you could prioritize your check over all others.

**Comment by mcbp223** [comment] 2019-01-15 01:45
Oh, even though maybe I could squeeze a few more cycles by going that IRQ vector route, it would take me ages, and wouldn't double the frequency I can go up to in any way.
But by now I really believe that this timer1 is a shared resource with wifi, that you'd have to somehow protect access to it by disabling edge interrupts at the start of the ISR, otherwise I can't explain the difference in wdt resets versus not having them disabled, and that I've seen them disabled in other implementations.
