### ISSUE TITLE
HTTP server slow on simultaneous requests 

### ISSUE THREAD

**Issue by tttapa** [esp8266/Arduino#3467] opened 2017-07-27 20:00 UTC
#### Hardware
Hardware:			WeMos D1 mini
Core Version:      	2.3.0

### Description

When sending multiple HTTP requests at the same time to the web server running on the ESP, the server responds very slowly (up to 23 seconds) and some requests even fail (because the ESP sends an empty response). 
If I change my client code so that it waits for one request to finish before sending the next request, these problems do not occur (all requests finish in less than 40ms).

#### All requests at once:
![all at once](https://raw.githubusercontent.com/tttapa/random/master/all_at_once.png)
#### One request after the other:
![one by one](https://raw.githubusercontent.com/tttapa/random/master/one_by_one.png)
Blue: Content download
Green: Time to first byte (waiting)
Grey: Stalled

Sometimes, _output?output=5_ fails, sometimes it doesn't. Not sure why.
### Settings in IDE

Module:  			WeMos D1 R2 & mini
Flash Size: 		4M (1M SPIFFS)
CPU Frequency:	80MHz
Upload Using:		Serial (921600 baud)

### Sketch

```cpp

#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <FS.h>


ESP8266WebServer server = ESP8266WebServer(80);       // create a web server on port 80

const char* WiFiHostname = "esp8266";      // Host name on the network

const char* ssid     = "SSID";         // The SSID (name) of the Wi-Fi network you want to connect to
const char* password = "PASSPHRASE";     // The password of the Wi-Fi network

const uint8_t outputs[] = { 2, 4, 5, 12, 13, 14, 15, 16 };
const size_t  nb_outputs = sizeof(outputs);

/*__________________________________________________________SETUP__________________________________________________________*/

void setup() {

  Serial.begin(115200);        // Start the Serial communication to send messages to the computer
  delay(10);
  Serial.println('\n');

  startOutputs();              // Set all LED pins to outputs

  startWiFi();                 // Start a Wi-Fi access point, and try to connect to some given access points. Then wait for either an AP or STA connection

  startSPIFFS();               // Start the SPIFFS and list all contents

  startServer();               // Start a HTTP server with a file read handler and an upload handler

}

/*__________________________________________________________LOOP__________________________________________________________*/

void loop() {
  server.handleClient();      // run the server
}

/*__________________________________________________________SETUP_FUNCTIONS__________________________________________________________*/

void startOutputs() {  // Set all LED pins to outputs
  for (uint8_t i = 0; i < nb_outputs; i++) {
    pinMode(outputs[i], OUTPUT);
  }
}

void startWiFi() {  // Start a Wi-Fi access point, and try to connect to some given access points. Then wait for either an AP or STA connection
  WiFi.hostname(WiFiHostname);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);             // Connect to the network
  Serial.print("Connecting to ");
  Serial.print(ssid); Serial.println(" ...");

  int i = 0;
  while (WiFi.status() != WL_CONNECTED) { // Wait for the Wi-Fi to connect
    delay(1000);
    Serial.print(++i); Serial.print(' ');
  }

  Serial.println('\n');
  Serial.println("Connection established!");
  Serial.print("IP address:\t");
  Serial.println(WiFi.localIP());         // Send the IP address of the ESP8266 to the computer
  Serial.println('\n');
}

void startSPIFFS() {  // Start the SPIFFS and list all contents
  SPIFFS.begin();                             // Start the SPI Flash File System (SPIFFS)
  Serial.println("SPIFFS started. Contents:");
  {
    Dir dir = SPIFFS.openDir("/");
    while (dir.next()) {                      // List the file system contents
      String fileName = dir.fileName();
      size_t fileSize = dir.fileSize();
      Serial.printf("\tFS File: %s,\tsize: %s\r\n", fileName.c_str(), formatBytes(fileSize).c_str());
    }
    Serial.print('\r');
  }
}

void startServer() {  // Start a HTTP server with a file read handler and an upload handler
  server.on("/output",  HTTP_POST, setOutput);
  server.on("/output",  HTTP_GET, getOutput);
  server.on("/nb_outputs",  HTTP_GET, get_nb_outputs);


  server.onNotFound(handleNotFound);          // if someone requests any other file or page, go to function 'handleNotFound'
  // and check if the file exists

  server.begin();                             // start the HTTP server
  Serial.println("HTTP server started.");
  Serial.println('\n');

}

/*__________________________________________________________SERVER_HANDLERS__________________________________________________________*/

void handleNotFound() {  // if the requested file or page doesn't exist, return a 404 not found error
  if (!handleFileRead(server.uri())) {        // check if the file exists in the flash memory (SPIFFS), if so, send it
    server.send(404, "text/plain", "404: File Not Found");
  }
}

bool handleFileRead(String path) {  // send the right file to the client (if it exists)
  Serial.println("handleFileRead: " + path);
  if (path.endsWith("/")) path += "index.html";            // If a folder is requested, send the index file
  String contentType = getContentType(path);               // Get the MIME type
  String pathWithGz = path + ".gz";
  if (SPIFFS.exists(pathWithGz) || SPIFFS.exists(path)) {  // If the file exists, either as a compressed archive, or normal
    if (SPIFFS.exists(pathWithGz))                           // If there's a compressed version available
      path += ".gz";                                           // Use the compressed verion
    File file = SPIFFS.open(path, "r");                      // Open the file
    size_t sent = server.streamFile(file, contentType);      // Send it to the client
    file.close();                                            // Close the file again
    Serial.println(String("\tSent file: ") + path);
    return true;
  }
  Serial.println(String("\tFile Not Found: ") + path);   // If the file doesn't exist, return false
  return false;
}

void setOutput() {
  if ( ! server.hasArg("output") || ! server.hasArg("state")
       || server.arg("output") == NULL ) {                                // If the POST request doesn't have "output" and "state" data
    server.send(400, "text/plain", "400: Invalid Request");               // The request is invalid, so send HTTP status 400
    return;
  }
  char state_char = server.arg("state").c_str()[0];  // the first character of the state
  if (state_char != '1' &&  state_char != '0') {
    server.send(400, "text/plain", "400: Invalid Request");               // The request is invalid, so send HTTP status 400
    return;
  }
  bool state = state_char - '0';
  unsigned int output = server.arg("output").toInt();
  if (output >= nb_outputs) {
    server.send(404, "text/plain", "404: Output not found");              // The request is invalid, because the output doesn't exist
    return;
  }
  digitalWrite(outputs[output], state);                                   // Set the selected output accordingly
  Serial.printf("SET \tOutput: %d\tState: %d\r\n", output, state);
  Serial.printf("[S %d:%d]\t%lu\tStart sending\r\n", millis(), output, state);
  unsigned long start = millis();
  server.send(200);
  Serial.printf("[S %d:%d]\t%lu\tFinished sending\t(%lu)\r\n", output, state, millis(), millis() - start);
}

void getOutput() {
  if ( ! server.hasArg("output") || server.arg("output") == NULL) {                                 // If the POST request doesn't have "output" and "state" data
    server.send(400, "text/plain", "400: Invalid Request");               // The request is invalid, so send HTTP status 400
    return;
  }
  unsigned int output = server.arg("output").toInt();
  if (output >= nb_outputs) {
    server.send(404, "text/plain", "404: Output not found");              // The request is invalid, because the output doesn't exist
    return;
  }
  char state_str[2];
  state_str[0] = '0' + digitalRead(outputs[output]);                      // Get the state of the selected output
  state_str[1] = '\0';
  
  static unsigned long first_req = millis();

  Serial.printf("GET \tOutput: %d\r\n", output);
  Serial.printf("[G %d]\t%lu\tStart sending\r\n", output, millis() - first_req);
  unsigned long start = millis();
  server.send(200, "text/plain", state_str);                              // Send it to the client
  Serial.printf("[G %d]\t%lu\tFinished sending\t(%lu)\r\n", output, millis() - first_req, millis() - start);
}

void get_nb_outputs() {
  char nb_outputs_str[3];
  sprintf(nb_outputs_str, "%02X", nb_outputs);                            // Convert nb_outputs to hex string
  server.send(200, "text/plain", nb_outputs_str);                         // Send it to the client
}
/*__________________________________________________________HELPER_FUNCTIONS__________________________________________________________*/

String formatBytes(size_t bytes) {  // convert sizes in bytes to KB and MB
  if (bytes < 1024) {
    return String(bytes) + "B";
  } else if (bytes < (1024 * 1024)) {
    return String(bytes / 1024.0) + "KB";
  } else {
    return String(bytes / 1024.0 / 1024.0) + "MB";
  }
}

String getContentType(String filename) { // determine the filetype of a given filename, based on the extension
  if (filename.endsWith(".html")) return "text/html";
  else if (filename.endsWith(".css")) return "text/css";
  else if (filename.endsWith(".js")) return "application/javascript";
  else if (filename.endsWith(".ico")) return "image/x-icon";
  else if (filename.endsWith(".gz")) return "application/x-gzip";
  return "text/plain";
}
```
#### HTML/JavaScript all at once
``` html
<html>
<head>
    <link rel="stylesheet" type="text/css" href="main.css">
</head>
<body>
    <script>
        function sendButtonState(button, state) {
            console.log(button + ": " + state);

            let request = new XMLHttpRequest();
            request.open("POST", "/output");
            request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            request.send("output=" + encodeURI(button) + "&state=" + state);
        }

        let nb_outputs_req = new XMLHttpRequest();
        nb_outputs_req.onload = displayAllButtons;
        nb_outputs_req.open("GET", "/nb_outputs");
        nb_outputs_req.send();

        function displayAllButtons() {
            let nb_buttons = parseInt(nb_outputs_req.response, 16);
            for (i = 0; i < nb_buttons; i++) {
                displayButton(i);
            }
        }
        function displayButton(button) {
            let buttondiv = document.createElement("div");
            buttondiv.innerHTML =
                `<h2>Output ${button + 1}</h2>\
                <label class="switch">
                    <input id="${button}" type="checkbox" onchange="sendButtonState(this.id,this.checked?'1':'0');">
                    <div class="slider round"></div>
                </label>`;
            let checkbox = buttondiv.getElementsByTagName("input")[0];
            let state_req = new XMLHttpRequest();
            state_req.onload = function () {
                checkbox.checked = state_req.response === '1' ? true : false;
            };
            state_req.open("GET", "/output?output=" + button);
            state_req.send();
            document.body.appendChild(buttondiv);
        }
    </script>
</body>
</html>
```
#### HTML/JavaScript one by one
``` html
<html>
<head>
    <link rel="stylesheet" type="text/css" href="main.css">
</head>
<body>
    <script>
        function sendButtonState(button, state) {
            console.log(button + ": " + state);

            let request = new XMLHttpRequest();
            request.open("POST", "/output");
            request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            request.send("output=" + encodeURI(button) + "&state=" + state);
        }

        let nb_outputs_req = new XMLHttpRequest();
        nb_outputs_req.onload = displayAllButtons;
        nb_outputs_req.open("GET", "/nb_outputs");
        nb_outputs_req.send();

        function displayAllButtons() {
            let nb_buttons = parseInt(nb_outputs_req.response, 16);
            displayButton(0, nb_buttons);
        }
        function displayButton(button, nb_buttons) {
            let buttondiv = document.createElement("div");
            buttondiv.innerHTML =
                `<h2>Output ${button + 1}</h2>\
                <label class="switch">
                    <input id="${button}" type="checkbox" onchange="sendButtonState(this.id,this.checked?'1':'0');">
                    <div class="slider round"></div>
                </label>`;
            let checkbox = buttondiv.getElementsByTagName("input")[0];
            let state_req = new XMLHttpRequest();
            state_req.onload = function () {
                checkbox.checked = state_req.response === '1' ? true : false;
                document.body.appendChild(buttondiv);
                if (++button < nb_buttons) {
                    displayButton(button, nb_buttons);
                }
            };
            state_req.open("GET", "/output?output=" + button);
            state_req.send();
        }
    </script>
</body>
</html>
```

### Debug Messages
These are the debug messages corresponding to the following image:  
![all at once](https://raw.githubusercontent.com/tttapa/random/master/all_at_once-c.png)
The numbers in the second column are time stamps, starting from the first request, the numbers between parentheses are the duration of each response. (in milliseconds) 
```
Connecting to SSID ...
1 2 3 4 5 6 7 

Connection established!
IP address:	192.168.1.15


SPIFFS started. Contents:
	FS File: /main.css,	size: 906B
	FS File: /index.html,	size: 1.69KB

HTTP server started.


handleFileRead: /
	Sent file: /index.html
handleFileRead: /main.css
	Sent file: /main.css
GET 	Output: 0
[G 0]	0	Start sending
[G 0]	10002	Finished sending	(10001)
GET 	Output: 1
[G 1]	12006	Start sending
[G 1]	12036	Finished sending	(30)
GET 	Output: 2
[G 2]	12041	Start sending
[G 2]	12050	Finished sending	(9)
GET 	Output: 3
[G 3]	12055	Start sending
[G 3]	12068	Finished sending	(13)
GET 	Output: 5
[G 5]	12073	Start sending
[G 5]	12081	Finished sending	(8)
GET 	Output: 4
[G 4]	12086	Start sending
[G 4]	12097	Finished sending	(11)
GET 	Output: 6
[G 6]	12102	Start sending
[G 6]	12110	Finished sending	(8)
GET 	Output: 7
[G 7]	12114	Start sending
[G 7]	12129	Finished sending	(15)
```
I know it's a lot of code, but many parts are the same as (or very close to) the [FSBrowser example](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples/FSBrowser).

The JavaScript code first asks the ESP how many outputs it has (GET request to `/nb_outputs`). Then it creates the right number of buttons (one for each output) and asks the ESP what the state of each output is (GET request to `/output?output=i`, where i is the number of each button). Finally, it changes the state of the buttons on the webpage according to the response it got from the ESP. 
By clicking a button, it sends the new state to the ESP (POST request to `/outputs` with a body containing urlencoded formdata `output=i&state=x` where x is either '0' or '1').

I really don't know why the first request takes so long (10s according to the ESP, 23s according to Chrome) and why the the other requests all finish after 12s (according to both the ESP and Chrome).

Thanks in advance, 
Pieter

**Comment by JamesGKent** [comment] 2017-08-07 14:52
the webserver can only handle a single request at a time, so receiving multiple requests at once (so more come while dealing with the first) drags the flow of execution away from your code to handle the background wifi related tasks, this will slow down the execution and use more resources, it's possible you are running out of ram/stack causing some of your requests to fail.
i would suggest that issuing a separate request for each output is bad design, instead i would make it so you have a single request to get all output states at the same time as you request the number of outputs.

Just a thought.

however if you are insistent on this design, look into the async libraries for esp, specifically asyncwebserver

**Comment by tttapa** [comment] 2017-08-07 21:22
Thank you for the reply.
In the final version, I send everything in a single response, but I just found it strange that it fails so easily. I thought that there may be a problem with the actual code I used in the server handlers.
I'll definitely look into the async libraries, looks very interesting. 

Thanks again,
Pieter

**Comment by devyte** [comment] 2017-08-07 22:01
A note here, from my experience a few months backago.
The async webserver has many good things, but there is one downside: you
can't call yield() or delay() from an endpoint handler, because it doesn't
run in the loop.
This means that, if your handler takes a long processing time, you'll run
into wifi stack corruption.
In contrast, the standard webserver runs in the loop, so if your handler
takes a long time, you can call yield() in key places to allow the wifi
stack to process before the handler is done.

There are ways around this limitation in the async webserver, but they are
nontrivial and make for very complex code.

Personally, after trying out both, I'm sticking to the standard webserver,
but of course that's just my own choice.

**Comment by JamesGKent** [comment] 2017-08-08 09:40
fair enough, one thing i can add is that using the `String` type and joining them together can be a big cause of the slowdown, along with memory fragmentation, for my code i adapted it to using a big buffer assigned at the start of the handler, and then `strcpy` data into my buffer, i found this to be orders of magnitude faster than the strings, and a lot more stable too, you could look at that instead?

**Comment by perote2000** [comment] 2017-08-14 02:48
Hi, could you write a small example of code about using buffer insteaf of strings. Are you telling about client.print for instance.. ?

**Comment by JamesGKent** [comment] 2017-08-14 08:25
so not a complete example, but i add a variable like this:
#define RETBUF_SIZE 1420
char retbuf[RETBUF_SIZE];

then in the function where you receive a new request start with:
memset(retbuf, 0, RETBUF_SIZE); // empty the reply buffer
uint16_t retlength; // to keep track of where in buffer we have written to

then to add new data to the buffer:
retlength += sprintf(&retbuf[retlength], "new string stuff");

note that if you want to add numbers you'll have to do the conversions yourself

this could of course be encapsulated in a class much like how the arduino string class works, but the difference is the memory gets assigned once in a contiguous block rather than little chunks all over the place.

**Comment by tttapa** [comment] 2017-08-14 12:11
Do you mean the Strings used in the actual server class that comes with the ESP8266 Arduino Core?

**Comment by JamesGKent** [comment] 2017-08-14 12:23
yes, the built in Arduino String type that comes with the core allocates more memory when you add them together or add sting literals etc into them. allocating memory like that is slow, and also means that the figure the IDE gives you for memory used becomes inaccurate, and causes memory fragmentation. by assigning a big buffer for any built responses you get a single allocation (faster) with a single contiguous block (no fragmentation) and because i defined mine as global its a known amount of memory used, meaning i have a better idea how much i'm using overall from the output of the compiler.

however rereading your code you only seem to use the string type in your file handler rather than for your built responses, in which case you are probably causing memory exhaustion with your flood of connections

**Comment by tttapa** [comment] 2017-08-14 13:45
I'm well aware of the disadvantages of String objects, what I meant was that the server class itself uses Strings rather than null terminated char arrays for things like HTTP headers and arguments:
[ESP8266WebServer.h](https://github.com/esp8266/Arduino/blob/72ed29ad5f18aac3d26037e4a8ff14cc523eb7a1/libraries/ESP8266WebServer/src/ESP8266WebServer.h#L97)

**Comment by everslick** [comment] 2017-11-06 12:55
FYI: The String class has the reserve() method. If you know how big your html code is going to be, just reserve as much as needed before adding substrings to it. This will avoid the whole fragmentation/reallocation/memcopy problem and you get all benefits from the String class.

```
String str;

str.reserve(1024);
str = F("foo");
str += F("bar");
...
```

**Comment by PotatoX** [comment] 2017-12-02 15:12
Also consider compartmentalizing your code a bit and using scrip synchronization? This worked for me to keep the browser from blasting my ESP webserver with a bunch of simult loads.

https://www.w3schools.com/tags/att_script_defer.asp
-or-
https://www.w3schools.com/tags/att_script_async.asp

**Comment by devyte** [comment] 2019-11-20 04:37
This issue is old. A lot has changed since it was reported, including a long list of relevant fixes.
Closing due to age.
If you think the problem is still relevant, please open a new issue, follow the template instructions, and add details like in this report.

**Closed by devyte** 2019-11-20 04:37 UTC
