### ISSUE TITLE
Error compile Windows 10

### ISSUE THREAD

**Issue by sabas1080** [esp8266/Arduino#3926] opened 2017-12-06 18:03 UTC
#### Hardware
Hardware:			ESP12
Core Version:      	2.3.0

### Description

Problem description

### Settings in IDE

Module:  			Wemos D1
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		nodemcu

### Sketch
```
Example Blink
```

### Debug Messages

```
unable rename

arduino.ar reason: File exists
```

I already tried running as administrator, in Arduino IDE 1.8.4 and 1.8.5 installer and portable #2987

![24882775_1039864912834193_1928425778_o](https://user-images.githubusercontent.com/2874292/33677214-a25fbd54-da7d-11e7-85f8-41d4025e32d2.png)

**Comment by devyte** [comment] 2017-12-06 18:07
@sabas1080 I suggest a clean install. That includes deleting the Arduino15 folder. Don't forget to back up your projects before deleting.
Closing as can't reproduce.

**Closed by devyte** 2017-12-06 18:07 UTC

**Comment by sabas1080** [comment] 2017-12-06 18:18
Also try cleaning and deleting Arduino15 and the same error

**Comment by Spackstor** [comment] 2019-12-15 16:09
I believe this problem is caused by not closing your file before exiting Arduino. The first time this happens running as administrator may work. The second time, it will be the administrator's working file and Windows will protect it. It is not the only file involved.
So find the file's Temp directory by doing a search on the file and delete the Temp directory.  This worked for me and so far so good.
