### ISSUE TITLE
error: conflicting declaration 'typedef uint32_t u32_t'

### ISSUE THREAD

**Issue by Tahitibob35** [esp8266/Arduino#3771] opened 2017-10-29 16:32 UTC
### Basic Infos
I want to use NTP library (https://github.com/gmag11/NtpClient) and SPIFF library

#### Hardware
Hardware:			NodeMCU v3 (ESP-12E Module)
Core Version:      	2.3.0

### Description

#include "user_interface.h"
#include "spiffs/spiffs.h"
Compilation error :
error: conflicting declaration 'typedef int32_t s32_t'
error: conflicting declaration 'typedef uint32_t u32_t'

### Settings in IDE

Module:  			NodeMCU1.0 (ESP-12E Module)
Flash Size: 		4MB
CPU Frequency:	80Mhz
Flash Mode:		??
Flash Frequency:	840Mhz?
Upload Using:		SERIAL
Reset Method:		??

### Sketch

```cpp
#include "user_interface.h"
#include "spiffs/spiffs.h"
void setup() {
}
void loop() {
}
```

### Debug Messages

```
/1data/applications/arduino-1.8.4/arduino-builder -dump-prefs -logger=machine -hardware /1data/applications/arduino-1.8.4/hardware -hardware /home/david/.arduino15/packages -hardware /home/david/Arduino/hardware -tools /1data/applications/arduino-1.8.4/tools-builder -tools /1data/applications/arduino-1.8.4/hardware/tools/avr -tools /home/david/.arduino15/packages -built-in-libraries /1data/applications/arduino-1.8.4/libraries -libraries /home/david/Arduino/libraries -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=80,UploadSpeed=115200,FlashSize=4M3M -ide-version=10804 -build-path /tmp/arduino_build_801784 -warnings=none -build-cache /tmp/arduino_cache_283260 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=/home/david/.arduino15/packages/esp8266/tools/esptool/0.4.9 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=/home/david/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2 -prefs=runtime.tools.mkspiffs.path=/home/david/.arduino15/packages/esp8266/tools/mkspiffs/0.1.2 -verbose /home/david/Arduino/sketch_oct29b/sketch_oct29b.ino
/1data/applications/arduino-1.8.4/arduino-builder -compile -logger=machine -hardware /1data/applications/arduino-1.8.4/hardware -hardware /home/david/.arduino15/packages -hardware /home/david/Arduino/hardware -tools /1data/applications/arduino-1.8.4/tools-builder -tools /1data/applications/arduino-1.8.4/hardware/tools/avr -tools /home/david/.arduino15/packages -built-in-libraries /1data/applications/arduino-1.8.4/libraries -libraries /home/david/Arduino/libraries -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=80,UploadSpeed=115200,FlashSize=4M3M -ide-version=10804 -build-path /tmp/arduino_build_801784 -warnings=none -build-cache /tmp/arduino_cache_283260 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=/home/david/.arduino15/packages/esp8266/tools/esptool/0.4.9 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=/home/david/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2 -prefs=runtime.tools.mkspiffs.path=/home/david/.arduino15/packages/esp8266/tools/mkspiffs/0.1.2 -verbose /home/david/Arduino/sketch_oct29b/sketch_oct29b.ino
Using board 'nodemcuv2' from platform in folder: /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0
Using core 'esp8266' from platform in folder: /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0
Warning: Board breadboard:avr:atmega328bb doesn't define a 'build.board' preference. Auto-set to: AVR_ATMEGA328BB
Detecting libraries used...
"/home/david/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/tmp/arduino_build_801784/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10804 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "/tmp/arduino_build_801784/sketch/sketch_oct29b.ino.cpp" -o "/dev/null"
Generating function prototypes...
"/home/david/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/tmp/arduino_build_801784/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10804 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "/tmp/arduino_build_801784/sketch/sketch_oct29b.ino.cpp" -o "/tmp/arduino_build_801784/preproc/ctags_target_for_gcc_minus_e.cpp"
"/1data/applications/arduino-1.8.4/tools-builder/ctags/5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/tmp/arduino_build_801784/preproc/ctags_target_for_gcc_minus_e.cpp"
Compilation du croquis...
"/home/david/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/tmp/arduino_build_801784/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10804 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "/tmp/arduino_build_801784/sketch/sketch_oct29b.ino.cpp" -o "/tmp/arduino_build_801784/sketch/sketch_oct29b.ino.cpp.o"
In file included from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/spiffs/spiffs.h:14:0,
                 from /home/david/Arduino/sketch_oct29b/sketch_oct29b.ino:2:
/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/spiffs/spiffs_config.h:21:17: error: conflicting declaration 'typedef int32_t s32_t'
 typedef int32_t s32_t;
                 ^
In file included from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/lwip/arch.h:43:0,
                 from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/lwip/debug.h:35,
                 from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/lwip/opt.h:46,
                 from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/lwip/ip_addr.h:35,
                 from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include/user_interface.h:11,
                 from /home/david/Arduino/sketch_oct29b/sketch_oct29b.ino:1:
/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/arch/cc.h:57:28: error: 's32_t' has a previous declaration as 'typedef long int s32_t'
 typedef signed     long    s32_t;
                            ^
In file included from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/spiffs/spiffs.h:14:0,
                 from /home/david/Arduino/sketch_oct29b/sketch_oct29b.ino:2:
/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/spiffs/spiffs_config.h:22:18: error: conflicting declaration 'typedef uint32_t u32_t'
 typedef uint32_t u32_t;
                  ^
In file included from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/lwip/arch.h:43:0,
                 from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/lwip/debug.h:35,
                 from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/lwip/opt.h:46,
                 from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/lwip/ip_addr.h:35,
                 from /home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include/user_interface.h:11,
                 from /home/david/Arduino/sketch_oct29b/sketch_oct29b.ino:1:
/home/david/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include/arch/cc.h:56:28: error: 'u32_t' has a previous declaration as 'typedef long unsigned int u32_t'
 typedef unsigned   long    u32_t;
                            ^
exit status 1
Erreur de compilation pour la carte NodeMCU 1.0 (ESP-12E Module)

```

**Comment by devyte** [comment] 2017-10-29 16:42
@Tahitibob35 you mention NtpClientLib, but it's not included in the code you show.
You're including user_interface.h without the extern C wrapper.
You're including the internal spiffs.h instead of the exported SPIFFS.h.
Please look at the examples. If you need further assistance, please ask at a community forum.
I am using both SPIFFS and NtpLientLib without issues.
Closing as can't reproduce and due to user errors.

**Closed by devyte** 2017-10-29 16:42 UTC
