### ISSUE TITLE
core_esp8266_features.h: No such file or directory

### ISSUE THREAD

**Issue by vimosd** [esp8266/Arduino#3981] opened 2017-12-17 09:50 UTC
while compiling getting this:
core_esp8266_features.h: No such file or directory

**Comment by devyte** [comment] 2017-12-18 03:13
@vimosd no basic info, no IDE settings, no example sketch. You ignored the entire issue template.
Assuming you have selected the correct board, I suggest a clean install from scratch.
Closing due to can't reproduce, and lack of info.

**Closed by devyte** 2017-12-18 03:13 UTC
