### ISSUE TITLE
Latest UART buffers break Serial.swap()

### ISSUE THREAD

**Issue by riataman** [esp8266/Arduino#3192] opened 2017-05-03 00:40 UTC
I have a NodeMCU, I was using Serial.swap() just fine with 2.3.0. After upgrading to master Serial.swap doesn't work anymore. 

If I backup the serial buffer changes it works again.

**Comment by igrr** [comment] 2017-05-08 16:15
By "doesn't work", you mean that the output is still sent to the original pins after `swap`? Or some other issue?

**Comment by igrr** [comment] 2017-05-18 10:24
@riataman  Can you confirm that the issue is that you can not `swap` back to the original pins?

**Comment by riataman** [comment] 2017-05-18 16:19
Sorry, I haven't been able to get back to test this, but as I remember I was just calling ´Serial.swap´ once and the alternative pins didn't worked.

I'll try to get back to test this again soon.

**Comment by devyte** [comment] 2017-12-28 15:28
@riataman ping

**Comment by d-a-v** [comment] 2018-10-12 13:11
Closing due to age and because `Serial.swap()` is working.
Please open a new issue with more details if your tests are not satisfactory.

**Closed by d-a-v** 2018-10-12 13:11 UTC
Labels: component: core, type: bug
