### ISSUE TITLE
google doesn't return responses sometimes

### ISSUE THREAD

**Issue by wyasuda** [esp8266/Arduino#2289] opened 2016-07-17 08:59 UTC
Hi,

I tried to upload an image taken by ArduCAM to Google Cloud Storage by the code below.
I use WiFiClientSecure.
It looked working properly, but approximately 1 out of 3 times, I did not get any response from google's server.
Are there anything I miss?
Thank you in advance.

  //upload picture to Google Storage
  while(!client.connect("www.googleapis.com", 443)) delay(10);    

  client.println("POST /upload/storage/v1/b/temp_bucket/o?uploadType=media&name=myObject HTTP/1.1");
  client.println("Host: www.googleapis.com");
  client.println("Content-Type: image/jpeg"); 
  client.println("Connection: close");
  client.print("Content-Length: ");
  client.println(len);
  client.print("Authorization: Bearer ");
  client.println(access_token);
  client.println();

  static const size_t bufferSize = 4096;
  static uint8_t buffer[bufferSize] = {0xFF};
  while (len) {
    size_t will_copy = (len < bufferSize) ? len : bufferSize;
    SPI.transferBytes(&buffer[0], &buffer[0], will_copy);
    if (!client.connected()) break;
    client.write(&buffer[0], will_copy);
    len -= will_copy;
  }
  myCAM.CS_HIGH();
  client.println(); 

  // Read  the reply from server
  while (client.connected()){
    if ( client.available() ){
      char c=client.read();
      Serial.print(c);
    }  
  }
  client.stop();

**Comment by devyte** [comment] 2017-10-14 23:58
@wyasuda No basic info, no IDE settings, incomplete sketch.
I don't see anything obvious in your code.
If the issue is still valid with latest git, I suggest taking a look with wireshark.
Please discuss at a community forum, this is an issue tracker.
Closing per #3655 .

**Closed by devyte** 2017-10-14 23:58 UTC
