### ISSUE TITLE
WebServer hangs on GET in versions above 2.3.0

### ISSUE THREAD

**Issue by ntsecrets** [esp8266/Arduino#3092] opened 2017-03-26 14:30 UTC
I have a clock that also has the webserver running, no ssl on port 80.  Compile with 2.3.0 works and I can get pages.  If I build with the nightly build it complies and runs, but the clock freezes when I do a http get (just in a browser) and I get no data.  If I hit stop in the browser the clock starts running again.  So it works fine in 2.3.0 but the nightly hangs.   Only thing I haven't tried was a hard reset (power cycle) after updating in case that matters, this is updated via OTA, which still works even when the main part hangs. 

#### Hardware
Hardware:			ESP-01
Core Version:      nightly-build

### Description

Library ESP8266WebServer hangs on GET in nightly build ver.

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		1MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		OTA 
Reset Method:		ck

Code here: https://github.com/ntsecrets/espclock/blob/master/esp8266-ledclock_v5/esp8266-ledclock_v5.ino

**Comment by devyte** [comment] 2019-11-20 04:44
This issue is old. A whole lot has changed since it was reported, including a long list of relevant fixes.
Closing due to age.
If you think the problem is still relevant, please open a new issue and follow the template instructions.

**Closed by devyte** 2019-11-20 04:44 UTC
