### ISSUE TITLE
"No such file or directory" error compiling sketch

### ISSUE THREAD

**Issue by acoulson2000** [esp8266/Arduino#6717] opened 2019-11-06 13:32 UTC
#### Platform

- Hardware:				ESP8266
- Core Version:			2.5.2
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Mode:			dout
- Flash Size: 			1MB
- lwip Variant:   		v1.4
- Reset Method:		ck
- Flash Frequency:		40Mh]
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   		256200

### Problem Description

When I try to compile any sketch, I consistently get errors like:

xtensa-lx106-elf-gcc: error: C:\Users\acoulson\AppData\Local\Temp\arduino_cache_508305\core\core_esp8266_esp8266_generic_xtal_80,exception_disabled,ssl_all,ResetMethod_ck,CrystalFreq_26,FlashFreq_40,FlashMode_dout,eesz_1M64,led_2,ip_lm2f,dbg_Disabled,lvl_None____,wipe_none,baud_256000_8703485dc7715ec16b554ce94a858534.a: No such file or directory

exit status 1
Error compiling for board Generic ESP8266 Module.

The path (as visible in the error) being generated by the tool chain exceeds the maximum file path length allowable under windows, which I believe is the source of the problem.

I'm not sure why build settings need to be part of the library path, but I would suggest shortening the config token names or excluding ones that are set to the default. I could be wrong, but I don't believe we, as end users, have control over the path those temporary build files are stored in.

**Comment by devyte** [comment] 2019-11-06 15:30
> I'm not sure why build settings need to be part of the library path

This is how the arduino build system works, it's called fqbn. It has already been shortened a while back, and changing the fqbn caused a lot of breakage out there. Even if we could shorten it further, we don't want to go through that again. 

The issue is the Windows path length limitation. There are three possible workarounds for you that I'm aware of:
1. Don't develop under windows. Use either a linux guest in VirtualBox, or use WSL. 
2. Disable the windows path length limitation. This requires editing the registry. Google is your friend. I don't remember if this actually works for the compiler though.
3. Move your temp dir to be C:/Temp. I think this also requires registry editing. Again, google is your friend. 

Whatever else, I don't think there's anything further that can be done in the core that hasn't already been done.
Closing.

**Closed by devyte** 2019-11-06 15:30 UTC
