### ISSUE TITLE
 SPIFFS crashes after adding unrelated code when saving configuration

### ISSUE THREAD

**Issue by helpme1** [esp8266/Arduino#2560] opened 2016-09-29 11:03 UTC
Module:             NodeMCU
Flash Size:         4MB
CPU Frequency:      80Mhz
Flash Mode:         dio?
Flash Frequency:    40Mhz
Upload Using:       SERIAL
Reset Method:        nodemcu

I am encountering a strange behavior. I am using ESP8266 arduino SPIFFS to store configuration settings. Here is the relevant part of mycode; 

```
void loop()
{
      handleUartRxOk();
}

void handleUartRxOk() {
   String cmd;

   char charBuff[3200];
   char char_print[50];
   static bool terminatorReceived = false;

   char incomingChar = 0;   // for incoming serial data

   if (Serial.available()) {
      incomingChar = Serial.read();
      saveChar(incomingChar);

      if (incomingChar == '\r') {
         terminatorReceived = true;
      }

      if (terminatorReceived) {
         buffer[buffer_index - 1] = '\0';
         cmd = String(buffer);
         if (cmd == "XXX") {
            ConfigSettings.ssid = "SSID_XX";
            ConfigSettings.password = "PASSWORD_XX";
            saveConfig();
         } 

         buffer_index = 0;
         terminatorReceived = false;
      }
   }
} 
```

In the above code, the UART will receive a command "XXX\r", then run saveConfig() which will save the config parameters ssid and parameters into SPIFSS. This code works perfectly fine until I add more code which is totally unrelated.

This is how the new code looks like. 

```
void handleUartRxOk() {
   String cmd;

   char charBuff[3200];
   char char_print[50];
   static bool terminatorReceived = false;

   char incomingChar = 0;   // for incoming serial data

   if (Serial.available()) {
      incomingChar = Serial.read();
      saveChar(incomingChar);

      if (incomingChar == '\r') {
         terminatorReceived = true;
      }

      if (terminatorReceived) {
         buffer[buffer_index - 1] = '\0';
         cmd = String(buffer);
         if (cmd == "XXX") {
            ConfigSettings.ssid = "SSID_XX";
            ConfigSettings.password = "PASSWORD_XX";
            saveConfig();
         } 

         //Why does adding this else statement cause saveConfig() to crash?
         else {
               strcat(charBuff, cmd.c_str());
            }   

         buffer_index = 0;
         terminatorReceived = false;
      }
   }
} 
```

After adding the additional else clause, sending "XXX\r" to the UARt and causing saveConfig() will cause an exception error. This is puzzling since the new code did not even get to run.

The exception error is as below;

_Exception (3):

epc1=0x401002f0 epc2=0x00000000 epc3=0x00000000 excvaddr=0x400072f6 depc=0x00000
000

ctx: sys 

sp: 3fff06b0 end: 3fffffb0 offset: 01a0

**Comment by lorneb** [comment] 2016-09-29 11:31
Do you really need this buffer to be this big and not global?
char charBuff[3200];

**Comment by sticilface** [comment] 2016-09-29 14:48
I second that.  That will be on the stack which is only 4K.  You are better using new and delete to manage anything over 100 bytes TBH.

**Comment by helpme1** [comment] 2016-09-30 06:14
Thanks for the tips. Can I confirm with you that the maximum stack size is 4K? If yes, where is this defined? Can it be changed?

**Comment by devyte** [comment] 2017-10-12 05:40
@helpme1 previous comments are coorect: the issue is most likely a stack blowup due to that huge buffer. Yes, the stack size can be increased, but I don't recommend it, because it reduces your available heap. Instead, declare the buffer in global scope, create it dynamically, or use a managed object like std::vector, std::string, or String.
Closing as user error.

**Closed by devyte** 2017-10-12 05:40 UTC
