### ISSUE TITLE
iPhone failed to connect to AP with password

### ISSUE THREAD

**Issue by apicquot** [esp8266/Arduino#5396] opened 2018-11-30 02:23 UTC
### Basic Infos

- [x ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x ] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ x] I have filled out all fields below.

#### Platform

- Hardware:				ESP-12F and WROOM02
- Core Version:			2.4.2
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Generic Board ESP8266
- Flash Mode:			qio
- Flash Size: 		       2MB (1M SPIFFS)
- lwip Variant:                 v2 Lower Memory
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	        40Mhz
- CPU Frequency:		80Mhz|
- Upload Using:		SERIAL
- Upload Speed:             115200

### Problem Description

I am running the demo WiWiAcessPoint.ino:
I manage to connect the AP from and Android phone with no problem
From an iphone6 iOS12 I can only connect to the AP if I remove the password of the AP.

 
### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>

/* Set these to your desired credentials. */
const char *ssid = "ESPap";
const char *password = "thereisnospoon";

ESP8266WebServer server(80);

/* Just a little test message.  Go to http://192.168.4.1 in a web browser
   connected to this access point to see it.
*/
void handleRoot() {
  server.send(200, "text/html", "<h1>You are connected</h1>");
}

void setup() {
  delay(1000);
  Serial.begin(115200);
  Serial.println();
  Serial.print("Configuring access point...");
  
  //work in android with this option
  WiFi.softAP(ssid, password);

  //works with iphone 6 iOS12
  //WiFi.softAP(ssid);

  IPAddress myIP = WiFi.softAPIP();
  Serial.print("AP IP address: ");
  Serial.println(myIP);
  server.on("/", handleRoot);
  server.begin();
  Serial.println("HTTP server started");
}

void loop() {
  server.handleClient();
}

```

### Debug Messages

```
Configuring access point...[AP] softap config unchanged
AP IP address: 192.168.4.1
HTTP server started
ip:192.168.1.21,mask:255.255.255.0,gw:192.168.1.1
wifi evt: 3
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7

```

**Comment by apicquot** [comment] 2018-12-01 16:18
After further tests, the problem exists on both devices Android and iOS: the AP connection in fact keeps dropping for both. I suspect that WPA2 is too costly in CPU for the esp8266 softAP and the connection may timeout very often. Android may be more tolerant than iOS for timeout that may explain why it works better on one phone than the other. I can solve the problem by changing clock from 80M to 160M: Is it a problem to clock the esp8266 to 160M ? Is there any other way to improve the answer speed on the esp8266: changing the beacon interval ?

**Comment by Hieromon** [comment] 2018-12-02 04:33
HI,
I also encountered the same problem with iOS 12. A frequent occurrence when updated iOS to 12 and update Arduino IDE to 1.8.7. When connection errors to the AP occurred frequently, it immediately disconnected even when connecting from iOS, and the "ERROR: dhcps send nak" also occurred.
It recovered by erasing the flash with the esptool, then reducing the CPU clock to 80 MHz, crystal frequency to 24MHz,  and setting the Flash mode to the original DIO. It is interesting that the opposite of your resolution ways. However, this phenomenon may recur and is still in the stage of watching.

**Comment by devyte** [comment] 2018-12-02 05:32
@earlephilhower you've done tests @160MHz . Does any of this ring a bell?

**Comment by devyte** [comment] 2018-12-02 18:56
I can't reproduce this with a Wemos D1 mini r2, or on a Nodemcy v1.0, or on a WittyCloud. The AP works fine both with and without password, at both 80 and 160MHz CPU.
Different vendors/manufacturers/boards/makers can have different settings for flash speed, crystal freq, etc. There is even the case of the Puya flash chips, where some boards of the same brand/vendor can come with Puya or non-Puya chips (which currently can't be selected in the IDE and requires a patch to address).
Wrong settings can have weird effects, including something working at 80 and not at 160MHz, or vice versa, or have certain HWSerial speeds work but not others, etc.
You have to know what to set in the IDE in accordance to your board. If you don't know, you have to investigate. If a new variant of a board appear, you need to figure it out, and you're invited to contribute the variant's settings for inclusion in the IDE menu.

Closing due to can't reproduce.

**Closed by devyte** 2018-12-02 18:56 UTC
Labels: waiting for feedback
