### ISSUE TITLE
Arduiuno| fatel error : ESP8266WIFI.h: no such file or directory compilation termined.   

### ISSUE THREAD

**Issue by q785773826** [esp8266/Arduino#4681] opened 2018-04-25 11:40 UTC
### Basic Infos

- [ x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x ] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [x ] If there is a stack dump, I have decoded it.
- [x ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[2.41]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module|Wemos D1 mini r2|Nodemcu|other]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

Detailed problem description goes here.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>
#include <ESP8266WiFi.h>
const char* ssid     = "360wifilulu";
.......
void setup() {
..........
}

void loop() {
.............
}

```

### Debug Messages

```
Debug messages go here
C:\Users\Administrator\Desktop\鏃犵嚎\sketch_apr23a\sketch_apr23a.ino:1:25: fatal error: ESP8266wifi.h: No such file or directory

compilation terminated.

exit status 1

**Comment by devyte** [comment] 2018-04-25 13:58
I can't reproduce this. It looks like either an installation issue, or an issue with the path with chinese chars.
Closing.

**Closed by devyte** 2018-04-25 13:58 UTC
