### ISSUE TITLE
spiffs seek(..., SeekEnd) doesn't work

### ISSUE THREAD

**Issue by brianjmurrell** [esp8266/Arduino#4285] opened 2018-02-03 15:53 UTC
#### Hardware
Hardware:			NodeMCU
Core Version:      	2.4.0 I believe

### Description
`f.seek(80, SeekEnd);` doesn't actually seek from the end

### Settings in IDE

Module:  			NodeMCU 1.0
Flash Size: 		4MB/3MB
CPU Frequency:		80Mhz
Flash Mode:			not sure
Flash Frequency:	not sure
Upload Using:		SERIAL
Reset Method:		not sure

### Sketch

```cpp

#include <FS.h>

void setup() {
  SPIFFS.begin();
  File f = SPIFFS.open("/stats.txt", "r");
  f.seek(80, SeekEnd);
  Serial.println(f.size());
  Serial.println(f.position());
  f.seek(f.size() - 80);
  Serial.println(f.position());
}

void loop() {
// NA
}
```

### Debug Messages

```
2041660
2041660
2041580
```

As you can see the ` seek(80, SeekEnd)` didn't actually work and seeked to the end, not 80 bytes from the end.  The `seek(f.size() - 80)` did what the ` seek(80, SeekEnd)` should have done.

**Comment by igrr** [comment] 2018-02-03 16:09
Probably duplicate of https://github.com/esp8266/Arduino/issues/2597.

**Comment by devyte** [comment] 2018-02-04 01:08
It is. I'll pull the other one into 2.4.1 and make a PR.
Closing this as duplicate.

**Closed** 2018-02-04 01:10 UTC

**Comment by devyte** [comment] 2018-02-04 04:09
@brianjmurrell please try #4287 .
