### ISSUE TITLE
Esp8266 Reconnection Problem With Version 2.4.0

### ISSUE THREAD

**Issue by mustafayuce33** [esp8266/Arduino#4445] opened 2018-03-01 09:51 UTC
#### Hardware
Hardware:			ESP-12
Core Version:      	2.4.0

### Description

With previous version of SDK, esp tries to reconnect wifi network when its connection is lost. But with 2.4.0 version when I reboot modem esp can not recognize "disconnect" state. I have tested this issue with both of version. Esp with 2.3.0 version work well. 

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz?
Upload Using:		OTA
Reset Method:		ck

### Sketch

```cpp

#include <Arduino.h>

#include <ESP8266WiFi.h> 
#include <ESP8266WebServer.h>
#include <WiFiManager.h>         //https://github.com/tzapu/WiFiManager - See more at: http://www.esp8266.com/viewtopic.php?f=32&t=9056#sthash.ZdUTu2vQ.dpuf

Ticker connectionCheck;
ESP8266WebServer server(80);
ESP8266HTTPUpdateServer httpUpdater;


//callback notifying us of the need to save config
void saveConfigCallback () {
  Serial.println("Should save config");
  shouldSaveConfig = true;
}

char devicename[30] = "";
WiFiManagerParameter custom_devicename("devicename", "device name", devicename, 30);

bool reconnectChecker;

void connectionCheckHandler()
{
  
  if (reconnectChecker == false && WiFi.status() != WL_CONNECTED){
    reconnectChecker = true;
    WiFi.reconnect();    
  }
  else if (WiFi.status() == WL_CONNECTED && reconnectChecker == true){
    reconnectChecker = false;
  }
  
}


void setup()
{ 
   reconnectChecker = false;

  Serial.begin(115200);//fixed at 115200 bps for all platforms
  Serial.println("Connecting"); // HELLO STRING - ALL COMMENTS SENT IN !....! FORMAT
  Serial.setDebugOutput(true);

  char hostString[32] = {0};  
  sprintf(hostString, "arnido-ir-esp%06X", ESP.getChipId());

  wifiManager.setDebugOutput(true);
  wifiManager.setSaveConfigCallback(saveConfigCallback);
  wifiManager.addParameter(&custom_devicename);
  wifiManager.setBreakAfterConfig(true);
  
  wifiManager.setTimeout(180);
  wifiManager.setConnectTimeout(20);

  wifiManager.getSSID();
  wifiManager.getPassword();
  
  WiFi.setOutputPower(20.5);
  
 if(!wifiManager.autoConnect(hostString, update_password)) {
    Serial.println("Could not connect wifi!!!!!");
    delay(3000);
    //reset and try again, or maybe put it to deep sleep
    ESP.restart();
    delay(5000);
    return;
  }   

  delay(50);
  

  if (!MDNS.begin(hostString)) {
      while(1) { 
        delay(1000);
      }    
  }       
  
  server.on("/", homepage);      
  server.on("/index.html", homepage);      
  
  server.begin();

  delay(0);    
  
   MDNS.addService("arnido-ir", "tcp", 80); // Announce esp tcp service on port 8080
   MDNS.addServiceTxt("arnido-ir", "tcp", "devicename",  ((const char *)devicename));  

   connectionCheck.attach(240, connectionCheckHandler);
}
void loop() {

}
```

### Debug Messages

I have set Serial.setDebugOutput(true); and look at the logs. Here are the logs with 2.3.0 version ;

```
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.6.169
pm open,type:2 0
Invalid WEP key *******
ap_loss
state: 5 -> 0 (0)
rm 0
pm close 7
reconnect
scandone
no ARMAKOM found, reconnect after 1s
reconnect
scandone
no ARMAKOM found, reconnect after 1s
reconnect
no ARMAKOM found, reconnect after 1s
reconnect
scandone
no ARMAKOM found, reconnect after 1s
reconnect
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with ARMAKOM, channel 6
dhcp client start...
ip:192.168.6.169,mask:255.255.255.0,gw:192.168.6.1
pm open,type:2 0

```
Here are the logs with 2.4.0 version ;

```
connected with ARMAKOM, channel 1
dhcp client start...
ip:192.168.6.169,mask:255.255.255.0,gw:192.168.6.1
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.6.169
pm open,type:2 0
Invalid WEP key *****
ap_loss
reconnect
state: 5 -> 0 (0)
rm 0
pm close 7
f r0, scandone

```

It waits but it doesnt reconnect wifi network again .  (Connection State is most probably WL_IDLE_STATUS)

**Comment by igrr** [comment] 2018-03-08 10:17
Could you please

1. update the PR description to include the sketch used to reproduce this issue
2. install version 2.4.1 using boards manager and try again

**Comment by mustafayuce33** [comment] 2018-03-08 11:25
I have uploaded a piece of code. Here in our office when i reboot modem device , esp catches this issue and tries to reconnect again. But sometimes it doesnt. It stops somewhere in the code. When i look at the Wifi.Status() it looks WL_IDLE_STATUS. So that in my sketch i have added an timer that checks connection status and if it is not "connect" then i call "reconnect" function. 

And i also install latest git version by help of  lihttps://github.com/esp8266/Arduino#using-git-version link. This might cause this issue?

**Comment by d-a-v** [comment] 2018-03-08 15:13
Can you try with
```WiFi.setSleepMode(WIFI_NONE_SLEEP);```

**Comment by tablatronix** [comment] 2018-03-08 18:05
This sounds alot like and issue I was seeing also, where I know the ap was exists, but scandone and says nope. hmm

**Comment by mustafayuce33** [comment] 2018-03-08 18:08
Hi dave. Ok i will try your suggestion. And leave feedback again.

**Comment by mustafayuce33** [comment] 2018-03-08 18:11
Hi tablatronix

I am actually trying with theatest git version. It is not solved i think.

**Comment by tablatronix** [comment] 2018-03-08 18:19
You'll need a smaller minimal sketch to reproduce, one with no libraries.

**Comment by tablatronix** [comment] 2018-03-08 23:11
I could not reproduce with basic sketch and staging, tried all sorts of stuff. Did not try the example sketch there are too many libs and variables

**Comment by mustafayuce33** [comment] 2018-03-09 06:18
tablatronix , Thank you for your help. The example sketch is no so much different from basic sketch. I dont encounter this problem with some modems . Here at our office there is a modem brand name is "GrandStream". This modem causes this problem sometimes.

**Comment by devyte** [comment] 2018-07-13 19:21
There have been several fixes merged since this was opened, especially into the lwip glue. The current connection status has thoroughly tested. If there are problems connecting to a specific wifi router, the problem is either in the router, in which case there is nothing we can do, or in Espressif's SDK, in which case there is nothing we can do in this repo.
Closing.

**Closed by devyte** 2018-07-13 19:21 UTC
