### ISSUE TITLE
arduino.esp8266.com is down

### ISSUE THREAD

**Issue by ProfFan** [esp8266/Arduino#4403] opened 2018-02-20 17:10 UTC
### Description

Problem description

The site `arduino.esp8266.com` is down. Unable to retrieve the board definition and it also made current installations unusable.

**Comment by devyte** [comment] 2018-02-20 17:57
I can't reproduce this. Must have been a transient.
Closing.

**Closed by devyte** 2018-02-20 17:57 UTC

**Comment by sparklingsparklers** [comment] 2018-02-20 18:06
Was also down for me when I last checked.

**Comment by igrr** [comment] 2018-02-20 18:29
Was down between 20/02/2018 23:06:37 and 21/02/2018 01:27:37. Sorry for the trouble.
