### ISSUE TITLE
NodeMCU Serial Port error message: ets Jan 8 2013, rst cause:4, boot mode:(3,6)

### ISSUE THREAD

**Issue by EdCaneda** [esp8266/Arduino#7318] opened 2020-05-20 04:02 UTC
### Basic Infos

- [/ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:                      NodeMCU 1.0, ESP-12E module
- Core Version:			I have no idea
- Development Env:		Arduino IDE 1.8.9
- Operating System:		Windows

**Settings in IDE**

- Module:  			NodeMCU 1.0, ESP-12E module
- Flash Mode:			N/A
- Flash Size: 		        4MB
- lwip Variant:                   v2 Lower Memory
- Reset Method:		N/A
- Flash Frequency:	        N/A
- CPU Frequency:		80Mhz
- Upload Using:		OTA
- Upload Speed:                115200

### Problem Description
Here's the screenshot of the serial log below. Anyone who has existing solutions to this, please provide the link in the comments below. I appreciate it .
![image](https://user-images.githubusercontent.com/54743084/82403579-c7b9cf00-9a91-11ea-8642-682b85ee4612.png)

###Sketch
### Debug Messages

None
Debug messages go here
No debug done yet

**Comment by pfeerick** [comment] 2020-05-20 09:08
Examining the list of reset causes and boot modes indicates that your problem is being caused by a watchdog reset. This is confirmed by the fourth line of output stating `wdt reset`. It is likely something in your code is locking the ESP8266 up for more than 6 seconds, hence the reset. Without you providing the sketch / MVCE, it's impossible to diagnose. 

```
    reset causes:
        0:
        1: normal boot
        2: reset pin
        3: software reset
        4: watchdog reset

    boot device:
        0:
        1: ram
        3: flash
```

**Comment by earlephilhower** [comment] 2020-05-20 14:44
No MCVE present, template not followed.  Closing.

Please use https://esp8266.com or https://gitter.im/esp8266/Arduino for general questions like this.

**Closed by earlephilhower** 2020-05-20 14:44 UTC

**Comment by EdCaneda** [comment] 2020-05-20 23:43
> Examining the list of reset causes and boot modes indicates that your problem is being caused by a watchdog reset. This is confirmed by the fourth line of output stating `wdt reset`. It is likely something in your code is locking the ESP8266/NodeMCU up for more than 6 seconds, hence the reset. Without you providing the sketch / MCVE, it's impossible to diagnose.
> 
> ```
>     reset causes:
>         0:
>         1: normal boot
>         2: reset pin
>         3: software reset
>         4: watchdog reset
> 
>     boot device:
>         0:
>         1: ram
>         3: flash
> ```

**Hi @pfeerick , I got this code from online. It was wrong a couple of time . Sudden after few days, it returns the error.

Here's the code below:**

/*********
  Rui Santos
  Complete project details at http://randomnerdtutorials.com  
*********/

// Load Wi-Fi library
#include <ESP8266WiFi.h>

// Replace with your network credentials
const char* ssid     = "CCTN-WIFI";
const char* password = "francis123";

// Set web server port number to 80
WiFiServer server(80);

// Variable to store the HTTP request
String header;

// Auxiliar variables to store the current output state
String output5State = "off";
String output4State = "off";

// Assign output variables to GPIO pins
const int output5 = 5;
const int output4 = 4;

// Current time
unsigned long currentTime = millis();
// Previous time
unsigned long previousTime = 0; 
// Define timeout time in milliseconds (example: 2000ms = 2s)
const long timeoutTime = 2000;

void setup() {
  Serial.begin(115200);
  // Initialize the output variables as outputs
  pinMode(output5, OUTPUT);
  pinMode(output4, OUTPUT);
  // Set outputs to LOW
  digitalWrite(output5, LOW);
  digitalWrite(output4, LOW);

  // Connect to Wi-Fi network with SSID and password
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  // Print local IP address and start web server
  Serial.println("");
  Serial.println("WiFi connected.");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  server.begin();
}

void loop(){
  WiFiClient client = server.available();   // Listen for incoming clients

  if (client) {                             // If a new client connects,
    Serial.println("New Client.");          // print a message out in the serial port
    String currentLine = "";                // make a String to hold incoming data from the client
    currentTime = millis();
    previousTime = currentTime;
    while (client.connected() && currentTime - previousTime <= timeoutTime) { // loop while the client's connected
      currentTime = millis();         
      if (client.available()) {             // if there's bytes to read from the client,
        char c = client.read();             // read a byte, then
        Serial.write(c);                    // print it out the serial monitor
        header += c;
        if (c == '\n') {                    // if the byte is a newline character
          // if the current line is blank, you got two newline characters in a row.
          // that's the end of the client HTTP request, so send a response:
          if (currentLine.length() == 0) {
            // HTTP headers always start with a response code (e.g. HTTP/1.1 200 OK)
            // and a content-type so the client knows what's coming, then a blank line:
            client.println("HTTP/1.1 200 OK");
            client.println("Content-type:text/html");
            client.println("Connection: close");
            client.println();
            
            // turns the GPIOs on and off
            if (header.indexOf("GET /5/on") >= 0) {
              Serial.println("GPIO 5 on");
              output5State = "on";
              digitalWrite(output5, HIGH);
            } else if (header.indexOf("GET /5/off") >= 0) {
              Serial.println("GPIO 5 off");
              output5State = "off";
              digitalWrite(output5, LOW);
            } else if (header.indexOf("GET /4/on") >= 0) {
              Serial.println("GPIO 4 on");
              output4State = "on";
              digitalWrite(output4, HIGH);
            } else if (header.indexOf("GET /4/off") >= 0) {
              Serial.println("GPIO 4 off");
              output4State = "off";
              digitalWrite(output4, LOW);
            }
            
            // Display the HTML web page
            client.println("<!DOCTYPE html><html>");
            client.println("<head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
            client.println("<link rel=\"icon\" href=\"data:,\">");
            // CSS to style the on/off buttons 
            // Feel free to change the background-color and font-size attributes to fit your preferences
            client.println("<style>html { font-family: Helvetica; display: inline-block; margin: 0px auto; text-align: center;}");
            client.println(".button { background-color: #195B6A; border: none; color: white; padding: 16px 40px;");
            client.println("text-decoration: none; font-size: 30px; margin: 2px; cursor: pointer;}");
            client.println(".button2 {background-color: #77878A;}</style></head>");
            
            // Web Page Heading
            client.println("<body><h1>ESP8266 Web Server</h1>");
            
            // Display current state, and ON/OFF buttons for GPIO 5  
            client.println("<p>GPIO 5 - State " + output5State + "</p>");
            // If the output5State is off, it displays the ON button       
            if (output5State=="off") {
              client.println("<p><a href=\"/5/on\"><button class=\"button\">ON</button></a></p>");
            } else {
              client.println("<p><a href=\"/5/off\"><button class=\"button button2\">OFF</button></a></p>");
            } 
               
            // Display current state, and ON/OFF buttons for GPIO 4  
            client.println("<p>GPIO 4 - State " + output4State + "</p>");
            // If the output4State is off, it displays the ON button       
            if (output4State=="off") {
              client.println("<p><a href=\"/4/on\"><button class=\"button\">ON</button></a></p>");
            } else {
              client.println("<p><a href=\"/4/off\"><button class=\"button button2\">OFF</button></a></p>");
            }
            client.println("</body></html>");
            
            // The HTTP response ends with another blank line
            client.println();
            // Break out of the while loop
            break;
          } else { // if you got a newline, then clear currentLine
            currentLine = "";
          }
        } else if (c != '\r') {  // if you got anything else but a carriage return character,
          currentLine += c;      // add it to the end of the currentLine
        }
      }
    }
    // Clear the header variable
    header = "";
    // Close the connection
    client.stop();
    Serial.println("Client disconnected.");
    Serial.println("");
  }
}
