### ISSUE TITLE
WIFI CLIENT GET FROM WEB PROBLEM

### ISSUE THREAD

**Issue by michaelmnich** [esp8266/Arduino#4587] opened 2018-03-29 12:06 UTC
#### Platform

- Hardware:			        [ESP8266]
- Development Env:		[Platformio]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Nodemcu]
- Flash Mode:			[qio|dio]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|9600]

### Problem Description

Hi i was trying to make one of yours tutorial:
http://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/client-examples.html
I tried on 2 different network and the same situation.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

Code: -----------------------------------------------------------------------------------
#include <ESP8266WiFi.h>

const char* ssid = "Ewaaa&Spolka";
const char* password = "$qazxsw123#cze";

const char* host = "http://localhost/"; //THIS IS MY LOCAL SERWER WWW ANYWAY Anny other web page do not make difference.

void setup()
{
Serial.begin(9600);
Serial.println();

Serial.printf("Connecting to %s ", ssid);
WiFi.begin(ssid, password);
while (WiFi.status() != WL_CONNECTED)
{
delay(500);
Serial.print(".");
}
Serial.println(" connected");
}

void loop()
{
WiFiClient client;

Serial.printf("\n[Connecting to %s ... ", host);
if (client.connect(host, 80))
{
Serial.println("connected]");

Serial.println("[Sending a request]");
client.print(String("GET /") + " HTTP/1.1\r\n" +
             "Host: " + host + "\r\n" +
             "Connection: close\r\n" +
             "\r\n"
            );

Serial.println("[Response:]");
while (client.connected())
{
  if (client.available())
  {
    String line = client.readStringUntil('\n');
    Serial.println(line);
  }
}
client.stop();
Serial.println("\n[Disconnected]");
}
else
{
Serial.println("connection failed!]");
client.stop();
}
delay(5000);
}

Code: -----------------------------------------------------------------------------------

### Debug Messages

still Geting:

[Connecting to http://localhost/ ... connection failed!]

[Connecting to http://localhost/ ... connection failed!]

[Connecting to http://localhost/ ... connection failed!]

[Connecting to http://localhost/ ... connection failed!]

**Comment by devyte** [comment] 2018-03-29 12:32
Closing as duplicate of #4586 .

**Closed by devyte** 2018-03-29 12:32 UTC
