### ISSUE TITLE
SPIFFS read speed varies depending on location in file

### ISSUE THREAD

**Issue by 2dom** [esp8266/Arduino#2450] opened 2016-08-28 20:00 UTC
#### Hardware

Hardware:           ESP-12
Core Version:       2.2
### Description

I experience good read speed over most of the file system however sometimes it is terrible.

E.g. if I have a 2MB image file, the read speed is extremely slow  in some parts of the file (37ms / byte) but ok in others (<1ms / byte).
### Settings in IDE

Module:             NodeMCU 1.0
Flash Size:         4MB/3MB SPIFFS
CPU Frequency:      160MHz
Flash Mode:         ?
Flash Frequency:    ?
Upload Using:       SERIAL
Reset Method:       Nodemcu
### Sketch

``` cpp
#include "FS.h"
#include <Arduino.h>


void setup() {
Serial.begin(115200);
SPIFFS.begin();

}

void loop() {

    File my_file = SPIFFS.open("/starwars.bmp","r");
    unsigned long start_time;
    unsigned long delta;
    unsigned long byte_count=0;
    while (my_file.available()){

       start_time=millis();
       my_file.read();

       delta = millis()-start_time;
       byte_count++;
       if (delta > 5)
          Serial.println("Byte no: " + String(byte_count) + ", read latency: " + String(delta));
    }
   my_file.close();
   Serial.println("Loop");

}

### Debug Messages
Byte no: 2173912, read latency: 38
Byte no: 2173913, read latency: 37
Byte no: 2173914, read latency: 37
Byte no: 2173915, read latency: 38
Byte no: 2173916, read latency: 37
Byte no: 2173917, read latency: 37
Byte no: 2173918, read latency: 38
Byte no: 2173919, read latency: 37
Byte no: 2173920, read latency: 37
Byte no: 2173921, read latency: 37
Byte no: 2173922, read latency: 37
Byte no: 2173923, read latency: 37
Byte no: 2173924, read latency: 37
Byte no: 2173925, read latency: 38
Byte no: 2173926, read latency: 37
Byte no: 2173927, read latency: 37
Byte no: 2173928, read latency: 37
Byte no: 2173929, read latency: 38
Byte no: 2173930, read latency: 37
Byte no: 2173931, read latency: 37
Byte no: 2173932, read latency: 38
Byte no: 2173933, read latency: 37
Byte no: 2173934, read latency: 37
Byte no: 2173935, read latency: 37
Byte no: 2173936, read latency: 37
...
...


```

messages here

```


```

**Comment by WereCatf** [comment] 2016-08-29 07:07
Does the drop in performance happen around 2147483648 bytes read?

**Comment by 2dom** [comment] 2016-08-29 13:54
The first drop happens at 2173912 and lasts a few 10 kBs ....

**Comment by WereCatf** [comment] 2016-08-29 14:33
You could try a newer SPIFFS from https://github.com/pellepl/spiffs -- it's at v3.6, whereas the SPIFFS in the ESP8266 Arduino-core is v3.4. If you do test it I'd like to hear your results. Also, if it doesn't resolve the issue you could open an issue in @pellepl 's code as he's much more likely to be able to tell you what the problem is than anyone here.

**Comment by WereCatf** [comment] 2016-08-29 14:37
The SPIFFS v3.6 has this note:
> Optimize SPIFFS_read for large files

**Comment by WereCatf** [comment] 2016-08-29 17:20
I just tested this and I can confirm that on SPIFFS v3.4 the performance-drop happens, but when I updated to v3.6 it disappeared -- no drops, whatsoever. My version of the ESP8266-core with SPIFFS 3.6 is available at https://github.com/WereCatf/Arduino if you wish to test.

**Comment by 2dom** [comment] 2016-08-29 19:58
I tested it with the v3.6 version ... it works without slow down. Great stuff. Do you have any idea when the ESP8266-core will be updated. I stumbled over this issue twice now.

**Comment by WereCatf** [comment] 2016-08-29 20:23
Considering that, as far as I know, @igrr and whoever else are working on this core for free and on their own time I don't think they have any sort of a schedule or anything, so there's no way of saying when they might take a look at this. Just be patient, I'm sure someone will at least comment on this topic and/or the pull-request eventually.

**Comment by 2dom** [comment] 2016-08-30 20:16
I am patient ... just asking. What you guys are doing is amazing - cheers to you!

**Comment by devyte** [comment] 2017-10-14 03:54
@2dom Current SPIFFS version is 0.3.7, so this is already done.
Closing as resolved.

**Closed by devyte** 2017-10-14 03:54 UTC
