### ISSUE TITLE
Feature Request: Soft SPI compatible with ESP-01? (libraries provided for starting point)

### ISSUE THREAD

**Issue by Matthew-Bradley** [esp8266/Arduino#2204] opened 2016-06-28 17:23 UTC
### Basic Info
Feature request: Software SPI host that can be run on an ESP-01, with the four existing GPIO (including TX and RX)

#### Hardware
Hardware:			?ESP-01?
Core Version:      	?2.1.0-rc2?

### Description

Hi.
First off, I wanna say am absolutely astounded what igrr (thanks for https!) and company have managed to accomplish here. You guys deserve a dozen rounds of applause.

I'm currently running an ESP-01 (and have an SPI card reader with a fairly simple library) and was wondering if it's possible that you might consider implementing a software SPI host library similar to the soft I2C that already exists (and allows configuration of the GPIO pins it uses). I looked into doing this myself, and found some existing software SPI libraries that might make the job easier:

https://github.com/greiman/DigitalIO/tree/master/DigitalIO/src

It uses 'fast' digital functions (fast pinmode, fast digitalwrite, fast digitalread) but those *should* be easy to replace if you're familiar with the way the GPIO is accessed.

There's also this library which provides soft SPI for the teensy and a bunch of others, which might also be of use, but doesn't have a mapping defined for the ESP8266:

https://github.com/niteris/ArduinoSoftSpi

**Comment by igrr** [comment] 2016-06-30 16:09
Closing as duplicate of #33. That issue also has some pieces of code, in assembly.

**Closed by igrr** 2016-06-30 16:09 UTC
