### ISSUE TITLE
Async connect for WiFiClient ?

### ISSUE THREAD

**Issue by pgScorpio** [esp8266/Arduino#2180] opened 2016-06-22 22:32 UTC
#### Hardware
Hardware:		ESP-12
Core Version:      	2.2.0

### Description

Problem description

At this moment WiFiClient::connect() is blocking until connected or error.

Especially when the server you are connecting to is offline this causes your sketch to freeze for a few seconds...... In a lot of cases this is not acceptable.

I think it should be possible to start a connect without blocking and check from loop if the connect succeeded or not.

**Comment by chaeplin** [comment] 2016-06-23 06:56
this ? https://github.com/me-no-dev/ESPAsyncTCP

**Comment by igrr** [comment] 2016-06-23 07:06
Also, closing as duplicate of #922.

**Closed by igrr** 2016-06-23 07:06 UTC

**Comment by miguelpom** [comment] 2016-12-22 16:28
Hi, guys.
@igrr: this issue is kind of related to the one posted in #922. However, the actual problem with the blocking timeout of the function WifiClient.connect() isn't really addressed or solved. Or so it seems to me.
Can we reanimate this thread, please?
