### ISSUE TITLE
ESP12 dont start

### ISSUE THREAD

**Issue by kamilbystryk** [esp8266/Arduino#4295] opened 2018-02-05 11:59 UTC
#### Hardware
Hardware:			ESP-12
Core Version:      	2.4.0

### Description

I have problem with program starts on ESP12 device (ESP8266MOD, producer - DOIT). After start i see don't readable characters on serial. Program starts only, when I choose "generic ESP8255 module". I check - inside module is ESP8266 and SPI flash. No one sketch starts on ESP8266 generic stettings (e.g. blink).
On AI thinker ESP12 program run without problems.
I read settings by  Esspressiff download tool:
Problem module:
flash vendor:
C8h : GD
flash devID:
4016h
QUAD;32Mbit
crystal:
26 Mhz

"good" module:
flash vendor:
EFh : WB
flash devID:
4016h
QUAD;32Mbit
crystal:
26 Mhz

How can I solve problem?

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 	4MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		ck

**Comment by RudyFiero** [comment] 2018-02-06 02:29
This is not the place for your problem. This is for issues regarding the ESP8266 Arduino software. Issues are bugs or feature requests. 

Have a look at this. 
https://arduino-esp8266.readthedocs.io/en/latest/boards.html

http://www.esp8266.com/ is a more appropriate place for asking about new user problems. But try and be specific in what you have done. The information you provided here is inadequate. Explaining how you have the module connected and powered would be a good start.

**Comment by devyte** [comment] 2018-02-06 04:03
This gives a hint:
flash vendor:
C8h : GD

Closing as duplicate of #3616 .

**Closed by devyte** 2018-02-06 04:03 UTC

**Comment by Karpesh** [comment] 2018-02-18 20:20
I solved the problem for my case.
This flash has DIO mode, not QIO.  I switched the mode in my makefile and all works fine now.
