### ISSUE TITLE
Huzzah board crashes on deep sleep wake up cycle, (pin 16 and rst connected)

### ISSUE THREAD

**Issue by Zyxmn** [esp8266/Arduino#2050] opened 2016-05-23 14:55 UTC
I have been testing the deepsleep function on the huzzah board and the board crashes average after 9 to 14 consecutive deepsleep and wakeup cycles.

Sometimes it crashes with only 3 to 4 deepsleep and wakeup cycles and sometimes goes to about 20 plus cycles before crashing.

Here is the sketch I use:

#include

void setup() 
{
Serial.begin(115200);
Serial.println();
Serial.println(ESP.getResetReason());
Serial.println(); 
delay(100);
ESP.deepSleep(100000, WAKE_RF_DEFAULT); // Sleep for 1 second
}

void loop() 
{

}

**Comment by igrr** [comment] 2016-05-23 15:24
Closing as duplicate of #2049

**Closed by igrr** 2016-05-23 15:24 UTC
