### ISSUE TITLE
Can't Set SSID in AP Mode with latest version

### ISSUE THREAD

**Issue by kapyaar** [esp8266/Arduino#1123] opened 2015-12-01 04:28 UTC
I am testing the latest staging version and the Accesspoint example seems to set the default SSID (ESP_XXXX) even after doing WiFi.softAP("New_SSID") in setup.

**Comment by igrr** [comment] 2015-12-01 04:51
Duplicate of #1054 #1103, fixed in git and stable versions.

**Closed by igrr** 2015-12-01 04:52 UTC
