### ISSUE TITLE
MTU Bug

### ISSUE THREAD

**Issue by Gulaschcowboy** [esp8266/Arduino#3569] opened 2017-09-04 08:50 UTC
Hello @igrr 

in the release notes for the SDK  2.1.0 (https://github.com/espressif/ESP8266_NONOS_SDK/releases) I read under Topic LWIP: 3. "Fix MTU negotiate bug."
It seems that I'm affected by it.
Are there plans to update the SDK from 2.0.0_16_08_09 to 2.1.0?

**Comment by timpur** [comment] 2017-09-05 10:05
Having problems with MTU also (i think) so it would be good to see if this helps.

**Comment by igrr** [comment] 2017-09-12 12:48
Closing this as duplicate of https://github.com/esp8266/Arduino/issues/2437. Please follow that link and click "subscribe" to get updates.

You can also follow the status of 2.1.0 update here: https://github.com/esp8266/Arduino/pull/3278.

**Closed by igrr** 2017-09-12 12:48 UTC
