### ISSUE TITLE
flash vendor ???

### ISSUE THREAD

**Issue by jarda195** [esp8266/Arduino#3618] opened 2017-09-17 19:28 UTC
how differ ESP WROOM 02 flash vendor: A1h : FM (32MB) and ESP WROOM 02 flash vendor: C8h : GD (16MB)

both buy as ESP WROOM 02 but flas size is different..

**Comment by vicnevicne** [comment] 2017-09-17 20:45
@jarda195 this is not the right place to ask for help for your particular project or module. This is an issue tracker, meant for tracking issues in the core.
Please refer to esp8266.com or stackoverflow for assistance.

**Comment by devyte** [comment] 2017-09-17 23:07
Closing as duplicate of #3616.

**Closed by devyte** 2017-09-17 23:07 UTC
