### ISSUE TITLE
Wrong subnetMask using DHCP?

### ISSUE THREAD

**Issue by hinzundcode** [esp8266/Arduino#1249] opened 2015-12-18 21:42 UTC
If I use DHCP WiFi.gatewayIP() and WiFi.subnetMask() return the correct values from my DHCP server (subnetmask 255.255.0.0), but I can't access other devices from the subnet. It only works if I set the same values manually using WiFi.config(). Any ideas?

```
Connected. IP Address: 10.0.2.3
10.0.0.1
255.255.0.0
connection failed
```

Code: https://gist.github.com/schokocappucino/5f6e23cf0c02652f7d92
##

**Comment by devyte** [comment] 2017-10-19 07:00
I can't reproduce this with latest git. Closing.

**Closed by devyte** 2017-10-19 07:00 UTC
Labels: type: troubleshooting
