### ISSUE TITLE
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

### ISSUE THREAD

**Issue by ChazTuna** [esp8266/Arduino#6758] opened 2019-11-12 05:35 UTC
This happens with Version 2.6.0 but not Version 2.5.2

Device:  Adafruit HUZZAH ESP8266
IDE:  Arduino 1.8.9  Windows 10
BAUD:  115200

Just changing back to Version 2.5.2 and recompiling and doing the upload works fine, but not Version 2.6.0

**Stats on upload with Version 2.5.2:**
esptool.py v2.6
2.6
esptool.py v2.6
Serial port COM3
Connecting....
Chip is ESP8266EX
Features: WiFi
MAC: *******************
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 335184 bytes to 236579...

Writing at 0x00000000... (6 %)
Writing at 0x00004000... (13 %)
etc.

**Comment by devyte** [comment] 2019-11-12 05:41
Duplicate of #6755.  
Closing.

**Closed by devyte** 2019-11-12 05:41 UTC
