### ISSUE TITLE
Alpha build for windows dowsn't start

### ISSUE THREAD

**Issue by Pablotis** [esp8266/Arduino#237] opened 2015-05-13 18:47 UTC
![image](https://cloud.githubusercontent.com/assets/10696506/7618261/2b6ac31a-f9b1-11e4-94bc-a255560a0863.png)

**Comment by igrr** [comment] 2015-05-13 18:48
Duplicate of #223?

**Comment by Pablotis** [comment] 2015-05-13 18:53
Yes, I didn't see it, sorry.

**Closed** 2015-05-13 18:54 UTC
