### ISSUE TITLE
STA not working is start AP first

### ISSUE THREAD

**Issue by progtronix** [esp8266/Arduino#7115] opened 2020-02-27 14:51 UTC
### Basic Infos

- [X ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ X] I have tested that the issue is present in current master branch (aka latest git).
- [ X] I have searched the issue tracker for a similar issue.
- [ X] If there is a stack dump, I have decoded it.
- [ X] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-01]
- Core Version:			[2.2.1+119]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows 10|Debian 10]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[dio]
- Flash Size: 		        [4MB]
- lwip Variant:                  [v2 Higher Bandwidth]
- Reset Method:		[nodemcu]
- Flash Frequency:	        [40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:              [115200]

### Problem Description
If the WIFI_AP is started before WIFI_STA then after roughly 5-10 main loops, it will not connect to the station, it just gets stuck in the while(WiFi.status() != WL_CONNECTED).
If the WIFI_AP is started after WIFI_STA, everything works normal.

i have tried putting the disconnects at the top of sketch and at the bottom with same results with respect to which is started first, i have also tried disconnecting AP before STA and then tried STA before AP, all have same effect depending on if AP or STA is started first.

have tried using WiFi.mode() in replacement of disconnects and also tried disconnects with true and false but all result in the same hang if the AP is started after the STA

i have provided a small sketch that will reproduce the problem with  #define GOOD/BAD  to switch between the two positions of where AP is started to easily reproduce the problem

i have also provided two debug logs, the bad one when (#define BAD) and also the (#define GOOD)

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <ESP8266WiFi.h>

const char *ssid = "";
const char *pass = "";
uint16_t loopC = 1;

#define BAD // GOOD/BAD select where AP is started

void setup() {
  Serial.begin(115200);
  Serial.println();
}

void loop() {
  Serial.printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   %d\n", loopC++);

#ifdef GOOD
  Serial.printf("AP-BEGIN = %d\n", WiFi.softAP("test", pass));
#endif

  Serial.printf("STA-BEGIN = %d\n", WiFi.begin(ssid, pass));
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print('.');
    delay(500);
  }

#ifdef BAD
  Serial.printf("AP-BEGIN = %d\n", WiFi.softAP("test", pass));
#endif

  Serial.printf("STA-DISCONNECTING = %d\n", WiFi.disconnect(true));
  Serial.printf("AP-DISCONNECTING = %d\n", WiFi.softAPdisconnect(true));
}

```

### Debug Messages
DEBUG LEVEL = CORE+WIFI+HTTP_UPDATE+UPDATER+OTA+OOM+MDNS
(didn't know which i wanted so i chose one with wifi+core in it)

```
---------------------------------------------------------------------------------------------------------------------------------
THE GOOD
---------------------------------------------------------------------------------------------------------------------------------
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   1
bcn 0
del if1
usl
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
AP-BEGIN = 1
mode : sta(5c:cf:7f:8e:95:64) + softAP(5e:cf:7f:8e:95:64)
add if0
STA-BEGIN = 6
.wifi evt: 8
....wifi evt: 2
.scandone
state: 0 -> 2 (b0)
.state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 

connected with VM2G, channel 13
dhcp client start...
wifi evt: 0
ip:192.168.0.219,mask:255.255.255.0,gw:192.168.0.1
wifi evt: 3
state: 5 -> 0 (0)
rm 0
del if0
mode : softAP(5e:cf:7f:8e:95:64)
STA-DISCONNECTING = 1
bcn 0
del if1
usl
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
bcn 0
del if1
usl
mode : null
AP-DISCONNECTING = 1
wifi evt: 1
STA disconnect: 8
wifi evt: 8
wifi evt: 8
---------------------------------------------------------------------------------------------------------------------------------
THE BAD
---------------------------------------------------------------------------------------------------------------------------------
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   5
mode : sta(5c:cf:7f:8e:95:64)
add if0
STA-BEGIN = 6
.wifi evt: 8
.....scandone
state: 0 -> 2 (b0)
.state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 
........state: 5 -> 2 (2a0)
rm 0
wifi evt: 1
STA disconnect: 2
..reconnect
state: 2 -> 0 (0)
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 
........state: 5 -> 2 (2a0)
rm 0
wifi evt: 1
STA disconnect: 2
..reconnect
state: 2 -> 0 (0)
.scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 
........state: 5 -> 2 (2a0)


AT THIS POINT... IT JUST KEEPS REPEATING FROM [rm0] -> [........state: 5 -> 2 (2a0)]

```

**Comment by devyte** [comment] 2020-02-27 15:31
Of all WiFi startup sequences I have ever seen, this has got to be one of the worst. At the very least, this will burn through your flash in no time, because you're not even using persistent(false).
I have to wonder that there's a "GOOD" at all, I wouldn't expect that order to work either. 
Anyways:
You're repeatedly setting up the wifi on every loop pass. That's not how it works, the setup is a process that happens in the SYS context, and you have to give it some time. Then, once it's set up, you don't immediately set it up again. So:
-Either put your wifi sequence code in setup(), or leave it in the loop, but then wrap it in an if condition so that it gets executed only if not already set up. 
-Please study the WiFi examples included with the core. And maybe some of the non WiFi examples as well. 
-Look at the wifi event system to handle wifi state changes. Be aware that the callbacks you set up execute in SYS, and are therefore subject to the SYS restrictions (no yield/delay, timing etc). Readthedocs for further info. 

Closing due to user error.

**Closed as completed** 2020-02-27 15:31 UTC

**Comment by progtronix** [comment] 2020-02-27 16:13
this is not a startup sequence, this is a way to try and re-create the problem i was getting.

im not concerned with burning flash chips... on top of the bag of flash chips i have... i have an equal bag of esp modules and that in no way is related to the problem as i have another sketch not using it with same results... again... burnt flash chip is of no concern here.

then what is the required time? and if there is a required time... why is it only noticeable given this exact example? and why is there not a wait for disconnect of either STA or AP before it can be successfully started again? if i remove the AP then STA will start and stop as many times as i want (also AP on its own is ok)... likewise... if i start AP before STA it will always work... so given every other way works and this one does not... is that still a user error? really? i have another sketch that i was working on that led me to find this problem... that sketch actually checks for an IP address and only disconnects and reconnects if the IP is not present from WiFi.localIP.... it will not do anything if there is a connection that i made and there is an IP for the iface i wanted.... sooooo..... when you say dont do it every loop.... i came to this problem from a sketch that doesnt do it every loop all because i started WIFI_AP_STA.... make it connect to another ESP, then unplug the other ESP... and because i started AP first, eventually it will no longer connect after X loops (roughly 5)

this other sketch runs like a service where i switch to a mode in setup, then just monitor and reconnect if the connection drops. but if i start AP first and leave it running... then after so many attempts at STA reconnect... i will get the error... so i broke it down into what i thought would be a correct way to reproduce the problem.

and if i cannot simply stop and start the STA whenever i want.. then what is the proper sequence/timing or flags to wait for to know when i can issue a disconnect and then reconnect for STA??? also bear in mind that this info is not documented on this magic sequence/timing  and if i dont enable AP 'BEFORE' STA.... i dont need to know magic sequence/timing and everything works.

im not saying i dont have more to learn... clearly i do... but from trying different things a every other way working except this one... i cant see how this is NOT a bug.

if i cant simply start STA again when i want... then where is the WiFi.waitForLoopCountBeforeReconnect? if this is internal... why is it even letting me disconnect / reconnect with both return codes from disconnect and reconnect return the same whether using  the GOOD or BAD define? which means this magic sequence/timing cannot be checked... it must be known and programmed around, a little misleading when every other way works except this catch you out 5 loops down the line

but what if i have AutoReconnect set to true and it tries more than 10 times and fails?, so i wanted to check myself and reconnect manually based on conditions and the only problem is if i start AP first

i have gone over many examples ...  and the documentation for arduino esp8266 is not good enough to decipher from it this particular situation (and i doubt ever will be) ... if there is  a background time period... then should it not be check-able?

**Comment by progtronix** [comment] 2020-02-27 16:45
if i make a connection... wait for it to be connected by WiFi.status(), then disconnect and the disconnect returns true... than after that one would think you should just be able to start WiFi.begin again, this works with AP fine... it even works if AP is started before STA.

if there is something that "you have to give it some time" ... then why is this not checked at the start of either WiFi.begin() and fails if to early? or at the start of disconnect if the problem lies with disconnecting to fast? i did not just setup a connection after setting up a connection... i disconnected the STA, and then try to reconnect.

take this for example... if i started AP... then later started STA... then i sent a command to change to the SSID and PASS of STA... so i disconnect... and then WiFi.begin() with new SSID and PASS... wait for connect with wifi.status... but after 5 disconnects... it will not reconnect simply because i started AP first.

then what is the correct procedure to stop the STA .... change the SSID+PASS ... then reconnect? because if the procedure is not what i have done but with more time in between and only if AP is started after STA... then i would could this a developer error/oversight... as its only one use case, its not reproducible if AP is not used or started after STA... begin and disconnect dont care about anything in background taking any extra time before it just blindly stops and starts again... and there is nothing to check/wait for before i can just STOP then START a STA connection

**Comment by devyte** [comment] 2020-02-27 21:05
About flash burning: 
You're posting to a public tracker, so your sketch is visible by anyone. If somebody were to decide to try it out for something, or worse: adopt it in some form in a real application, their flash would burn. So even if **you** have a "bag of flash chips" and an "equal bag of ESP modules", your wifi startup sequence must be identified as being bad, because others likely don't have such bags, so burnt flash is very much a concern. Simply put: your sketch is subtly dangerous => closed issue. 
So use persistent(false);

Also, did you wipe the flash between tests with GOOD/BAD defines? I'm betting no. Because you're not using persistent(false), previous settings are relevant and are attempted on boot before your sketch even gets to setup().

About "required magic time":
If your original code did the wifi sequence not in the loop, then why did you post a sketch with the sequence in the loop? That makes no sense. Your sketch has the exact same error as calling WiFi.begin() without guards in the loop: Repeated calls in rapid succession won't work. You have to trigger the sequence, then give it time to finish. Ideally, let the loop return and check back later. 
In addition, there are wifi routers that don't accept too many connect/reconnects too quickly, and can ignore you for a few seconds.

About your report and your sequence:
You said:
> [X] I have tested that the issue is present in current master branch (aka latest git).

But then:
> Core Version: [2.2.1+119]

Which is beyond ancient. We don't provide support for older releases, because we have a linear release model.

In addition, you said:
> [X] I have searched the issue tracker for a similar issue.

And your sketch uses:
```cpp
while (WiFi.status() != WL_CONNECTED) {
...
```
So you're waiting for the station connection to be done with WiFi.status(), but there are open issues about status() not returning a correct value (this is related to the SDK, see next point below). did you check that using the wifi event system to set a flag and checking that flag in the loop works? I'm betting no. If the wifi event system works, but status() is wrong, then your report is a duplicate of a known issue.

Then:
Keep in mind that our core is a code layer over Espressif's SDK, which is a black box, so we know very little about the internals, and the documentation about functional behavior is almost nonexistent. There may be a bug in our core, or there may be a bug in the SDK, or there may be some interaction between what we do and what the SDK expects to be done. Also, there are likely things that aren't possible. One such example was addressed not too long ago: changing wifi mode seems to be asynchronous, and there doesn't seem to be a realistic way of knowing when the transition is really done. This worked ok before, but then suddenly popped up for no reason at some point, and manifested with random crashes. The solution implemented was to add a delay(something) after a mode switch, which sucks, but it's what we have.

So I'm not saying the behavior you observe doesn't exist, it may very well be real. However, your report here is all of wrong, incomplete, and dangerous, and possibly redundant on top.

Finally, please cool down, take a few breaths, finish thinking your way through the problem, finish your investigation, check against the examples in case there is one that inits the wifi in your "BAD" order, and try to create a corrected MCVE that reproduces it. If you can reach that point, open a new issue and report your (complete) findings. We can continue discussing there.

On a personal note. my own app, which has been rock solid for a long time, and serves me as kind of core health checker, forcibly sets up the AP first (whether enable or disable) and STA second, so it's a variation of your "GOOD" sequence. If something goes wrong, it waits a short while, then tries again in the same order. I don't think I've ever tried the other way around.

**Comment by progtronix** [comment] 2020-02-27 22:14
well sorry about that.. didnt think of it like that.. i just tried to produce the smallest code possible to reproduce the problem because if my STA lost and IP address, then that code was what i was running if the two checks failed (check which mode we are in WiFi.getMode() and check the IP) and then try and disconnect and reconnect and waitForConnectResult(6000) then it will go through main loop and try again... thats when the error was happening so i found the smallest code and posted it... but note taken on the safety thing.

yes i always have it set erase all flash contents ... hence the bag 'o' chips on the ready :)

i just installed using git from the install page and using debian 10, i thought that was the latest version? if not how do i get the changes as they are made?

i would not of known to search for the status() problem as it was not really apparent that was the area of the problem, if i switch things around it works so why should i suspect that? maybe because you know about it you may relate it easier but i did search for STA not connecting and the like... also.. i checked some examples just now in ESP8266WiFi and i couldnt find one that uses persistent(false) to help peoples flash and they used while (WiFi.status() != WL_CONNECTED) ... the same examples you told me to go study perhaps? :)

anyways, in my original code i was starting the STA before AP, but if i just swap the two main if blocks around so it goes through checking AP first... then STA... it works.
for now i am just going to do it the normal way, start it all once in setup and hope the reconnect always works... there was a time i used these and it didnt always work correctly.

i had a think about when you said it needs a little time so made some changes to the posted sketch... basically it just wrapped the connects and disconnects in two millis() timed if statements... the connects would go... then start a timer for the second if disconnects... so i could adjust the time between begin->disconnect  and also the time between disconnect->begin   and if i add an 8 second delay after STA connects before the disconnect happens... all is ok and that is 8 seconds after a 4 second connect time so the required magic time is about 12 seconds from begin  (connection or not)

anways... i think thats the end of this one... i think i just hit a bullet with a bullet which is easily avoided... but you made me scared to report something now ha and there is another i think i found where every time ESP STA looses connection to AP because i unplug the other ESP8266 in AP mode... my STA mode prints out the word "blob" in the serial monitor when serial is enabled... nothing in loop, should i open one or are you aware of this? i searched the word blob on git/goo but found nothing
