### ISSUE TITLE
Repository for esp8266 library broken?

### ISSUE THREAD

**Issue by henrybcn** [esp8266/Arduino#2613] opened 2016-10-17 19:18 UTC
I am trying to install the esp8266 library on the arduino ide and seems they are not available. Is the link broken?

I am following the instructions on the main page, but can not even see the library to install:
Enter http://arduino.esp8266.com/stable/package_esp8266com_index.json into Additional Board Manager URLs field. You can add multiple URLs, separating them with commas.

Is there any alternative to get it done?
Rgds,
henry

**Comment by WereCatf** [comment] 2016-10-18 00:15
Works just fine for me.

**Comment by 1-prop-head** [comment] 2016-10-20 15:55
If you past the link into the preferences you may not get the required carriage return line feed characters and this will cause the repository not to load properly.  Open the explore icon beside the text input box on the preferences and add a carriage return.  This will repair the issue and allow repository to load

**Comment by devyte** [comment] 2017-10-11 18:33
Can't reproduce, board manager is currently working. Closing.

**Closed by devyte** 2017-10-11 18:33 UTC
