### ISSUE TITLE
Missing #include <avr/pgmspace.h> for Adafruit FONA

### ISSUE THREAD

**Issue by architmuchhal12** [esp8266/Arduino#3327] opened 2017-06-02 19:35 UTC
I am using an Arduino ESP8266 along with Adafruit FONA 808,
While compiling, it gives me an error as - 

```
 #include <avr/pgmspace.h>

                          ^

compilation terminated
```

Do I need to add this file? And if yes, where would I need to make changes?
Thanks!

**Comment by pipi61** [comment] 2017-06-02 21:49
[http://lmgtfy.com/?q=esp8266+avr%2Fpgmspace.h](url)
first in the list:
[https://github.com/SodaqMoja/Sodaq_DS3231/issues/5](url)

**Comment by architmuchhal12** [comment] 2017-06-05 14:32
@pipi61 Thanks a lot! It helped. I could compile the program.

After compiling the program to the ESP8266 board (NodeMCU 1.0), this is what I get on the Serial Monitor of Arduino IDE -

```
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
```
I tried to test the FONA 808 module by uploading the FONA_Test example by making the following changes in the code -

```
#define FONA_RX D7
#define FONA_TX D8
#define FONA_RST D4
```

I am not sure as to why I am seeing the output of that kind on the Serial Monitor.

Please help me in this regard.

Thanks!

**Comment by devyte** [comment] 2017-09-05 23:59
#1749 may help. Also, be very careful about which pins you use, and how you configure them, and with your power supply. I use a 5V 20A power supply for development (yes, that's 20 amps) to make sure that any resets or whatever aren't due to dips in supply voltage due to power spikes (and this is a cell module, so it could well have power spikes).

Having said that, this is not the correct place to ask for support questions regarding an external lib. This is an issue tracker, meant to track issues in the core libs. Please ask at esp8266.com or stackoverflow for assistance with getting the FONA code to work with the ESP.
If you eventually do find an issue in the core libs, such as a missing/incorrect function or #define, feel free to open a new issue with the explanation, and add a full minimal sketch that reproduces it, so that action can be taken.
Closing.

**Closed by devyte** 2017-09-05 23:59 UTC

**Comment by Rhanem** [comment] 2018-03-25 22:24
i downloaded this file from here :
https://github.com/mikalhart/galileo-Pgmspace.h/
next i edit the line to: #include <pgmspace.h>
is working..
