### ISSUE TITLE
EEPROM write/put not checking every single byte

### ISSUE THREAD

**Issue by mamama1** [esp8266/Arduino#5767] opened 2019-02-15 20:16 UTC
Hi

it seems to me, that EEPROM.commit(), write and put don't check every single byte if it has changed (using the _dirty flag) but as soon as one byte gets changed, the whole area will be rewritten to flash.

Is this intended or was it some getting-things-done-whoopsie?

eg. I change just one byte but I have reserved 4k of EEPROM, all 4k will be erased and rewritten, if I understand the code correctly.

Thanks

**Comment by penfold42** [comment] 2019-02-15 21:43
This is intended behaviour.
It’s an emulation layer on top of a SPI flash sector and SPI flash sectors must be erased before writing.

**Comment by mamama1** [comment] 2019-02-15 21:55
> It’s an emulation layer on top of a SPI flash sector and SPI flash sectors must be erased before writing.

I know that, but how big is one sector? 4k?

**Comment by devyte** [comment] 2019-02-15 22:38
Correct. Closing as intended behavior.

**Closed by devyte** 2019-02-15 22:38 UTC
