### ISSUE TITLE
 Wemos D1R2 espcomm_send_command: didn't receive command response

### ISSUE THREAD

**Issue by nkqz** [esp8266/Arduino#3760] opened 2017-10-26 13:42 UTC
Hi, i used the blink code below and it worked fine the first time.
then i changed the delay and uploaded it back but can't upload.
tried the reset button, reinstalling drivers and arduino ide but still not working.

help?

Source code:

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);     // Initialize the LED_BUILTIN pin as an output
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, LOW);                                      
  delay(1000);                      
  digitalWrite(LED_BUILTIN, HIGH);  
  delay(1000);                      
}

error message: 
Arduino: 1.8.4 (Windows 10), Board: "WeMos D1 R2 & mini, 80 MHz, 921600, 4M (3M SPIFFS)"

Archiving built core (caching) in: C:\Users\nickq\AppData\Local\Temp\arduino_cache_845318\core\core_esp8266_esp8266_d1_mini_CpuFrequency_80,UploadSpeed_921600,FlashSize_4M3M_364cca2a1b54b3b9b0ca6734b17c92ab.a
Sketch uses 222201 bytes (21%) of program storage space. Maximum is 1044464 bytes.
Global variables use 31576 bytes (38%) of dynamic memory, leaving 50344 bytes for local variables. Maximum is 81920 bytes.
Uploading 226352 bytes from C:\Users\nickq\AppData\Local\Temp\arduino_build_162651/Blink.ino.bin to flash at 0x00000000
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_BEGIN) failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by devyte** [comment] 2017-10-27 00:58
@nkqz Not the right place to ask for usability support. Please refer to a community forum. Also:
- like the message says, enable verbose output
- flashing at a speed of 921k is just asking for trouble, try 230k or 115k
- I have 50+ Wemos D1R2s, and flashing works fine.
Closing as can't reproduce, and per #3655 .

**Closed by devyte** 2017-10-27 00:58 UTC
