### ISSUE TITLE
Delay() at start of Setup() prevents esp8266 from connecting to a network

### ISSUE THREAD

**Issue by VisualMicro** [esp8266/Arduino#3220] opened 2017-05-09 18:17 UTC
Adding a delay of a few seconds to the start of the setup() (before wifi network connect) prevents the esp from connecting to a wifi network.

We use a small delay() of a few seconds to allow telemetry to start on an external device such as a pc before the esp starts.

An example with a 5 second delay for testing purposes ...

void setup()
{
  delay(5000);

  //wifi no connect from esp to network, tested using auto assigned dhcp IP
}

Thanks

**Comment by igrr** [comment] 2017-05-10 05:24
This looks like a duplicate of https://github.com/esp8266/Arduino/issues/2186

**Closed by igrr** 2017-05-10 05:24 UTC
