### ISSUE TITLE
Connection to wifi takes too long

### ISSUE THREAD

**Issue by robertgregor** [esp8266/Arduino#2358] opened 2016-08-02 13:38 UTC
Hello, I have this code to connect the Wifi network:

void connectToWifi() {
  if (WiFi.status() == WL_CONNECTED) return;
  Serial.print(F("Connecting wifi: "));
  Serial.println(millis(), DEC);
  digitalWrite(LED_PIN, HIGH);
  WiFi.mode(WIFI_STA);
  if (ip[0] != 0) WiFi.config(getIpAddrFromArr(ip), getIpAddrFromArr(gw), getIpAddrFromArr(mask),getIpAddrFromArr(dns));
  WiFi.begin();
  int attempts = 0;
  while (WiFi.status() != WL_CONNECTED) {
      if (++attempts < 150) {
        Serial.print(".");
        delay(100);
      } else break;
  }
  if (WiFi.status() == WL_CONNECTED) {
    Serial.print(F("\nConnected to AP: "));
    Serial.print(millis(), DEC);
    Serial.print(F(" IP: "));
    for (byte thisByte = 0; thisByte < 4; thisByte++) {
      Serial.print(String(WiFi.localIP()[thisByte], DEC));
      if (thisByte != 3) Serial.print(".");
    }
    Serial.println();
  }
  digitalWrite(LED_PIN, LOW);  
}

It generates this output (Debug All):

Connecting wifi: 313
..wifi evt: 1
STA disconnect: 201
......................wifi evt: 1
STA disconnect: 201
......................wifi evt: 1
STA disconnect: 201
......................wifi evt: 1
STA disconnect: 201
.......................wifi evt: 1
STA disconnect: 201
.......................øwifi evt: 0
wifi evt: 3

Connected to AP: 12560 IP: 192.168.1.22
øMQTT client connected.
øø:c0 1, 5
ÿÿ:sent 29
þþþ:ur 1
:clnse
del
ÿÿàÿðüstate: 5 -> 0 (0)
rm 0
del if
usl
wifi evt: 1
STA disconnect: 8

As is seen, the time to connect to Wifi is almost 12 sec. With my mobile or PC, it is much faster, less than second for sure.
What I am doing wrong?

Hello, OK, interresting. In fact, if I change the code like that, it is pretty fast:

WiFi.begin("Bob","xxxxxxx");

Connecting wifi: 281
..€€wifi evt: 0
wifi evt: 3

Connected to AP: 485 IP: 192.168.1.22
€ÀMQTT client connected.
øà:c0 1, 5
:sent 25
:ur 1
:close
'V«Hø€ðþstate: 5 -> 0 (0)
rm 0
del if0
usl
wifi evt: 1
STA disconnect: 8

So it looks like, there is an issue with the module to read the last known wifi config...

**Comment by devyte** [comment] 2017-10-14 06:49
@robertgregor No basic info, no IDE settings, sketch is not complete.
I don't see this behavior on my ESP-12F boards, connection for me is pretty fast.
I seem to remember seeing somewhere a discussion about different connection times for different connection methods, e.g.: begin(), begin(ssid, pass), begin(ssid, pass, mac) or something along those lines. The times varied quite a bit.
Anyways, not the right place to discuss. Closing as can't reproduce.

**Closed by devyte** 2017-10-14 06:49 UTC
