### ISSUE TITLE
getCoreVersion returns empty string in version 3.0.0

### ISSUE THREAD

**Issue by fabiuz7** [esp8266/Arduino#8117] opened 2021-06-11 19:19 UTC
## Platform

- Hardware:				[esp8266ex]
- Core Version:			3.0.0
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

## [MCVE] Sketch

```cpp

void setup() {
  Serial.begin(115200);
  Serial.println("1");
  Serial.println(ESP.getCoreVersion());// Initialize the LED_BUILTIN pin as an output
  Serial.println("2");
}

void loop() {}
```

On serial monitor I can see "1" and "2", the line that should contain the core version is empty.

**Comment by d-a-v** [comment] 2021-06-11 20:26
Closing as duplicate of #8114 and #8049.
Thanks for reporting, it will be fixed in v3.0.1.

**Closed by d-a-v** 2021-06-11 20:26 UTC
