### ISSUE TITLE
softAP(ssid, password) ignores new data and uses old one

### ISSUE THREAD

**Issue by starlino** [esp8266/Arduino#1103] opened 2015-11-28 17:44 UTC
I have a weird problem I am basically running this sample witch current rc2.0.0-rc2:
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino

I have previously used this board with other scripts and somehow the ESP remembers the old SSID/Pass for access point, and ignores the new one

  WiFi.softAP(ssid, password);

I tried   WiFi.persistent(false); but it did not help. 

If I do:   Serial.setDebugOutput(true);  

I get:

Configuring access point...
softap config unchanged
AP IP address: 192.168.4.1
HTTP server started
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 5
cnt 

So why "softap config unchanged"  ?  Is there a way I completely reset/zero-out my board to factory defaults ?

**Comment by starlino** [comment] 2015-11-28 17:58
An update:  switching to  rc2.0.0-rc1  fixed the issue above, there might be something wrong in  rc2.0.0-rc2,

**Comment by igrr** [comment] 2015-11-28 18:00
Duplicate of #1054. Fixed in git now.

**Closed by igrr** 2015-11-28 18:00 UTC

**Comment by sayanee** [comment] 2017-07-28 12:52
@igrr @starlino I have exactly the same problem, but I'm unable to get Arduino to use the latest [rc1](https://github.com/esp8266/Arduino/releases/tag/2.4.0-rc1) version.

I tried following the [readme for using Arduino with git version](https://github.com/esp8266/Arduino#using-git-version), but installing in the directory did not seem to work `~/Documents/Arduino/hardware/esp8266com`. After I re-flashed ESP8266, the SSID for the access point is still the old name.

**Comment by sayanee** [comment] 2017-07-28 13:40
Ok, I got the `2.4.0-rc1` loaded into Arduino via the Boards Manager by appending `https://github.com/esp8266/Arduino/releases/download/2.4.0-rc1/package_esp8266com_index.json`:

![image](https://user-images.githubusercontent.com/413879/28719635-3d5b21de-73dd-11e7-8f42-42000913f1a5.png)

But the AP still shows the old one even after re-flashing 🤔

**Comment by sayanee** [comment] 2017-07-28 23:56
Alright - I have gotten it to work with the [example](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino) 👍

**Comment by guruthree** [comment] 2019-11-22 21:27
Possibly not for the same reasons, but I had an issue that presented the same way: changing the configured SSID/password didn't take effect. It appears that this is what happens when your password isn't at least 8 characters long. Hopefully this keeps someone else from spending a few hours tracking this down...

**Comment by fgerard** [comment] 2020-09-09 16:55
Thanks!! The thing is as @guruthree says, if password is not 8 chars or more everything is ignored!!

**Comment by Bagunceiro** [comment] 2022-04-23 16:52
Good grief. That's a couple of hours of my life I won't get back. Is there a fix in the works for that?

**Comment by bobemoe** [comment] 2023-02-16 19:46
Wow what a weird bug! Big thanks @guruthree for saving me a few hours :D

**Comment by Himanshu21358** [comment] 2023-03-10 12:08
Sir I am new developer now we are create a ESP8266 as server and serial port receive data and send data successfully. but I have a issue now I am change my Wi-Fi SOFTAP credentials(like SSID, PASWORD) by receive in serial monitor, so please suggest any code ?
