### ISSUE TITLE
Soft AP's SSID get vanished after 8-10hours

### ISSUE THREAD

**Issue by mushfiq-cse05-buet** [esp8266/Arduino#2841] opened 2017-01-07 09:51 UTC
i'm running a simple WiFiServer on a esp01 as Soft AP, my problem is very simple. after powering up the esp01 for first 4-5 hours everything goes fine but whenver i put the system idle for 8-10hours my esp01 doesn't broadcast its SSID of its Soft AP anymore that is i cant find the SSID on my android phone anymore, can anybody help me out ???

**Comment by devyte** [comment] 2017-10-04 18:57
@mushfiq-cse05-buet No MCVE, no basic info, no IDE settings.
I suggest trying latest git.
I have 46 boards spread across Wemos d1 mini v2, Nodemcu, and WittyCloud. I have them running around the clock, and I can't reproduce this.
Closing due to lack of info and can't reproduce.

**Closed by devyte** 2017-10-04 18:57 UTC
