### ISSUE TITLE
ESP-12E Node MCU will resets automatically at every time

### ISSUE THREAD

**Issue by BharathTatikonda** [esp8266/Arduino#2542] opened 2016-09-22 09:33 UTC
#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?
hi, i have started ESP12-E to work with the GSM module, in this when i was running the it should be reset automatically when some messages will receives,... then it reset and restarted from first so the function is not completed,,....so, please suggest me how to disable the watchdog timer,..... when i run the program the error will be like this///.........

Soft WDT reset

ctx: cont 
sp: 3ffefc90 end: 3ffeff00 offset: 01b0

>>>stack>>>
3ffefe50:  00000001 00000001 00000000 402030ea  
3ffefe60:  00000106 00000000 000005dc 00001388  
3ffefe70:  00000005 3ffe87c0 00000004 40202fe8  
3ffefe80:  3ffe8517 3ffeed24 3ffeee1c 00000000  
3ffefe90:  00000005 000005dc 3ffe8ba2 4020313e  
3ffefea0:  4010564a feefeffe 3ffeee1c 3ffeeed0  
3ffefeb0:  3fffdad0 3ffe8ba2 00000000 40202b77  
3ffefec0:  3fffdad0 3ffeebe0 3ffeee1c 40201fd4  
3ffefed0:  feefeffe 00000000 3ffeeec8 4020213d  
3ffefee0:  feefeffe feefeffe feefeffe 4020388c  
3ffefef0:  feefeffe feefeffe 3ffeeee0 40100718  
<<<stack<<<

   so, please suggest me how to disable the watchdog timer in the esp12-e module

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp


#include <SoftwareSerial.h>
#include <Wire.h>
#include <EEPROM.h>
#include <string.h>
#include<Esp.h>
//#include "SoftReset.h"
// Add SIM900 library here
#include "GSM_Shield_Esp.h"


// SIM900 GSM module settings
//#define PIN_TX    7
//#define PIN_RX      8
#define RELAY 4
#define BAUDRATE 9600
#define MESSAGE_LENGTH 30
const int interruptPin = 14;
volatile byte state = 0;


// For debugging interface
#define DEBUG 1
#define DELAY_TIME 1000

#define PB_ENTRY_INDEX_LOCATION 1
#define SMS_REPLY_LOCATION 2
#define CALL_REPLY_LOCATION 3


// Global Varables
char PRIMARY[16];
int CallReplyFlag = true;
int smsReplyFlag=false;
int rebootFlag = false;
char *password = "ABCDEF";  // Default password
byte messageIndex = 0;
char gsmBuffer[64];
char *s = NULL;
char num[4];
unsigned int PBEntryIndex = 1;
// Create an instance of GPRS library
GPRS gsm(13, 15, 9600);

// Main function starts here

void setup() {

 // wdt_disable();
  // Initialize the hardware
  InitHardware();
  
  // Setup SIM Card
  SIMCardSetup();
  // wdt_disable();
  
  // Setup SMS Service
  SMSServiceSetup();  
   pinMode(interruptPin,INPUT);
  pinMode(RELAY,OUTPUT);
  //pinMode(interruptPin, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(interruptPin), Alarm, FALLING);
  Serial.println("Listening for SMS ");
 // wdt_enable(5000);
}

void loop() {
  // Serial.println("Listening for SMS ");
  // Wait for SMS
  if(gsm.readable()) {
    // Print the buffer
    sim900_read_buffer(gsmBuffer,sizeof(gsmBuffer),DEFAULT_TIMEOUT);
    Serial.println(gsmBuffer);
    
    // If incoming is SMS
    // +CMTI: "SM", 2
    messageIndex = gsm.isSMSunread();
    if(messageIndex > 0) {
     // wdt_disable();
      Serial.println("handling SMS");
      handleSMS(messageIndex);
      //wdt_enable(5000);
      messageIndex = 0;
    }
    sim900_clean_buffer(gsmBuffer,sizeof(gsmBuffer));
  }


     if(digitalRead(interruptPin) == HIGH){
       
         

         // void Bharath() {
  // check this mobile number with the saved numbers and return the index if found
  // Searching for the mobile number
  char *s, *p;
  char index[4];
  byte i = 0;
  // AT+CPBF="mobileNumber"
  //sim900_check_with_cmd("AT+CPBS=\"ME\"\r\n","OK\r\n",CMD);
  sim900_send_cmd("AT+CPBR=");
  itoa(PBEntryIndex, num, 10);
  sim900_send_cmd(num);
  sim900_send_cmd("\r\n");
  sim900_clean_buffer(gsmBuffer, sizeof(gsmBuffer));
  sim900_read_buffer(gsmBuffer, sizeof(gsmBuffer));
  
  // +CPBF: 1,"+91XXXXXXXXXX",145,"TT+91XXXXXXXXXX"
  // If number is present
  if(NULL != ( s = strstr(gsmBuffer, "+CPBR:"))) {
    s = s + 10;
    p = strstr((char *)(s), "\""); //point to first ,
    if(NULL != s) {
      i = 0;
      while (s< p) {
        PRIMARY[i++] = *(s++);
      }
      PRIMARY[i] = '\0';
    } 
  }

      if(CallReplyFlag){
        Serial.println("calling"); 
        Serial.println(PRIMARY);
        //delay(1000);
        gsm.callUp(PRIMARY);
        delay(12000);
        gsm.hangup();
        delay(1000);
      }else if(smsReplyFlag){
        delay(1000);
        Serial.println("SMS");
      //  gsm.sendSMS(PRIMARY,"someone is coming");
        
      }
      }
  else
    delay(100);
  
  if (rebootFlag) {
    Serial.println("Rebooting device");
    delay(10 * DELAY_TIME);
  //  soft_restart();
  }
}
void InitHardware(void) {
  // Start Serial editor
  Serial.begin(BAUDRATE);
  Serial.println("initialising Hardware");
  //while(!Serial);

   EEPROM.begin(512);
  
 if (EEPROM.read(500) != 175) {
    //if not load default config files to EEPROM
    writeInitalConfig();
  }
  // Read the config settings from EEPROM
  readConfig();
  

  // POWER ON the GSM module
  while(!gsm.init()) {
    Serial.println("Initialisation error");
    delay(2000);
   // soft_restart();
  }
  
  // Set the communication settings for SIM900
  // Sent ATE0
  sim900_check_with_cmd("ATE0\r\n","OK\r\n",CMD);
  delay(DELAY_TIME);
}

void writeInitalConfig(void) {
  Serial.println("Writing default configuration");
  EEPROM.write(500, 175);
  EEPROM.write(PB_ENTRY_INDEX_LOCATION, 1); // Set default PBEntryIndex = 1
  EEPROM.write(SMS_REPLY_LOCATION, 0); // SMS Reply disabled
  EEPROM.write(CALL_REPLY_LOCATION, 1); // Call Reply Enabled
  EEPROM.commit();
}

void readConfig(void) {
  Serial.println("Reading config");
  PBEntryIndex = EEPROM.read(PB_ENTRY_INDEX_LOCATION);
  smsReplyFlag = (EEPROM.read(SMS_REPLY_LOCATION) != 0)? true : false;
  CallReplyFlag = (EEPROM.read(CALL_REPLY_LOCATION) != 0)? true : false;
}

void SIMCardSetup(void) {
    
  // check IMEI of device
  char imei[16];
  // Send AT+GSN
  gsm.getIMEI(imei);
  Serial.print("Received IMEI ");
  Serial.println(imei);
  
  // Generate Secret PASSWORD from IMEI
#ifdef DEBUG
  Serial.println("Generating password");
#endif
  GeneratePassword(imei);

/* int rssi, ber;
  // sent AT+CSQ
  
 // Check for signal strength
  gsm.getSignalStrength(&rssi);
#ifdef DEBUG
  Serial.print("Signal Strength is ");
  Serial.println(rssi);
#endif
  // Check for SIM registration
  // Send AT+CREG?
  int networkType;
  gsm.getSIMRegistration(&networkType);
#ifdef DEBUG  
  Serial.print("network type is ");
  Serial.println(networkType);
#endif
  if(networkType == 1 || networkType == 5) {
    Serial.println("SIM is registered");
  }
  else {
    Serial.println("SIM is not registered");
    //soft_restart();
  } */
} 

void GeneratePassword(char* imei) {
  // think of some mechanism
  
#ifdef DEBUG
  Serial.print("PASSWORD generated: ");
  Serial.println(password);
#endif
}

void SMSServiceSetup(void) {
  // Set SMS input mode
  Serial.println("Setting input mode");
  // send AT+CMGF=1
  sim900_check_with_cmd("AT+CMGF=1\r\n","OK\r\n",CMD);
  delay(DELAY_TIME);
  
  // Set the input character set
  Serial.println("Setting character mode: GSM");
  // Send AT+CSCS="GSM"
  sim900_check_with_cmd("AT+CSCS=\"GSM\"\r\n","OK\r\n",CMD);
  delay(DELAY_TIME);
  
  // Set SMS mode
  Serial.println("Setting SMS message indications");
  // Send AT+CNMI=2,1,0,0,0
  sim900_check_with_cmd("AT+CNMI=2,1,0,0\r\n","OK\r\n",CMD);
  delay(DELAY_TIME);
  
  // Save the settings for SMS
  Serial.println("Saving settings to memory");
  // Send AT+CSAS=0
  sim900_check_with_cmd("AT+CSAS=0\r\n","OK\r\n",CMD);
  delay(DELAY_TIME);
  
  Serial.println("SMS Service Ready");
}


void handleSMS(byte messageIndex) {
  // Get the SMS content
  char message[100];
  char mobileNumber[16];
  char dateTime[24];
  char *s, *p;
  char num[4];
  byte i = 0;

  
  // read SMS content
  gsm.readSMS(messageIndex, message, MESSAGE_LENGTH,mobileNumber , dateTime);
 // strupr(message);
#ifdef DEBUG
  Serial.println("Printing messageIndex");
  Serial.println(messageIndex);
  Serial.println("Printing SMS content");
  Serial.println(message);
  Serial.println("Printing MESSAGE_LENGTH");
  Serial.println(MESSAGE_LENGTH);
  Serial.println("Printing mobileNumber");
  Serial.println(mobileNumber);
  Serial.println("Printing dateTime");
  Serial.println(dateTime);
#endif 
 
  // delete SMS to save memory
  gsm.deleteSMS(messageIndex);
  
if(checkIfNumberAuthorized(mobileNumber)<0){
  if(NULL !=(s=strstr(message, "REGISTER"))){
 
     // get the password
      s = s + 8; // we are on the first digit of user password
      p = strstr((char *)(s)," ");
      char userPass[7];
      s++; //now s is pointing to first character of password
      i = 0;
      while(i < 6){
        userPass[i++] = *(s++);
      }
      userPass[i] = '\0';
#ifdef DEBUG
      Serial.print("User password is ");
      Serial.println(userPass);
#endif      
      // Compare the password
      if(!strcmp(userPass, password)) {
        Serial.println("Password matched");
        int index = checkIfNumberAuthorized(mobileNumber);
        if(index <= 0) {
        // Make an entry into phonebook
        //AT+CPBW=PBEntryIndex,"newmobileNumber",145,"TTmobileNumber"
        //PBEntryIndex++;
#ifdef DEBUG
        Serial.print("PB index is ");
        Serial.println(PBEntryIndex);
#endif
        sim900_flush_serial();
        //sim900_check_with_cmd("AT+CPBS=\"ME\"\r\n","OK\r\n",CMD);
        sim900_send_cmd("AT+CPBW=");
        itoa(PBEntryIndex, num, 10);
        sim900_send_cmd(num);
        sim900_send_cmd(",\"");
        sim900_send_cmd(mobileNumber);
        sim900_send_cmd("\",145,\"TT");
        sim900_send_cmd(mobileNumber);
        sim900_send_cmd("\"\r\n");
        
        sim900_wait_for_resp("OK\r\n", CMD);
#ifdef DEBUG
        Serial.print("Mobile Number ");
        Serial.print(mobileNumber);
        Serial.println(" Authorised");
#endif
           EEPROM.write(PB_ENTRY_INDEX_LOCATION, PBEntryIndex);
        }
       else {
#ifdef DEBUG
          Serial.println("Password did not match");
#endif
          //gsm.sendSMS(mobileNumber, "Wrong password");
       }
  }
}
}
  else if(checkIfNumberAuthorized(mobileNumber)> 0) {
  if(NULL !=(s=strstr(message, "SMS ENABLE"))){
    smsReplyFlag= true;
    CallReplyFlag= false;
    //send SMS
    if(smsReplyFlag){
      //gsm.sendSMS(PRIMARY, "SMS ENABLED");
      }
        // Save settings to EEPROM
        EEPROM.write(SMS_REPLY_LOCATION,1);
        EEPROM.write(CALL_REPLY_LOCATION,0);
#ifdef DEBUG
      Serial.println("SMS ENABLED");
#endif 
    }
    else if(NULL != strstr(message,"SMS DISABLE")) {
      smsReplyFlag = false;
      CallReplyFlag = true;
      //send SMS
    if(smsReplyFlag){
      //gsm.sendSMS(PRIMARY, "SMS DISABLED");
      }
      // Save setting to EEPROM
       EEPROM.write(SMS_REPLY_LOCATION,0);
       EEPROM.write(CALL_REPLY_LOCATION,1);
#ifdef DEBUG
      Serial.println("SMS DISABLED");
#endif
    }
  }
}

int checkIfNumberAuthorized(char *mobileNumber) {
  // check this mobile number with the saved numbers and return the index if found
  // Searching for the mobile number
  char *s, *p;
  char index[4];
  byte i = 0;
  // AT+CPBF="mobileNumber"
  //sim900_check_with_cmd("AT+CPBS=\"ME\"\r\n","OK\r\n",CMD);
  sim900_send_cmd("AT+CPBF=\"");
  sim900_send_cmd(mobileNumber);
  sim900_send_cmd("\"\r\n");
  sim900_clean_buffer(gsmBuffer, sizeof(gsmBuffer));
  sim900_read_buffer(gsmBuffer, sizeof(gsmBuffer));
  
  // +CPBF: 1,"+91XXXXXXXXXX",145,"TT+91XXXXXXXXXX"
  // If number is present
  if(NULL != ( s = strstr(gsmBuffer, "+CPBF:"))) {
    s = s + 7;
    p = strstr((char *)(s), ","); //point to first ,
    if(NULL != s) {
      i = 0;
      while (s < p) {
        index[i++] = *(s++);
      }
      index[i] = '\0';
    }
    Serial.println("number is authorized");
    return atoi(index); 
  }
  else {
    Serial.println("number is not authorized");
    return -1;
  }
}

void Alarm()
{
  state= digitalRead(interruptPin);
  digitalWrite(RELAY, state);
}
 
```

### Debug Messages

```
messages here
```

**Comment by supersjimmie** [comment] 2016-09-22 09:40
You are using some unknown library called "GSM_Shield_Esp.h".
It looks like the problem is in there. Did you ask the maker of that library why it doesn't work?

**Comment by BharathTatikonda** [comment] 2016-09-22 09:48
yahh, but it was created based on the requirement. normal gsm library is not working for esp-12e,so i have removed some part(is listening and listen functions) in the library..... and rearranged it

**Comment by supersjimmie** [comment] 2016-09-22 10:13
Can you then trace where in your code it fails?
Just put some "Serial.println("here"); at several places, and replace "here" with something that points to where in the code it is. Then you may see at what point the crash occurs...

Otherwise you can do a stack decode to discover what happens in your code at the stack that is displayed.
[ESP Exception decoder](https://github.com/me-no-dev/EspExceptionDecoder)

**Comment by BharathTatikonda** [comment] 2016-09-22 10:19
Thank u for ur suggestion, i have checked thet one, the program will fails on when the message is reading (the program will stuck on the  " messageIndex = gsm.isSMSunread(); " in this funtion, ) and at some times it stucts at   "gsm.deleteSMS(messageIndex);" in this function....... 

And i want to try with the stack decode....

**Comment by BharathTatikonda** [comment] 2016-09-22 10:45
there no result.............. so could you tell how to disabled the watchdog timer in esp12-e

**Comment by supersjimmie** [comment] 2016-09-22 11:05
Then you should investigate what happens inside ```gsm.isSMSunread();```, which is in the library (we don't know).
You cannot disable the wdt, but in most cases the wdt is triggered because of a "bad" function.
Check that ```gsm.isSMSunread();```, perhaps there is some for/while/... loop in it that takes too long. If so add the ```yield()``` command inside that loop.

We cannot help if we don't know the library.

**Comment by BharathTatikonda** [comment] 2016-09-22 11:10
ok.. i will send the gsm.isSMSunread(); function for this one from the library,........  could u check this one.......
bool GPRS::readSMS(int messageIndex, char *message, int length, char *phone, char *datetime)  
{
  /* Response is like:
  AT+CMGR=2
  
  +CMGR: "REC READ","XXXXXXXXXXX","","14/10/09,17:30:17+08"
  SMS text here
  
  So we need (more or lees), 80 chars plus expected message length in buffer. CAUTION FREE MEMORY
  */

    int i = 0;
    char gprsBuffer[80 + length];
    //char cmd[16];
	char num[4];
    char *p,*p2,*s;
    
    sim900_check_with_cmd("AT+CMGF=1\r\n","OK\r\n",CMD);
    delay(1000);
	//sprintf(cmd,"AT+CMGR=%d\r\n",messageIndex);
    //sim900_send_cmd(cmd);
	sim900_send_cmd("AT+CMGR=");
	itoa(messageIndex, num, 10);
	sim900_send_cmd(num);
	sim900_send_cmd("\r\n");
    sim900_clean_buffer(gprsBuffer,sizeof(gprsBuffer));
    sim900_read_buffer(gprsBuffer,sizeof(gprsBuffer));
      
    if(NULL != ( s = strstr(gprsBuffer,"+CMGR:"))){
        // Extract phone number string
        p = strstr(s,",");
        p2 = p + 2; //We are in the first phone number character
        p = strstr((char *)(p2), "\"");
        if (NULL != p) {
            i = 0;
            while (p2 < p) {
                phone[i++] = *(p2++);
            }
            phone[i] = '\0';            
        }
        // Extract date time string
        p = strstr((char *)(p2),",");
        p2 = p + 1; 
        p = strstr((char *)(p2), ","); 
        p2 = p + 2; //We are in the first date time character
        p = strstr((char *)(p2), "\"");
        if (NULL != p) {
            i = 0;
            while (p2 < p) {
                datetime[i++] = *(p2++);
            }
            datetime[i] = '\0';
        }        
        if(NULL != ( s = strstr(s,"\r\n"))){
            i = 0;
            p = s + 2;
            while((*p != '\r')&&(i < length-1)) {
                message[i++] = *(p++);
            }
            message[i] = '\0';
        }
        return true;
    }
    return false;    
}

bool GPRS::readSMS(int messageIndex, char *message,int length)
{
    int i = 0;
    char gprsBuffer[100];
    //char cmd[16];
	char num[4];
    char *p,*s;
    
    sim900_check_with_cmd("AT+CMGF=1\r\n","OK\r\n",CMD);
    delay(1000);
	sim900_send_cmd("AT+CMGR=");
	itoa(messageIndex, num, 10);
	sim900_send_cmd(num);
	sim900_send_cmd("\r\n");
//  sprintf(cmd,"AT+CMGR=%d\r\n",messageIndex);
//    sim900_send_cmd(cmd);
    sim900_clean_buffer(gprsBuffer,sizeof(gprsBuffer));
    sim900_read_buffer(gprsBuffer,sizeof(gprsBuffer),DEFAULT_TIMEOUT);
    if(NULL != ( s = strstr(gprsBuffer,"+CMGR:"))){
        if(NULL != ( s = strstr(s,"\r\n"))){
            p = s + 2;
            while((*p != '\r')&&(i < length-1)) {
                message[i++] = *(p++);
            }
            message[i] = '\0';
            return true;
        }
    }
    return false;   
}

**Comment by BharathTatikonda** [comment] 2016-09-22 11:14
but how can we control the with the reset function, until the process would be completed,....... same program will works on the arduino's modules. But i cant identify the problem in that.. i have stucked in this small logic upto one week... but there is no use,.

**Comment by supersjimmie** [comment] 2016-09-22 11:24
I see several (4?) ```while``` loops. Just try to add ```yield();``` within each ```while``` loop.
Arduino doesn't have a WDT, ESP has it and it cannot be disabled.
Adding yield() just prevents the WDT to kick in (in most cases).

Also, other functions like ```sim900_read_buffer()```, and ```sim900_send_cmd()``` and perhaps others are called from here.
You should also check those. (and others, called from there)

**Comment by BharathTatikonda** [comment] 2016-09-22 11:25
gsm.isSMSunread(); this function is same as in the arduino sim900 library......... could u also check with gprs sim900a libraries..................... in that libraries i have deleted only two functions i.e,.
1.void GPRS::listen(void)
  {
	gprsSerial.listen();
}
2.bool GPRS::isListening(void)
   {
	return gprsSerial.isListening();
   }

**Comment by BharathTatikonda** [comment] 2016-09-22 11:27
ok i will check with the yield(); at the loops,........

**Comment by BharathTatikonda** [comment] 2016-09-22 11:57
yes, thank you so much for your suggestion, i will got better result while using yield(); this function for only some loops only,.... i can search with other functions also,...... thank you somuch ,... if there is any queries i will contact with u,,,.....

**Comment by supersjimmie** [comment] 2016-09-22 12:39
You are welcome.  :)
I know, from my own experience, this is a problem many people have when using arduino code on esp8266. That's why it is also easy to solve, if you know where to search.
(you can close this issue with the button below if it is solved for you)

**Comment by BharathTatikonda** [comment] 2016-09-22 12:42
ok done

**Comment by BharathTatikonda** [comment] 2016-09-27 10:22
hi, could u tell me where the yield() will be presented in the libraries.....
and also the function of the yield();

**Closed** 2016-09-29 08:45 UTC

**Comment by gocamiot** [comment] 2017-08-31 06:22
Same thing with esp-12f. Yield() solved it. long while loops are problematic.  Thank you.

**Comment by devyte** [comment] 2017-08-31 16:00
That is expected. The ESP requires free time off your code to handle the
wifi stack. There are watchdog timers in place to assure that. If you do an
long loop in your code, a wdt will trigger and reboot.
Calling yield() is meant to help with long operations. It gives a bit of
time to the wifi stack to handle critical operations. It can only be called
from within the loop, or functions called from the loop. It can't be called
from async callbacks.
