### ISSUE TITLE
enable sprintf to support printing floats, let the user choose.

### ISSUE THREAD

**Issue by aguaviva** [esp8266/Arduino#1974] opened 2016-04-25 21:54 UTC
Given that an ESP is as powerful as a Pentium Pro, does it make sense to remove the floating point support just to save some mem? 

At a minimum we should let the user choose whether to support %f feature or not.

**Comment by TheAustrian** [comment] 2016-04-25 22:06
I concatenate with String(floatVariable, numberOfDecimals) to print floats - I don't know if that helps in your application, though. I would not mind having %f, though.

**Comment by aguaviva** [comment] 2016-04-25 22:34
thanks and I'd also appreciate a proper fix, there a lots of confused people out there.

Even basic could print floating point numbers :) lets fix this please :)

**Comment by igrr** [comment] 2016-04-25 23:57
Closing as duplicate of #1179.

**Closed by igrr** 2016-04-25 23:57 UTC

**Comment by aguaviva** [comment] 2016-04-26 10:45
Is anybody working in this? If anybody submits a pull request with the c implementation used in gcc, would it be accepted?

**Comment by igrr** [comment] 2016-04-26 10:47
This can be implemented as part of a pending pull request: #1752.
Please follow up in the issue linked above: #1179.

**Comment by aguaviva** [comment] 2016-04-26 13:09
Thanks, this helps! BTW you guys rock!
