### ISSUE TITLE
The module stops responding on ARP broadcast after several hours

### ISSUE THREAD

**Issue by vgam7** [esp8266/Arduino#1137] opened 2015-12-03 14:25 UTC
Hi,
I'm using the esp module as a web server, connected via wifi to my home AP. The issue is that after several hours it stops responding on ARP broadcasts so newly connected devices in the same network are unable to establish connection to it.
I've tried working with WifiServer, esp8266WifiServer - result is same. This bug is 100% reproducible, tested many times on 3 different esp modules, with latest (from Nov 30) version as well as with previous "stable" version.
It's looks as some kind of memory or resource leak but it's my guess only...
##

**Comment by devyte** [comment] 2017-10-19 16:39
Closing as duplicate of #3095. Will track there, as there is slightly more info in it.

**Closed by devyte** 2017-10-19 16:39 UTC
