### ISSUE TITLE
ESP8266WebServer URL parameter decoding 

### ISSUE THREAD

**Issue by elefa** [esp8266/Arduino#4058] opened 2017-12-31 21:26 UTC
I use simple AJAX function saveconfig() (bellow) with ESP8266WebServer and I receive bad results:
webSrv.args() returns: 1
webSrv.arg(0) returns: arg1=uno&arg2=two&arg3=77  

I use lastest git version ESP8266WebServer (and ESP Arduino core too). 
IE, Edge, Chrome - same results.

With uncommented #define DEBUG_ESP_HTTP_SERVER I receive only "New client" message. 

function saveconfig() {
var xhr = new XMLHttpRequest();
xhr.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200)
  	document.getElementById("status").innerHTML = this.responseText;
};
xhr.open("POST", "/saveconfig", true);
xhr.setRequestHeader("Content-Type", "text/plain;charset=UTF-8");
var resp = "arg1=uno&arg2=two&arg3=77";
xhr.send(resp);
}

**Comment by devyte** [comment] 2017-12-31 21:48
@elefa you pretty much ignored the entire issue template. It exists for a reason.
A fix for decoding was merged  only yesterday. I suggest you resync your git, rebuild from scratch, and retest.
The issue only shows a browser side java snippet, which has nothing to  do with the code in this repo. Without a MCVE sketch that reproduces the issue, this won't be investigated.
Closing due to lack of info. If you think there is is still a problem, please open a new issue and fill in all the requested info.

**Closed by devyte** 2017-12-31 21:48 UTC
