### ISSUE TITLE
Serial.swap() unexpected chars on RX buffer Problem related to #2380

### ISSUE THREAD

**Issue by vitalian12** [esp8266/Arduino#2427] opened 2016-08-24 02:10 UTC
I'm using ESP12E (nodemcu) and I have same problem #2380.

I think lots of people use both RXD0/TXD0 and RXD2/TXD2 for debugging by using Serial.swap().

There is no input clearly to RXD2 but sometimes get some weird chars when I use Serial.read() with repeating swap in loop like below source code which come from #2380.

I suspect that RX buffer not clear when swap happens, so if you communicate with your serial monitor in your PC through RXD0/TXD0 by Serial.print() or Serial.println() and then there are remaining some chars in RX buffer by the communication I guess. and then you enable Serial.swap(). If you do Serial.read() in RXD2/TXD2 mode, then you may get unexpected chars from the RX buffer.

I look at HardwareSerial class, the swap function doesn't clear RX buffer, this is also same happened in Serial.flush() function which this is only for TX not RX. The flush only waits for sending all chars in TX buffer not related to RX clearly. 

There is no function clearing RX buffer in Serial global object. 

What I do to solve this problem:
If I communicate with serial monitor through RXD0/TXD0 and then I do Serial.swap() to use RXD2/TXD2.
after swap, I do read function with serial.available() repeatably until there is no read chars.
and then there are no unexpected chars. 
of course, you should not just remove RX buffer, consider how to deal with pair of write and read depending on your situation.

example source code below, D8,D7 is hard-wired connected in my nodemcu
# include <ESP8266WiFi.h>

void SendCMD(char cmd){
  delay(100);
  Serial.swap(15);
  delay(100);

  while((Serial.available() > 0)){
    Serial.read();  
  }

  Serial.flush();
  Serial.write(cmd);
  delay(100);
  Serial.swap(1);
  delay(100);
}

void GetCMD(void){
  int incomingbyte = 0;
  int recv_flag = 0;
  delay(100);
  Serial.swap(15);
  delay(100);
  if(Serial.available() > 0){
    incomingbyte = Serial.read(); 
    recv_flag = 1;  
  }
  delay(100);
  Serial.swap(1);
  delay(100);
  if(recv_flag > 0){
    Serial.print("I received: ");
    Serial.println(incomingbyte,HEX);
  }  
}

void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println("Serial Port opend!");
}

void loop() {
  // put your main code here, to run repeatedly:
  SendCMD('a');
  GetCMD();
}

**Comment by devyte** [comment] 2017-10-14 04:39
Closing as duplicate of #2380.

**Closed by devyte** 2017-10-14 04:39 UTC
