### ISSUE TITLE
error: espcomm_open failed, error: Failed to open COM1

### ISSUE THREAD

**Issue by CrazyPharaoh** [esp8266/Arduino#2974] opened 2017-02-17 08:16 UTC
i have bought the latest ESP8266 (im new to coding and arduino)
board and i have been having this isssue that when i try to upload code, it says:
error: espcomm_open failed.

the error code is this:

Arduino: 1.8.1 (Windows 10), Board: "Adafruit HUZZAH ESP8266, 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

Sketch uses 522522 bytes (50%) of program storage space. Maximum is 1044464 bytes.
Global variables use 51564 bytes (62%) of dynamic memory, leaving 30356 bytes for local variables. Maximum is 81920 bytes.
error: Failed to open COM1
error: espcomm_open failed
error: espcomm_open failed

I have no idea how to fix this...

**Comment by JamesGKent** [comment] 2017-02-17 08:46
I suspect your ESP isn't actually on COM1, with your ESP plugged in, open the arduino IDE and from the menu select tools -> Port and let us know what's listed there. hopefully one of the entries there will identify as being your ESP and selecting it should then allow your download to go ahead, if i't doesn't please post any further details you get

**Comment by CrazyPharaoh** [comment] 2017-02-17 10:54
Oh ok Thanks sooooooooooooooo much James! I changed the port to port 5 and it worked!

**Comment by CrazyPharaoh** [comment] 2017-02-17 11:00
Thanks James! I changed the port to COM5 and the board to nodemcu 0.1 and it worked!

**Comment by JamesGKent** [comment] 2017-02-17 12:50
If this is solved, can you close this issue please?
Thanks

**Comment by sloth475** [comment] 2017-05-31 07:16
I m having the same issue and I tried changing the port also but the error still persists.

**Comment by lrmoreno007** [comment] 2017-05-31 08:16
https://arduino-esp8266.readthedocs.io/en/latest/faq/a01-espcomm_sync-failed.html

**Comment by GreenApple04** [comment] 2017-07-03 09:49
i tried this but the port is disabled

**Comment by GreenApple04** [comment] 2017-07-03 09:51
I tried to look port on menu -> tools, but unfortunately it is disabled.

**Comment by devyte** [comment] 2017-09-09 06:28
The causes for the described issue are documented, with ample help and pictures. If that doesn't help, the board is likely dead (I saw such a case just today).
Closing.

**Closed by devyte** 2017-09-09 06:28 UTC

**Comment by jainmnsh** [comment] 2017-12-12 15:34
I confirmed that my port is correctly configured but still running into issues.
Archiving built core (caching) in: C:\Users\MANISH~1\AppData\Local\Temp\arduino_cache_444881\core\core_esp8266_esp8266_huzzah_CpuFrequency_80,UploadSpeed_115200,FlashSize_4M3M_025d1e6d36dee6c6466fc86db1d37fde.a
Sketch uses 222213 bytes (21%) of program storage space. Maximum is 1044464 bytes.
Global variables use 31588 bytes (38%) of dynamic memory, leaving 50332 bytes for local variables. Maximum is 81920 bytes.
error: Failed to open COM3
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

**Comment by devyte** [comment] 2017-12-12 15:51
That's the problem right there:
error: Failed to open COM3

**Comment by jainmnsh** [comment] 2017-12-12 15:53
@devyte yea, I confirmed my device is connected on com3. I can see that in my device manager.
![image](https://user-images.githubusercontent.com/3792793/33893925-80a21aca-df11-11e7-9ffa-e2bd6fece0f0.png)

**Comment by JamesGKent** [comment] 2017-12-12 15:58
if you can see com3 in dev manager, then something else must have that port open, by any chance to you have the serial monitor open? if so, close it then try upload again.

**Comment by devyte** [comment] 2017-12-12 15:59
My point is that the port can't be opened. Either it's bad hardware/driver, or the port number changed, or something else is using it.
Reboot, update drivers, reinstall, etc.

**Comment by karenYerevan** [comment] 2017-12-14 21:24
fuck arduino ... it is a very bad product ... 
yesterday i upload sketch in esp8266, today the same sketch not uploading, i am not changed nothing on my connect (arduino uno and esp8266) ...  and allways i have same error 

warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

ARDUINO bad pruduct on the world

**Comment by sarath341** [comment] 2017-12-21 10:53
Hello Guys, I too had the problem. Now I found out what was the problem. When I went to Device Manager I found that in ports -> CP2102 driver is not installed. So I googled it & downloaded the CP210x driver and installed. Now it works like charm. Here is the driver link: [https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers](url)

**Comment by sarath341** [comment] 2018-01-23 08:53
Hello swapkarnewar, I used Node MCU version 1.0. I'm not sure which board you are using. If it is ESP-01 then you need to connect GPIO0 pin to Ground while flashing (most people use push buttons for this). 

In case you are having NodeMCU there are 2 Versions (v0.9 & v1.0) are available (Look backside of the board). So you need to choose the Board type with the correct version. (Most boards selling in the market are v1.0 only so try with that). NodeMCU has additional hardware to enable flash mode (No need to connect GPIO to Gnd Still they provided a Flash button on it you can use it optional while flashing).

**Comment by jango** [comment] 2018-06-24 15:30
My experience:

1. I have two S20 that I just got from Amazon this month, PCBs are stamped: S20_US V1.3, 2017-3-28
2. I had to connect TX -> TX and RX -> RX in order for it to work, as mentioned by someone else in this thread.
3. I was not able to flash using VS Code, I had to compile using VS code and then use standalone esptool to flash, i.e.: `esptool.py --port COM3 write_flash 0x00000 firmware.bin`. When doing this through VS code, flashing start but fail at some point before 100% with "espcomm_sync" or similar error.

**Comment by SithiVaheeth** [comment] 2018-09-20 06:51
echo "# doubt-in-a-error" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/SithiVaheeth/doubt-in-a-error.git
git push -u origin master
how to rectify this error?

**Comment by SithiVaheeth** [comment] 2018-09-20 06:54
Build options changed, rebuilding all
Archiving built core (caching) in: C:\Users\Hemanth\AppData\Local\Temp\arduino_cache_435472\core\core_esp8266_esp8266_generic_CpuFrequency_80,VTable_flash,ResetMethod_ck,CrystalFreq_26,FlashFreq_40,FlashMode_qio,FlashSize_512K0,led_2,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_115200_2d7735b7171c68d5a228e47eff30259f.a
Sketch uses 354016 bytes (70%) of program storage space. Maximum is 499696 bytes.
Global variables use 31904 bytes (38%) of dynamic memory, leaving 50016 bytes for local variables. Maximum is 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed
How to rectify this error??

**Comment by anima-gupta** [comment] 2018-10-23 04:09
error: Failed to open COM3
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed
how to solve this issue in while using nodemcuesp8266 wifi module?
I also tried to look port on menu -> tools, but unfortunately it is disabled.
no port is being displayed over there.

**Comment by suhyunhan** [comment] 2020-04-16 05:06
TXD -  contact
RXD - contact
5V -    discontact(??)
GND - contact
3.3V  - contact
