### ISSUE TITLE
Enabling Debug port "Serial" results in compile error

### ISSUE THREAD

**Issue by probonopd** [esp8266/Arduino#1448] opened 2016-01-16 16:21 UTC
In most (all?) sketches that use Wi-Fi, enabling [Debug port](https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md) "Serial" results in a compile error.

For example, using the mDNS_Web_Server.ino sketch and enabling Debug port "Serial" results in a compile error:

```
Arduino: 1.6.7 Hourly Build 2015/12/17 04:29 (Linux), Board: "Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 921600, 4M (3M SPIFFS), nodemcu, Serial, All"

Build options changed, rebuilding all
In file included from /home/me/.arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp:26:0:
/home/me/.arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp: In member function 'wl_status_t ESP8266WiFiMulti::run()':
/home/me/.arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.h:37:66: error: cannot pass objects of non-trivially-copyable type 'class String' through '...'
 #define DEBUG_WIFI_MULTI(...) DEBUG_ESP_PORT.printf( __VA_ARGS__ )

                                                                  ^
/home/me/.arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp:130:25: note: in expansion of macro 'DEBUG_WIFI_MULTI'
                         DEBUG_WIFI_MULTI("[WIFI] SSID: %s\n", WiFi.SSID());

                         ^
exit status 1
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
```

**Comment by andig** [comment] 2016-01-16 19:15
Duplicate of https://github.com/esp8266/Arduino/pull/1369

**Closed** 2016-01-16 20:51 UTC
