### ISSUE TITLE
Linux 32bit build

### ISSUE THREAD

**Issue by dannyvai** [esp8266/Arduino#158] opened 2015-05-01 16:26 UTC
Hi,
Why there is no 32bit arduino ide build?
Some people use old computers to program micro-controllers like the esp8266 and arduino.. 
They use 32bit computers...

Btw after building the arduino in the programmer menu-list there shouldn't be the esptool?

**Comment by sticilface** [comment] 2015-05-01 18:15
1) Because igrr doesn't have access to a 32 bit machine to build it. 
2) it was only asked for last week

There is already a thread about this. 
+ the option for esptool was removed when it was put as the primary method for uploading. So esptool is default. I have to change some things to put it back / use esptool.py

**Comment by igrr** [comment] 2015-05-05 11:27
closing as duplicate of #124 — lets move the discussion there

**Closed by igrr** 2015-05-05 11:27 UTC

**Comment by igrr** [comment] 2015-05-19 06:30
Added 32-bit Linux tools to the board manager package.
