### ISSUE TITLE
broken wifi_softap_set_dhcps_lease function in 3.x.x version

### ISSUE THREAD

**Issue by R3D9477** [esp8266/Arduino#8471] opened 2022-01-31 10:49 UTC
How does DHCP server set IP address of clients ?

Before I did that:

```
    struct ip_info info;
    wifi_set_opmode(STATIONAP_MODE);
    wifi_softap_dhcps_stop();
    IP4_ADDR(&info.ip, 10, 0, 0, 1);
    IP4_ADDR(&info.gw, 10, 0, 0, 1);
    IP4_ADDR(&info.netmask, 255, 255, 255, 0);
    wifi_set_ip_info(SOFTAP_IF, &info);
    
    struct dhcps_lease dhcp_lease;
    IP4_ADDR(&dhcp_lease.start_ip, 10, 0, 0, 100);
    IP4_ADDR(&dhcp_lease.end_ip, 10, 0, 0, 105);
    wifi_softap_set_dhcps_lease(&dhcp_lease);
```

But since version 3.x.x I'm getting compilation exception: undefined reference to `wifi_softap_set_dhcps_lease'

**Comment by mcspr** [comment] 2022-02-20 14:20
Duplicate of #8307 (?)

**Closed by mcspr** 2022-02-20 14:20 UTC
