### ISSUE TITLE
broken board manager url since 2.5.0-beta1 uploaded causing -removal- of esp8266 support from arduino IDE

### ISSUE THREAD

**Issue by buzztiaan** [esp8266/Arduino#5472] opened 2018-12-10 23:42 UTC
The recent uploading of the 2.5.0-beta1 zipfile didnt get paired to creating a release of 2.5.0-beta1, thus breaking the board manager (which then removes all esp8266 boards using this from the menu)

**Comment by buzztiaan** [comment] 2018-12-10 23:45
error msgs from arduino IDE 1.8.5 : 

```
 Error downloading https://github.com/esp8266/Arduino/releases/download/2.5.0-beta1/esp8266-2.5.0-beta1.zip
java.lang.RuntimeException: java.lang.Exception: Error downloading https://github.com/esp8266/Arduino/releases/download/2.5.0-beta1/esp8266-2.5.0-beta1.zip
        at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:176)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading https://github.com/esp8266/Arduino/releases/download/2.5.0-beta1/esp8266-2.5.0-beta1.zip
        at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:131)
        at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:69)
        at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:102)
        at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:173)
        ... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 404
        at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:194)
        at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
        at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:129)
        ... 4 more

```

**Comment by buzztiaan** [comment] 2018-12-10 23:51
fyi, this bug means all Arduino IDE users that have internet now cant compile for their boards

**Comment by diception** [comment] 2018-12-11 00:05
lookes like arduino ide is looking for https://github.com/esp8266/Arduino/releases/download/2.5.0-beta1/esp8266-2.5.0-beta1.zip but the file is actually named https://github.com/esp8266/Arduino/releases/download/2.5.0-beta1/Arduino-2.5.0-beta1.zip

**Comment by buzztiaan** [comment] 2018-12-11 00:12
so probably a typo in http://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by buzztiaan** [comment] 2018-12-11 00:14
actually, shouldnt that json have more versions anyway, instead of just the latest beta version?

**Comment by igrr** [comment] 2018-12-11 00:51
The json served from http://arduino.esp8266.com/stable/package_esp8266com_index.json has been reverted to contain 2.4.2 and previous release. We are looking into the cause of this issue (new json not containing the previous versions).

**Comment by devyte** [comment] 2018-12-11 01:11
Closing as duplicate.

**Closed by devyte** 2018-12-11 01:11 UTC

**Comment by buzztiaan** [comment] 2018-12-11 10:44
what was the duplicate? i searched prior but found none

**Comment by dav1901** [comment] 2018-12-11 10:53
#5471 is the one
