### ISSUE TITLE
Heartbeat timeout when I use Wifi.Mode(WIFI_AP_STA)

### ISSUE THREAD

**Issue by MikyMouse90** [esp8266/Arduino#4262] opened 2018-01-30 18:43 UTC
#### Hardware
Hardware:		ESP-8266 Wemos D1 Mini

### Description

Problem description
Heartbeat timeout

#define BLYNK_PRINT Serial

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <WiFiClient.h>

char auth[] = "9e3f495xxxxx";

char ssid[] = "xxxxx"; //SSID Wi-Fi
char pass[] = "xxxxx";       //PSW Wi-Fi

WiFiServer server(80);
IPAddress IP(192,168,4,15);
IPAddress mask = (255, 255, 255, 0);

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_AP_STA);

  Blynk.begin(auth, ssid, pass);
  
  WiFi.softAP("Wemos_AP", "Wemos_comm");
  WiFi.softAPConfig(IP, IP, mask);
  server.begin();
  
}

void loop()
{
  Blynk.run();
}

I can't connect blynk to wemos when I use Wifi.Mode(WIFI_AP_STA).
The issue below.

![schermata 2018-01-30 alle 19 34 00](https://user-images.githubusercontent.com/35971745/35584529-93681212-05f5-11e8-8e9a-19d14a85e665.png)

Any idea?

**Comment by devyte** [comment] 2018-01-30 21:57
I suggest asking for an investigation from Blynk. If the issue is narrowed down to something specific in the core hosted in this repo, please open a new issue and include the details so that it can be investigated here.
Closing as off topic.

**Closed by devyte** 2018-01-30 21:57 UTC
